### ISSUE TITLE
Blank page is loaded instead for normal site.

### ISSUE THREAD

**Issue by Conjuror** [mozilla-mobile/FirefoxLite#1023]
as title.

Visit Topopedia via Top sites. The webpage is blank.

Build: 1412 RC
DuT: Redmi

**Comment by Conjuror** [comment]
After more investigation, we cannot reproduce it consistently.

Some STR for it:

1. Launch Zerda
2. Tap on a top site
3. tap on home
4. Tap on a top site
5. Repeat step 3&4

A user will have a chance to observe a blank page with a quick progress bar animation and it's like the loading is done.

**Comment by chianger** [comment]
Its reproducing rate is not too high so downgrade to p1.5

**Comment by mTwTm** [comment]
Possibly duplicate to #796

**Comment by NashTung** [comment]
It seems that can be reproduced it?
Video: https://drive.google.com/open?id=1Q6PoEttoQbNDUmyt2K0k2_R2qBGJpDTo

Device: Redmi 4A
Rocket: 2.1.0(4512).nightly
Android: 7.1.2
Android Webview: 66.0.3359.158

**Comment by mTwTm** [comment]
The blank page here is referring to a view that is plain white so maybe different from the recording provided by Nash.
