### ISSUE TITLE
[Webcompat] Unsupported browser on github with mito (device related)

### ISSUE THREAD

**Issue by dakaizou** [mozilla-mobile/FirefoxLite#1025]
Visit [github.com](https://github.com/) or Privacy Notice to check the banner.
Other devices seem working fine

Build: 1412 RC 1
DuT: samsung, mito, advan

**Comment by chianger** [comment]
agree P1.5 but not blocking RC1/RC2. Changing user agent would potentially creates web compat regressions so we need to be cautious.

**Comment by chianger** [comment]
QAWanted: can you attach a screenshot so that we understand better?

**Comment by chianger** [comment]
P2, assuming it refreshes after user close and bring up the download panel again.

**Comment by NashTung** [comment]
This issue can be reproduced
Picture:
https://drive.google.com/open?id=1Wd1QlX05xpFpGWVZwEvJMfuNsJ85xbSM

Device: Advan i5C
Rocket: 2.0.0(4168).nightly
Android: 5.1
Android Webview: 51.0.2704.81
