### ISSUE TITLE
[Smoke Test] Renamed file names after the 10th time seems out of order

### ISSUE THREAD

**Issue by dakaizou** [mozilla-mobile/FirefoxLite#1029]
![screenshot](https://lh3.googleusercontent.com/-HHBqrIqbjhQ/WdGV3np7_wI/AAAAAAAABWU/9bS0XmraLHkuxj5n8kM4U-Nf9EW8OylIwCL0BGAYYCw/h854/8147451443555071485%253Faccount_id%253D0)

P2/P3 suggested

Build: 1413
DuT: Advan, Samsung

**Comment by chianger** [comment]
This is download manager's behavior so we didn't do anything on it.
P3 for future tracking
