### ISSUE TITLE
[Smoke Test] Screenshot only captures part of the page

### ISSUE THREAD

**Issue by dakaizou** [mozilla-mobile/FirefoxLite#1030]
See [recording](https://drive.google.com/file/d/0B0uVZlaHN366UF9IbEx0LW1wSFU/view?usp=sharing)

Build: 1413
DuT: Advan, Samsung

**Comment by chianger** [comment]
This happens on website which has long list of radio buttons only.

**Comment by chianger** [comment]
P3.
