### ISSUE TITLE
Unable to download certain image from Google image site

### ISSUE THREAD

**Issue by harly21** [mozilla-mobile/FirefoxLite#1048]
STR:
1. Go to google image site
2. Search Mozilla
3. Tap a Mozilla logo
4. Long press the logo

No save image option in context menu

**Comment by mTwTm** [comment]
Duplicate to #187. #187 was closed since we've changed our agent, but we changed our agent once again so it's back again.

**Comment by chianger** [comment]
base64 unsupported.

**Comment by chianger** [comment]
it requires either refactoring or building inhousee download manager.
mark as feature to track.
