### ISSUE TITLE
Can't screenshot Instagram?

### ISSUE THREAD

**Issue by Jacklin-ux** [mozilla-mobile/FirefoxLite#1059]
After screenshot Instagram, go to My shot then you will see entire white page or part of white page for the Instagram screenshot?!

**Comment by mTwTm** [comment]
I checked old webview versions but they are suffering from the same symptom. My guess would be instagram.com just optimized something if it used to work. (Never tried it myself.)

**Comment by chianger** [comment]
too risky to fix this in two weeks. it takes architecture change.
