### ISSUE TITLE
Add video downloader feature

### ISSUE THREAD

**Issue by joechengla** [mozilla-mobile/FirefoxLite#1078]
Another feedback from Facebook Page:
If this app is intended for Indonesian user, I give some suggestions that might make users love it:
1. Add video downloader feature, which's able to download video from any site.

**Comment by brampitoyo** [comment]
Using unreliable network connection to download large files – like videos – may cause download interruption at some point in the process. Pausing/resuming may be something we need to add to this feature.

**Comment by weslyhuang** [comment]
next step on UX design proposal. (may get China team to help on it?)
