### ISSUE TITLE
A better pop-up and pop-under blocker

### ISSUE THREAD

**Issue by joechengla** [mozilla-mobile/FirefoxLite#1079]
Another feedback from Facebook Page:
If this app is intended for Indonesian user, I give some suggestions that might make users love it:
2. A better pop-up and pop-under blocker, because most of user devices are infected by malware from pop-up/pop-under ads.

**Comment by brampitoyo** [comment]
Do we not have a pop-up/pop-under blocker already implemented in the browser?
