### ISSUE TITLE
YouTube (live?) video does not play smoothly

### ISSUE THREAD

**Issue by cssjh** [mozilla-mobile/FirefoxLite#1101]
**Network Environment**
Connected to a 3G Android hotspot alone with 2 other devices opening other videos

**STR**
1. Open [this](https://www.youtube.com/watch?v=tfw_snadIQw) live streaming video
2. Jump to an earlier time (3:00 for example)
3. The video becomes laggy

**Notes**
1. Chrome works fine
2. Focus doesn't support live streaming

**DuT:** Oppo (can't reproduce), Advan, Redmi

**Build:** 1455

**Comment by cssjh** [comment]
We played a three hour long video on two Sony Z3C under a weak WIFI signal. They worked well.

**Comment by chianger** [comment]
not quite reproducible from QA team at this moment.
