### ISSUE TITLE
Can't use Facebook via games on http://play.ludigames.com/index/

### ISSUE THREAD

**Issue by cssjh** [mozilla-mobile/FirefoxLite#1126]
All Facebook functions (share or log in) in the games on http://play.ludigames.com/index/ don't react. For example: _Siberian Strike_, _Ludibubbles_, _Puzzle Pets: Pairs_ and _Nitro Street Run 2_. Chrome works fine.

If a user taps on Log in Facebook on _[Danger Dash](play.ludigames.com/games/dangerDashFree/)_, a error message will be shown and the game will be frozen. Chrome doesn't have this issue either.

**DuT:** Oppo, Samsung
**Build:** 1512

**Comment by chianger** [comment]
see also #1127

**Comment by joechengla** [comment]
1/ Turbo mode On: no ads, no pop-up allowed -> that’s why FB log-in / share pop-up are disabled by default. Please note that Ads will also be disabled when this mode is on.
2/ Turbo mode Off: ads & fb work as usual

**Comment by joechengla** [comment]
i'm curious on why tracking protection blocks the FB button from responsding.

**Comment by chianger** [comment]
putting in sprint#13 only to investigate and see if we can find the root cause.

**Comment by idiotmax** [comment]
Facebook domain(facebook.com/facebook.net) is in the blocking list. Also, some login process requires popup window, which is not supported in Rocket, will fail even if we disable turbo mode.
