### ISSUE TITLE
Can't play some games on http://play.ludigames.com/index/ in portrait mode

### ISSUE THREAD

**Issue by cssjh** [mozilla-mobile/FirefoxLite#1127]
As title.

The games affected: _Pocket Dessert Chef_, _Nova Covered Ops_, _Pirates: Path of the Buccaneer_, _Out Toughest Game_, _Kite_, _Nitro Tuk Tuk_, _Midnight Pool Classic_ and _Supercape of Justice_.

**DuT:** Oppo, Samsung
**Build:** 1512

**Comment by chianger** [comment]
Rocket is now single tab so it likely a limitation.

**Comment by chianger** [comment]
Only has portrait mode.

**Comment by chianger** [comment]
Possible to reach out to partner to fix from their side?

**Comment by NashTung** [comment]
It can be reproduced .

Device: Redmi 4A
Rocket: 2.1.0(4512).nightly
Android: 7.1.2
Android Webview: 66.0.3359.158
