### ISSUE TITLE
easily trigger context menu when performing scrolling and stop action 

### ISSUE THREAD

**Issue by joechengla** [mozilla-mobile/FirefoxLite#1157]

**Comment by chianger** [comment]
UC mini and Opera also have the same behavior. Chrome doesn't.

**Comment by chianger** [comment]
P2 as not blocking, but we should track to see if these "context menu trigger" are by accident or actualy user behavior

**Comment by chianger** [comment]
for this sprint it's more of a investigation effort.

**Comment by chianger** [comment]
turns out it requires refactoring to do it so let's not do it before multitab lands.
