### ISSUE TITLE
Native crash of org.mozilla.rocket for v0.9(build 1585) during Google Play Concole pre-launch test report

### ISSUE THREAD

**Issue by vanceyen** [mozilla-mobile/FirefoxLite#1159]
*** *** *** *** *** *** *** *** *** *** *** *** *** *** *** ***
Build fingerprint: 'samsung/hero2ltexx/hero2lte:6.0.1/MMB29K/G935FXXU1APB6:user/release-keys'
Revision: '9'
ABI: 'arm64'
pid: 32564, tid: 1084, name: Thread-2181  >>> org.mozilla.rocket <<<
signal 11 (SIGSEGV), code 1 (SEGV_MAPERR), fault addr 0x2
    x0   0000000600000000  x1   0000000000000003  x2   0000000056446661  x3   000000005e688911
    x4   0000007f1760cae9  x5   0000007f1a20b799  x6   0000007f1a20b799  x7   0000000000000000
    x8   0000000000000001  x9   00000000000000b0  x10  0000007f51278290  x11  0000000000000004
    x12  000000005c103130  x13  0000000002000000  x14  0000000056404189  x15  000000005c1c2121
    x16  0000007f1f8211a0  x17  000000005c000000  x18  00000000beeddead  x19  000000005c1c2039
    x20  0000007eeea0d571  x21  0000000052983939  x22  0000007f21f290c0  x23  00000000beeddead
    x24  00000000beeddead  x25  00000000beeddead  x26  0000007f51271038  x27  0000007eeea3daf9
    x28  0000007f3f76edd8  x29  0000007f3f76edf8  x30  0000007f220a3fa4
    sp   0000007f3f76ecb0  pc   0000007f1f8211b8  pstate 0000000020000000
backtrace:
    #00 pc 000000000001b1b8  <unknown>
    #01 pc 000000000009dfa0  <unknown>
Tombstone written to: /data/tombstones/tombstone_00

Logcat also 
[logcat(1).txt](https://github.com/mozilla-tw/Rocket/files/1405610/logcat.1.txt)
attached

**Comment by chianger** [comment]
not found in nightly on play store console. keep p2 to track
