### ISSUE TITLE
Refresh of an error-page does not work on Android 8 

### ISSUE THREAD

**Issue by mTwTm** [mozilla-mobile/FirefoxLite#1167]
STR:

1.   Launch Rocket with connected network
2.   Open any web page, and it would load correctly
3.   turn off WiFi, reload -> now we got error page
4.   turn on WiFi, reload -> got white screen
5.   reload again -> even URL becomes internal-error-url

**Comment by mTwTm** [comment]
Introduced in #1148

**Comment by mTwTm** [comment]
`Try again` will work in Step 4.

**Comment by chianger** [comment]
non-blocking for now as we have fairly small percentage of user using android8. 
we will need to fix soon.

**Comment by chianger** [comment]
only happens above android 8.0.
