### ISSUE TITLE
[Smoke Test] Deleting download file may show both deleted snack bar and cannot find the file toast

### ISSUE THREAD

**Issue by dakaizou** [mozilla-mobile/FirefoxLite#1181]
It seems pretty random, still under investigation.
STR:
1. Delete downloaded file in Downloads panel
2. Before the snack bar disappears, close the menu panel, so the toast won't be overlapped

Reproduce rate: ~10%
Build: 1641
DuT: Samsung J7 with sdcard

**Comment by mTwTm** [comment]
My guess is the timing issue here is if the file is being moved to sdcard, things might work unexpected.
