### ISSUE TITLE
Progress bar stuck after download via link twice

### ISSUE THREAD

**Issue by dakaizou** [mozilla-mobile/FirefoxLite#1185]
Follow the STR of #1180 
>1. Use Exit button to close Rocket
>2. Launch Rocket
>3. Visit this link [http://www.coverr.co/s3/mp4/Mobile-Games.mp4](http://www.coverr.co/s3/mp4/Mobile-Games.mp4)
>4. Tap on url bar and tap go to revisit the link

![screenshot](https://lh3.googleusercontent.com/-lVVAO74X2qk/WfF5rQVRxgI/AAAAAAAABxk/SDDu6X_2u041hGRoAgjjV263uHJkSAfRwCL0BGAYYCw/h1920/8429713593765667249%253Faccount_id%253D3)

Build: 1647
DuT: Samsung J7

**Comment by mTwTm** [comment]
Log:

10-26 14:08:10.701 8646-8646/org.mozilla.rocket.debug.tyu E/mTwTm: loadedUrl = null
10-26 14:08:10.768 8646-8646/org.mozilla.rocket.debug.tyu E/mTwTm:  10 http://www.coverr.co/s3/mp4/Mobile-Games.mp4
10-26 14:08:10.769 8646-8646/org.mozilla.rocket.debug.tyu E/mTwTm:   0  ->  10 
10-26 14:08:11.596 8646-8646/org.mozilla.rocket.debug.tyu E/mTwTm: loadedUrl = null
10-26 14:08:14.043 8646-8646/org.mozilla.rocket.debug.tyu E/mTwTm:  70 http://www.coverr.co/s3/mp4/Mobile-Games.mp4
10-26 14:08:14.044 8646-8646/org.mozilla.rocket.debug.tyu E/mTwTm:  10  ->  70 
10-26 14:08:14.044 8646-8646/org.mozilla.rocket.debug.tyu E/mTwTm: 100 http://www.coverr.co/s3/mp4/Mobile-Games.mp4
10-26 14:08:14.044 8646-8646/org.mozilla.rocket.debug.tyu E/mTwTm: loadedUrl = http://www.coverr.co/s3/mp4/Mobile-Games.mp4
10-26 14:08:14.044 8646-8646/org.mozilla.rocket.debug.tyu E/mTwTm:  10  -> 100 
10-26 14:08:14.049 8646-8646/org.mozilla.rocket.debug.tyu E/mTwTm: 100 http://www.coverr.co/s3/mp4/Mobile-Games.mp4
10-26 14:08:21.522 8646-8646/org.mozilla.rocket.debug.tyu E/mTwTm:  10 http://www.coverr.co/s3/mp4/Mobile-Games.mp4
10-26 14:08:21.528 8646-8646/org.mozilla.rocket.debug.tyu E/mTwTm: loadedUrl = null
10-26 14:08:21.619 8646-8646/org.mozilla.rocket.debug.tyu E/mTwTm:  10 http://www.coverr.co/s3/mp4/Mobile-Games.mp4
10-26 14:08:21.619 8646-8646/org.mozilla.rocket.debug.tyu E/mTwTm: 100  ->  10 
10-26 14:08:21.856 8646-8646/org.mozilla.rocket.debug.tyu E/mTwTm: loadedUrl = null
10-26 14:08:23.098 8646-8646/org.mozilla.rocket.debug.tyu E/mTwTm:  70 null
10-26 14:08:23.099 8646-8646/org.mozilla.rocket.debug.tyu E/mTwTm: 100 null
10-26 14:08:23.099 8646-8646/org.mozilla.rocket.debug.tyu E/mTwTm: loadedUrl = null
10-26 14:08:23.101 8646-8646/org.mozilla.rocket.debug.tyu E/mTwTm: 100 null
10-26 14:08:23.101 8646-8646/org.mozilla.rocket.debug.tyu E/mTwTm: loadedUrl = null

**Comment by mTwTm** [comment]
#1162 is not perfect enough to handle the case when webview.getUrl may go backward to the last item being browsed.

**Comment by chianger** [comment]
the STR is sort of an edge case and user can workaround to recover. P2.

**Comment by NashTung** [comment]
Work for me.
Video:
https://drive.google.com/open?id=1GuCq6MSoqvGxtLWV1ImaPr75VUlExpx9

Device: Redmi 4A
Rocket: 2.0.0(4168).nightly
Android: 7.1.2
Android Webview: 66.0.3359.126
