### ISSUE TITLE
Select image from "Downloads" list will show black screen if revoke the storage access permission

### ISSUE THREAD

**Issue by vanceyen** [mozilla-mobile/FirefoxLite#1191]
Build 1666

Precondition : Rocket -> Settings -> Save downloads to -> Internal storage
Reproduce Steps:

1. Grant Rocket the storage access permission and then download/save an image from any browser.
2. Go to "Setting" -> "Rocket" to revoke the storage access permission.
3. Got to Rocket -> Downloads to select the image from the list

Expect behavior : A prompt will show to ask for storage access permission
Actual behavior : Image is not displayed, only show a black screen

In build 1647, we can still access the image after revoking the storage access permisson of Rocket.

**Comment by chianger** [comment]
P2. Reason: "revoke" is not a usual case. non-blocking.
