### ISSUE TITLE
After editing a screenshot then back to viewer, the screenshot can be changed to the updated one?

### ISSUE THREAD

**Issue by Jacklin-ux** [mozilla-mobile/FirefoxLite#1198]
After using editor then back to the screenshot viewer, show toast "Saved"  but the screenshot looks the same as before. Users need to reopen it then see the difference. Can update to the new one after editing?

**Comment by mTwTm** [comment]
Yeah that's possible.

**Comment by mTwTm** [comment]
Duplicate to #583
