### ISSUE TITLE
Clicking "Share image" shares the link of image, instead of the image itself

### ISSUE THREAD

**Issue by FlyTori** [mozilla-mobile/FirefoxLite#1199]
Rocket and Focus both have this issue, while Fennec and Chrome can send image properly.

1. long press an image then click "Share image" in context menu
![screenshot_20171101-143925](https://user-images.githubusercontent.com/3325366/32265063-6afddd3a-beaf-11e7-8e5f-257e8471a205.png)
2. choose "Line"
3. image sent 
_**Rocket**_
![screenshot_20171101-144143](https://user-images.githubusercontent.com/3325366/32265065-6b493780-beaf-11e7-896a-add4bd7bf59f.png)
**_Chrome_**
![screenshot_20171101-144002](https://user-images.githubusercontent.com/3325366/32265064-6b23fb28-beaf-11e7-88f0-5d9c502a30ba.png)

**Comment by mTwTm** [comment]
+1 for this function. What we're doing is merely share image link now.

**Comment by chianger** [comment]
Same as Focus design

**Comment by chianger** [comment]
Chrome can share image directly.

**Comment by chianger** [comment]
Non-blocking, user has a workaround to save image and do further action. (not ideal though)

**Comment by chianger** [comment]
Expected behavior: share image should share image.
