### ISSUE TITLE
After cropping long screenshot, the cropped screenshot will be blurry and users can't read

### ISSUE THREAD

**Issue by Jacklin-ux** [mozilla-mobile/FirefoxLite#1200]
Just raise a feedback.
If we observe that more and more users would like to crop screenshot, maybe we need to redesign the screenshot flow or provide our own editor to let cropped screenshot has better quality.

**Comment by chianger** [comment]
the crop and resizing is on the editor so we don't have much to do with it.

**Comment by joechengla** [comment]
dup with https://github.com/mozilla-tw/Rocket/issues/834.
