### ISSUE TITLE
Download youtube video file from keepvid.com will become *.bin and also the video name isn't the same as Youtube

### ISSUE THREAD

**Issue by harly21** [mozilla-mobile/FirefoxLite#1201]
This is an issue from user testing in Indonesia:
STR: 
1. Go to youtube.com and select a video
2. Tap share button and copy the video link
3. Go to https://keepvid.com and paste the youtube link to the input field
4. Tap download and select a video to download

Actual result:
The video is downloaded but is saved as videoplayback.bin which will not be displayed in some gallery apps. Also, the name of the file isn't the same as the video name on Youtube

**Comment by chianger** [comment]
lightning has this issue too.

**Comment by harly21** [comment]
The same issue has been reported by user testing on http://en.savefrom.net

**Comment by chianger** [comment]
most likely need implement in-house download manager.

**Comment by mTwTm** [comment]
The onDownloadStart() is returning empty contentDisposition and empty mimetype for this case. I've tried to request for metadata like we do in #1154 while it is returning the mimetype correctly, we can do the #1154 patch but we should really trace why DownloadManager isn't returning the mimetype first.

**Comment by chianger** [comment]
QAwanted to verify if webview64 still has such issue.

**Comment by mTwTm** [comment]
Seems like keepvid is not working anymore? Orz
