### ISSUE TITLE
A page to reproduce ANR

### ISSUE THREAD

**Issue by mTwTm** [mozilla-mobile/FirefoxLite#1204]
https://www.mirrormedia.mg/projects/whitecollar/

**Comment by chianger** [comment]
no in ID top site so not blocking.

**Comment by chianger** [comment]
not happening using Pixel, PixelXL

**Comment by chianger** [comment]
action: figure out what devices can reproduce. (tyu's sony device can)

**Comment by mTwTm** [comment]
My device is sony XA
CPU: MTK Helio P10 (MT6755)
2GB RAM / 16GB ROM

**Comment by ariefbayu** [comment]
Not happening using Xiaomi 4x RAM 3GB version
Rocket 1.0.1 (1777)
OS 7.1.2
