### ISSUE TITLE
Can't play radio at https://www.internet-radio.com/

### ISSUE THREAD

**Issue by mTwTm** [mozilla-mobile/FirefoxLite#1208]
A [link](https://www.internet-radio.com/community/threads/latest-chrome-browser-update-v55-breaks-shoutcast-v1-x-html5-players.27560/)  says 

> We've started showing a "No Web Player" message (Shoutcast v1) for radio stations which won't play in the browser. These stations can still be played but only via the ".pls" and .m3u" links we display above the message.

> The latest update (v55) being rolled out for Google Chrome unfortunately breaks the ability for Shoutcast v1.x servers to be played with HTML5. More specifically support for HTTP/0.9 over non-standard ports has been dropped. Since Shoutcast v1.x uses HTTP/0.9 and runs on a non-standard port (i.e. not 80 or 443) it gives the error "net::ERR_INVALID_HTTP_RESPONSE" when you attempt to play a stream.

**Comment by chianger** [comment]
Opera doesn't play as well.

**Comment by chianger** [comment]
Investigation needed to identify whether it's a webview limitation.
