### ISSUE TITLE
Can not zoom out at https://ibank.bankmandiri.co.id/retail3/

### ISSUE THREAD

**Issue by vanceyen** [mozilla-mobile/FirefoxLite#1216]
STR:
1. open the link https://ibank.bankmandiri.co.id/retail3/
Expected result:
   see the whole page (as opened in Chrome)
Actual result: 
   Already zoom-in on part of the page and cannot zoom out with finger pinch

DUT - Can reproduce on any device
Build - 1.0 - 1692

**Comment by chianger** [comment]
Opera/Chrome/UC Browser: loads at fit-to-width

**Comment by chianger** [comment]
Need to investigate how we handle desktop websites.
