### ISSUE TITLE
Sharing link to external social app doesn’t work

### ISSUE THREAD

**Issue by vanceyen** [mozilla-mobile/FirefoxLite#1220]
STR:
1.  Go to any post at IDN TIMES
2. Click facebook messenger/twitter/line button at the bottom of the page
Expected:
    Open the correspond app
Actual:
    Screen remains on loading page forever (https://sumo.com/apps/share/loading)

DUT: Happens on any device
Build: 1.0 - 1692

**Comment by harly21** [comment]
#889
