### ISSUE TITLE
webpage not available when when entering ',s."'

### ISSUE THREAD

**Issue by cynthiatang** [mozilla-mobile/FirefoxLite#1251]
Step:
 1. Launch Rocket
 2. Enter ',sharebutton.io"' in the URL bar (the string contained in the single quotes)
                   or
     Try to click links to e.g. "http://www.;.com/"

Actual Result:
 - Rocket shows an error page "Webpage not available"
 - Video: https://youtu.be/6u5ke-QRZ-M
 - This issue can be reproduced on Redmi 4A, Sony Z3C and Google Pixel.

Expected Result:
 - User can view the google search results
 - Chrome Video: https://youtu.be/f2ft7Vrp8GM

Reproduction rate: 10/10
Rocket version: 1.0.1710

======================================
Device name: Redmi 4A
Android version: 6.0.1 MMB29M

Device name: Sony Z3C
Android version: 5.0.2 MMB29M

**Comment by mTwTm** [comment]
Root cause:

https://github.com/mozilla-tw/Rocket/blob/5e776dd690a440465c1814c06159470a6344fc85/app/src/main/java/org/mozilla/focus/utils/UrlUtils.java#L48

We're currently only blacklisting ' '
