### ISSUE TITLE
translucent shadow above the bottom navigation bar

### ISSUE THREAD

**Issue by joechengla** [mozilla-mobile/FirefoxLite#1259]
- We suggest adding a translucent shadow above the bottom navigation bar to create some depth and separate it from the web content.

**Comment by carol-mozilla** [comment]
![screen shot 2017-11-29 at 11 36 49 am](https://user-images.githubusercontent.com/6700296/33356837-b05c417c-d4f9-11e7-8110-42fe8a4b06a0.png)

Add **Shadow**
Color : #000000
opacity: 25%
shadow: outer
 * x, y - 0dp, 2dp
 * blur - 4dp
