### ISSUE TITLE
Sometimes the notification button doesn't work (Top 8: tokopedia.com)

### ISSUE THREAD

**Issue by cynthiatang** [mozilla-mobile/FirefoxLite#1268]
STR:
 1. Clear browsing data & close Rocket
 2. Relaunch Rocket
 3. Tap "Tokopedia"
 4. Tap notification button or menu button on the webpage

Actual Result:
 - It does not work. User cannot view his/her notification or menu content. 
 - Video: https://goo.gl/YM3HCn

Chrome's and Focus's Result:
 - It works well.  User can view his/her notification or menu content

Reproduction rate: 2/5
Rocket version: 1.0.1 Build 1777
Device name: Sony Z3C
Android version: 5.0.2

**Comment by mTwTm** [comment]
To me, this sounds like P1 and is blocking the release if it's a regression.

**Comment by cynthiatang** [comment]
This issue can be reproduced on Sony Z3C with Rocket 1.0.1710.

Reproduction rate: 2/5
Rocket version: 1.0.1710
Device name: Sony Z3C
Android version: 5.0.2
