### ISSUE TITLE
Highlighted text's behavior is inconsistent

### ISSUE THREAD

**Issue by dakaizou** [mozilla-mobile/FirefoxLite#1272]
STR:
 1. Visit a website
 2. Tap url
 3. Tap system back key
 4. __The highlighted text remains__
 5. Tap system back key
 6. Tap search button
 7. Type in any character to see autocomplete
 8. Tap system back key
 9. __The highlighted text deleted__

Expected Result:
 - Highlighted text behaves consistently

Actual Result:
 - Hightlighted text behaves inconsistently
 - Recording: https://drive.google.com/open?id=1SRHGW00nFnI1sujjThAP76phHmzNzpeJ

Reproduction rate: 5/5
Rocket version: 1.0.1 Build 1777

Device name: Samsung S7 edge
Android version: 7.0

Device name: Redmi 4A
Android version: 6.0

**Comment by mTwTm** [comment]
The first highlight is selection (for copy), while the second is autocompleted text, they're visually the same but not semantically equivalent.

**Comment by NashTung** [comment]
This issue can be reproduced.
Video: 
https://drive.google.com/open?id=1s_raJi7ikOeJ8svdZZLXOBNgQqLbNQRu

Device: Redmi 4A
Rocket: 2.0.0(4168).nightly
Android: 7.1.2
Android Webview: 66.0.3359.126
