### ISSUE TITLE
The permission dialog reprompt after granting permission

### ISSUE THREAD

**Issue by dakaizou** [mozilla-mobile/FirefoxLite#1273]
STR:
 1. Clear app data
 2. Visit [maps.google.com](https://www.google.com.tw/maps)
 3. Tap Allow (for website)
 4. Tap Allow (for application)

Expected Result:
 - Get the user's location

Actual Result:
 - Prompt for permission
 - Recording: https://drive.google.com/open?id=1LoCbcHHH4Qryp-LLbndfyqBsxx7AP9UH

Reproduction rate: 5/5
Rocket version: 1.0.1 Build 1777

Device name: Samsung S7 edge
Android version: 7.0

Related to #1262, #644, #295

**Comment by dakaizou** [comment]
Only happens on android 7+

**Comment by NashTung** [comment]
This issue can be reproduced.
Video:
https://drive.google.com/open?id=1P7lj2pOO1gwD8xt9Nw9ntvl-x7dJmiPc

Device: Redmi 4A
Rocket: 2.0.0(4168).nightly
Android: 7.1.2
Android Webview: 66.0.3359.126
