### ISSUE TITLE
File manager opens wrong location

### ISSUE THREAD

**Issue by dakaizou** [mozilla-mobile/FirefoxLite#1274]
STR:
 1. Download any picture
 2. When finished, tap OPEN on snack bar
 3. Choose the file manager

Expected Result:
 - Open the picture's location with file manager

Actual Result:
 - The file manager doesn't open the correct location
 - Recording(internal): https://drive.google.com/open?id=1r6_zT2ym5E_ZPLpeGru_rM__ovaBJHgO
 - Recording(sd): https://drive.google.com/open?id=1OrBZkXCsvYLwRjnrjfh4sTFhcoTSJn_9

Reproduction rate: 5/5
Rocket version: 1.0.1 Build 1777

Device name: Redmi 4A
Android version: 6.0

**Comment by mTwTm** [comment]
Hi @dakaizou can you help clarify these:
Is it only reproducing with that manager app? (It would definitely be a release blocking bug if this is not a single-app symptom.)
If yes, can I have the package name of the app? (Looks like a redmi app?)

**Comment by dakaizou** [comment]
@mTwTm The Gallery and Google Photos seem working fine.
The file manager package name: com.android.fileexploreer

**Comment by chianger** [comment]
Is this file manager a built-in app on Redmi? @dakaizou 
In that case we should P1 it.

**Comment by dakaizou** [comment]
Yes, it's Redmi built-in app.

**Comment by NashTung** [comment]
This issue can be reproduced.
Video:
Internal storage: https://drive.google.com/open?id=1412BzHDOxkG625xkMl0hLCxHq3a8Pi0f
SD: https://drive.google.com/open?id=1N6TW4gLyXAfkDnSCdZsAZuAa6IsXhQMx

Device: Redmi 4A
Rocket: 2.0.0(4168).nightly
Android: 7.1.2
Android Webview: 66.0.3359.126

**Comment by mTwTm** [comment]
Just a wild guess. Noticed that the "Move to" action is clicked. Could it be that what we're expecting to be "open the current folder" is actually "Pick a place to move to" and it is thus empty?

**Comment by NashTung** [comment]
Hi Teng-pao Yu:
I think the bug is that you said

Expected Result:
Open the current folder that picture downloaded

Actual Result:
Pick a place to move to and it is thus empty

**Comment by mTwTm** [comment]
Thanks! Sounds like an invalid bug to me then @cynthiatang do you agree?
