### ISSUE TITLE
Canceled downloading items remain in the Download panel for 7.0 devices

### ISSUE THREAD

**Issue by dakaizou** [mozilla-mobile/FirefoxLite#1276]
STR:
 1. Download a large file
 2. Cancel the file with download manager

Expected Result:
 - The download is canceled properly

Actual Result:
 - The item becomes Unknown in Download panel
 - Recording: https://drive.google.com/open?id=1LziI5Q1Cj6nYG1Bo6W9Ei5FCP3q6ACPX

Reproduction rate: 5/5
Rocket version: 1.0.1 Build 1777

Device name: Samsung S7 edge
Android version: 7.0

Device name: Redmi 4A
Android version: 6.0

**Comment by chianger** [comment]
@mTwTm to investigate first.

**Comment by cynthiatang** [comment]
Verified: Failed

Video: https://goo.gl/Jhd2km

Samsung J7
Rocket: 1.0.4 (2109).nightly
Android: 7.0
WebView: 64.0.3282.137

**Comment by chianger** [comment]
not blocking 1.1, but let's target on 2.0.

**Comment by chianger** [comment]
android 7.0 only. can't repro on 7.1 .

**Comment by mTwTm** [comment]
Reproduced on Android 7.0 devices and emulator, Android 7.1.1 is good. No cancel in notification on Android 6.0 so the only impacted are Android 7.0 devices.

**Comment by weslyhuang** [comment]
only impacted are Android 7.0 devices and user still able to clear it, change to S2

**Comment by NashTung** [comment]
Hi mTwTm

Due to I only have Android 7.1 mobile phone, I just try it on new version Rocket 2.0 nightly.

**Comment by mTwTm** [comment]
Yeah I know. I'm just trying to comment to point this out so people reading this bug won't be confused.
