### ISSUE TITLE
Promotion dialog pops out even if user is still onboarding

### ISSUE THREAD

**Issue by dakaizou** [mozilla-mobile/FirefoxLite#1277]
STR:
 1. Clear app data
 2. Launch Rocket
 3. Close Rocket
 4. Repeat step 2 and 3 five times
 5. Launch Rocket

Expected Result:
 - User is still onboarding, so there shouldn't be promotion dialog

Actual Result:
 - Promotion dialog pops out
 - ![Screenshot](https://lh3.googleusercontent.com/-uQJcJK0NshA/WiQ37u_k_uI/AAAAAAAAB5Y/fIsrm51ny1goUxaY--AtuohVLeOK9nJWwCL0BGAYYCw/h1920/3584542525073980565%253Faccount_id%253D1)

Reproduction rate: 5/5
Rocket version: 1.0.1 Build 1777

Device name: Samsung S7 edge
Android version: 7.0

Device name: Redmi 4A
Android version: 6.0

**Comment by chianger** [comment]
Edge case so P3.

**Comment by NashTung** [comment]
This issue can be reproduced.
Video:
https://drive.google.com/open?id=1ykQeODNyaQuc9L6Qcv0kUfoq3BCLUgc9

Device: Redmi 4A
Rocket: 2.0.0(4168).nightly
Android: 7.1.2
Android Webview: 66.0.3359.126
