### ISSUE TITLE
Sometimes the display cannot go to sleep when playing audio (Top11: Kompas.com)

### ISSUE THREAD

**Issue by cynthiatang** [mozilla-mobile/FirefoxLite#1279]
#Prerequisite:
 - Go to Android Settings -> Display -> Sleep -> Select "15 seconds" (After 15 seconds of inactivity)

STR:
 1. Launch Rocket
 2. Play audio from http://indeks.kompas.com/radio/sonora
 3. Wait for 20 seconds
 4. Launch Chrome
 5. Play audio from http://indeks.kompas.com/radio/sonora
 6. Wait for 20 seconds
 7. Repeat step1 to step6 twice or more 

Rocket's Result:
 - The display cannot go to sleep 
 -  Video: https://youtu.be/6vBdLZ8jjY4

Chrome's Result:
 - The display can go to sleep 

Reproduction rate: 4/5
Rocket version: 1.0.1 Build 1777
Device name: Sony Z3C
Android version: 5.0.2

**Comment by chianger** [comment]
P1 for it has wakelock
