### ISSUE TITLE
http://www.kompas.com/ should without a green lock

### ISSUE THREAD

**Issue by Conjuror** [mozilla-mobile/FirefoxLite#1298]
As title. http://www.kompas.com/ is not a safe connection and should be without a green lock.

STR:

1. Launch Zerda
2. visit a secure website (i.e. yahoo.com)
3. before the loading is complete, hit search button and type "k" and go". To visit http://www.kompas.com/
4. Check the URL bar

Expected result:

4. URL without a green lock

Actual Result:

4. URL with a green lock

Reproduce Rate: High (above 70%)

Build 1803
Device J7 Prime
Android 6.0.1
WebView 62

**Comment by cynthiatang** [comment]
Build 1803 
Device: Nexus 5

**Comment by Conjuror** [comment]
If you press back key quickly, some webpages won't display green lock even it should.

**Comment by mTwTm** [comment]
Can also reproduce on Xiaomi Android 7 / Webview 61 / Rocket 1710

**Comment by chianger** [comment]
per comment above this is not a regression.

**Comment by chianger** [comment]
triage: S2. non regression and not easy to reproduce. still some potential risk so keep S2.

**Comment by NashTung** [comment]
It seems that the url "http://www.kompas.com/' is always a secure website.
Video:  https://drive.google.com/open?id=1uvfCM0TnbKrnC_D78Ny9Z5nMlpILdO5X

Device: Redmi 4A
Rocket: 2.1.0(4512).nightly
Android: 7.1.2
Android Webview: 66.0.3359.158
