### ISSUE TITLE
Cannot get geolocation on Nexus 5

### ISSUE THREAD

**Issue by Conjuror** [mozilla-mobile/FirefoxLite#1300]
This is a device-specific issue that cannot reproduce on other devices.

STR

1. Launch Zerda
2. Visit a website with permission requested (i.e. maps.google.com
3. Grant the permission requests 

Expect Result

2. Prompt is shown to request for permission
3. Website is accessiable correctly

Actual Result

3. Website cannot show current position

Nexus 5
Android 6.0.1
WebView 63
Build 1803

**Comment by chianger** [comment]
triage: S3 for it's device specific and this is not target device.
