### ISSUE TITLE
The URL bar bg color breaks and becomes white when loading a site

### ISSUE THREAD

**Issue by carol-mozilla** [mozilla-mobile/FirefoxLite#1305]
STR:
1. Start from 'home'
2. Go to a website and wait for it to load.

Expected Result:
The address bar bg is the same grey as status bar color.

Actual Result:
There's only a divider below the address bar and the address bar bg become white.
After the site is full loaded, the bg is still white and the status bar become white as well!

![screenshot_20180110-114849](https://user-images.githubusercontent.com/6700296/34758988-66942ece-f614-11e7-91b3-978ad126366d.png)
![screenshot_20180110-114858](https://user-images.githubusercontent.com/6700296/34758989-66bee36c-f614-11e7-9a42-3e1fe5795bee.png)

**Comment by chianger** [comment]
I tried v1.0 (1710) and it's the same as what it is now (v1.0.2 1816)

**Comment by chianger** [comment]
triage: major visual impact.
