### ISSUE TITLE
Failed to open the website when visiting someone’s Facebook

### ISSUE THREAD

**Issue by cynthiatang** [mozilla-mobile/FirefoxLite#1307]
STR:
 1. Visit someone’s Facebook. For example https://m.facebook.com/mozilla 
 2. Scroll down and find the website and social link. For example: http://www.mozilla.org 
 3. Tap the link.  For example: http://www.mozilla.org 

Expected Result:
 - User can visit the website http://www.mozilla.org 

Actual Result:
 - Nothing happen

Lightning and Chrome:
 - User can visit the website http://www.mozilla.org 

![1319080615437340510](https://user-images.githubusercontent.com/12458450/34796784-97795460-f691-11e7-93f0-525da3db84cb.png)

Device: Nexus 5
Android: 6.0.1
WebView: 63.0.3239.111

**Comment by chianger** [comment]
oops. PixelXL can reproduce this. My webview is 63 and android is 8.0.

**Comment by mTwTm** [comment]
I can visit it, but the link is black instead of blue. NOKIA 6 (ANDROID 7, WEBVIEW 63)

**Comment by chianger** [comment]
S1: Function not work
