### ISSUE TITLE
Missing history when visit one of Recommended page in vk.com

### ISSUE THREAD

**Issue by cynthiatang** [mozilla-mobile/FirefoxLite#1308]
STR:
 1. Launch Rocket
 2. Go to  vk.com and login with your Facebook
 3. Tap one of Recommended page.  For example: Elektromontenur  (Figure1)
 4. Tap Rocket Menu button -> Tap History  

Expected Result:
 - After step3: it will be redirected to https://m.vk.com/elektromonteur
 - After step4: There is a history 
    - Title: Elektromonteur
    - Url:   https://m.vk.com/elektromonteur

Actual Result:
 - No history about Elektromonteur (Figure2)

Lightning and Chrome:
 - After step3: it will be redirected to https://m.vk.com/elektromonteur
 - After step4: There is a history (Figure3)
    - Title: Elektromonteur
    - Url:   https://m.vk.com/elektromonteur

![2861454726656495675](https://user-images.githubusercontent.com/12458450/34798444-0d503cee-f697-11e7-9371-340d32caaeaf.png)

![1429167512885447859](https://user-images.githubusercontent.com/12458450/34798445-0d799ce2-f697-11e7-9297-c73720371bce.png)

![5691708190239521145](https://user-images.githubusercontent.com/12458450/34798443-0d1d2a70-f697-11e7-81c0-21b0c368811a.png)

Device: Nexus 5
Android: 6.0.1
WebView: 63.0.3239.111

**Comment by chianger** [comment]
can repro on android 8.1/webview63, PixelXL.

**Comment by chianger** [comment]
S1 for key features not function as expected
