### ISSUE TITLE
Failed to login Lazada.co.id with Facebook account when users turn on "Turbo mode",   (Top 13 )

### ISSUE THREAD

**Issue by cynthiatang** [mozilla-mobile/FirefoxLite#1311]
STR:
 1. Launch Rocket
 2. Go to lazada.co.id with your Facebook account
 3. Go to lazada.co.id with your Google account
 4. Turn off "Turbo Mode"
 5. Repeat step2 and step3

Expected Result:
 - User can log into lazada.co.id with Facebook account successfully 
 - User can log into lazada.co.id with Google account successfully 

Actual Result:
 - Failed to login with Facebook account
 - Failed to login with Google account
 
Rocket 1.0.2 (1816)
Device: Nexus 5
Android: 6.0.1
WebView: 63.0.3239.111

**Comment by mTwTm** [comment]
Related to #1126

**Comment by chianger** [comment]
sounds like multitab can make this work, but still under non-turbo mode.

**Comment by chianger** [comment]
S1: function not working as expected.

**Comment by cynthiatang** [comment]
Updated the status
Only failed to login lazada.co.id with your Facebook account (Enable Turbo Mode)
