### ISSUE TITLE
Excessive Mobile Network Usage in Background

### ISSUE THREAD

**Issue by joechengla** [mozilla-mobile/FirefoxLite#1325]
Refer to Google Play

**Comment by chianger** [comment]
probably relevant to #1229

**Comment by cynthiatang** [comment]
Hi Joe, I just checked it from Google Play.
Excessive network usage (backgroud) is Bad behaviour (0.43%). But it only happened in Xiaomi Mi A1 (tissot_sprout) (Android 8.0.0). Thanks.

**Comment by joechengla** [comment]
it looks like we can continue to monitor this bug 
but is there anything we can do to debug such issue?

**Comment by mTwTm** [comment]
Prerequisite:

1. We'll need that device
2. We need to figure out or have a way to emulate how Google Play is monitoring this. (Need some testing infrastructure change)
3. With 2 we might have a way to find out what's happening and then we can start study which part of our code had lead to this.

Probably doable but requires lots of works.
