### ISSUE TITLE
Permission - Failed to start locating after allowing permission via snack bar

### ISSUE THREAD

**Issue by cynthiatang** [mozilla-mobile/FirefoxLite#1329]
Prerequisite
 1. Location Permission in system is Disabled
 2. First time to use the storage permission

STR:  (Please refer [Firefox Rocket] Home, search, settings v2.4.pdf, page 48)
 1. Launch Rocket
 2. Navigate to maps.google.com
 3. Tap DENY
 4. Tap Settings in Snack bar
 5. Enable location permission in system
 6. Tap Back key twice to back to the previous page
 7. Tap ALLOW to start locating
 
Expected result:
 - It starts locating.

Actual result: 
 - Failed to start locating.
 - Video: https://goo.gl/XY31jp

Device: Nexus 5
Rocket nightly: 1853
Android version: 6.0.1
WebView version: 63.0.3239.1111

**Comment by mTwTm** [comment]
I can reproduce this, seems to relate to #1328

**Comment by cynthiatang** [comment]
Sorry, there is no Snack Bar in Rocket 1.0.2. Because it's a new feature. 
Rocket 1.0.2 cannot starts locating after turn on location

Device: Nexus 5
Rocket nightly: 1816
Android version: 6.0.1
WebView version: 63.0.3239.1111

Device: Sony Z3C
Rocket nightly: 1816
Android version: 6.0.1
WebView version: 63.0.3239.1111
