### ISSUE TITLE
Screenshot long web catches

### ISSUE THREAD

**Issue by annie101101046** [mozilla-mobile/FirefoxLite#1363]
Firefox not yet able to store screenshot long web catches. Hope can save a long screen page in the future.

**Comment by chianger** [comment]
I thought Rocket can already do a full (and long) webpage for most websites. Maybe he/she encountered some exceptions?

**Comment by mTwTm** [comment]
Or she has a very basic phone. Not sure if that could happen though.

**Comment by mTwTm** [comment]
An example of the page that can't be captured would be some of the longest Wikipedia articles https://en.wikipedia.org/wiki/Special:LongPages
