### ISSUE TITLE
Screenshots fail

### ISSUE THREAD

**Issue by annie101101046** [mozilla-mobile/FirefoxLite#1379]
Sometimes screenshots fail on some websites like wikihow.

**Comment by chianger** [comment]
works quite alright by using Pixel XL (android8). 
The major paragraphs are screenshots, though the bottom "Related wikiHows" are lack of thumbnails. It's probably because webview doesn't really render the bottom part yet. (Similar to twitter issue #321)

**Comment by joechengla** [comment]
or could this be webview not updated?

**Comment by NashTung** [comment]
This issue can be reproduced on website Wikihow, Twitter and Instagram

**1. Wikihow :** 
The movie "How to Boil Eggs" on Wikihow home:
a. Rocket 2.0 nightly: cannot be screenshot:
Video: https://drive.google.com/open?id=1HwVE3EhI0-T_gZiRrs-zrEZKwDDMmgqu
Picture: https://drive.google.com/open?id=1kjmfqJij_yLs07uYjow9KkOxIy7gnZXW
b. System: can be screenshot:
Picture: https://drive.google.com/open?id=1Zd7qlDMld2_KQYBUVTHByp6dD8NDz5qO

The bottom bar:
a. Rocket 2.0 nightly: cannot be review under MyShots function: 
Picture: https://drive.google.com/open?id=1LZEbDiJevhdxXdXry7jMQ4ud7KS3Emu1
b. System: can be screenshot:
Picture: https://drive.google.com/open?id=1rNgUAml4AoEqnSb84eC4zaSx5BVr14Du

**2. Twitter:**
Rocket 2.0 nightly: amount of blank space
Video: https://drive.google.com/open?id=167-wLpewinyVI5QIH4Ras8CbUDADoI8E

**3. Instagram:**
Rocket 2.0 nightly: amount of blank space
Video: https://drive.google.com/open?id=167-wLpewinyVI5QIH4Ras8CbUDADoI8E

Device: Redmi 4A
Rocket: 2.0.0(4168).nightly
Android: 7.1.2
Android Webview: 66.0.3359.126
