### ISSUE TITLE
Optimized for the reload button instead of the home button

### ISSUE THREAD

**Issue by annie101101046** [mozilla-mobile/FirefoxLite#1384]
I think the most important element in the browser is the reload button instead of the home button.

Here are the reasons:
1) why firefox create a special browser in Indonesia? because the wifi connection problem is not stable. what happens when the wifi connection is unstable? people will press reload button, not the home button. 
2) try a / b testing. I guess the user will input URL, click x, or type new address instead of pushing the home button. 
3) Rocket is a browser, not a website.

**Comment by chianger** [comment]
It's a feature suggestion. let's triage it.
