### ISSUE TITLE
Failed to play the animation above the search bar automatically (Google.co.id)

### ISSUE THREAD

**Issue by cynthiatang** [mozilla-mobile/FirefoxLite#1444]
STR:
 1. Launch Rocket
 2. Visite google.co.id

Expected result:
 - Rocket can play flash automatically

Actual result: 
 - Failed to play flash automatically
 - Video: https://drive.google.com/open?id=1pFeMF-msqSYdYVVa75zx-YYuQEWRdV0I

This issue cannot be reproduced in Rocket 1.0.3 (1915), Focus, and Chome 

Devices: Samsung J7
Rocket: 1.0.4 (2109)
Android: 7.0
WebView: 64.0.3282.137

**Comment by chianger** [comment]
The link to video seems to be a wrong one. It is a process of installing the update.

**Comment by cynthiatang** [comment]
Thank you. https://drive.google.com/open?id=1pFeMF-msqSYdYVVa75zx-YYuQEWRdV0I

**Comment by chianger** [comment]
Update: 
the "release" flavor isn't affected while "nightly" flavor is impacted.

**Comment by Conjuror** [comment]
A quick investigation into the issue:

- Google Doodles are based on GIF for a long time. Therefore, it has nothing to do with flash.
- this is a permalink for trouble shooting: http://g.co/doodle/y6xhkd
- The symptom is more like [gif](https://www.google.com/logos/doodles/2018/doodle-snow-games-day-15-5907794870927360.3-2xa.gif) cannot displayed correctly
- Build 1.0.4(2383) seems good to play everything.

Suggest to close the issue as invalid if we have nothing to do with it.
