### ISSUE TITLE
StrictModeDiskReadViolation: org.mozilla.focus.utils.StorageUtils.getFirstRemovableMedia

### ISSUE THREAD

**Issue by mxlius** [mozilla-mobile/FirefoxLite#1478]
03-05 15:58:44.244 17046 17046 D StrictMode:    at android.app.FragmentManagerImpl.dispatchMoveToState(FragmentManager.java:3032)
03-05 15:58:44.244 17046 17046 D StrictMode:    at android.app.FragmentManagerImpl.dispatchActivityCreated(FragmentManager.java:2979)
03-05 15:58:44.244 17046 17046 D StrictMode:    at android.app.FragmentController.dispatchActivityCreated(FragmentController.java:178)
03-05 15:58:44.244 17046 17046 D StrictMode:    at android.app.Activity.performCreate(Activity.java:7005)
03-05 15:58:44.244 17046 17046 D StrictMode:    at android.app.Activity.performCreate(Activity.java:6990)
03-05 15:58:44.244 17046 17046 D StrictMode:    at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1214)
03-05 15:58:44.244 17046 17046 D StrictMode:    at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2731)
03-05 15:58:44.244 17046 17046 D StrictMode:    at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2856)
03-05 15:58:44.244 17046 17046 D StrictMode:    at android.app.ActivityThread.-wrap11(Unknown Source:0)
03-05 15:58:44.244 17046 17046 D StrictMode:    at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1589)
03-05 15:58:44.244 17046 17046 D StrictMode:    at android.os.Handler.dispatchMessage(Handler.java:106)
03-05 15:58:44.244 17046 17046 D StrictMode:    at android.os.Looper.loop(Looper.java:164)
03-05 15:58:44.244 17046 17046 D StrictMode:    at android.app.ActivityThread.main(ActivityThread.java:6494)
03-05 15:58:44.244 17046 17046 D StrictMode:    at java.lang.reflect.Method.invoke(Native Method)
03-05 15:58:44.244 17046 17046 D StrictMode:    at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:438)
03-05 15:58:44.244 17046 17046 D StrictMode:    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:807)
03-05 15:59:44.247   870  2367 W ActivityManager: handleApplicationStrictModeViolation; res=0
03-05 15:59:44.248 17046 17046 D StrictMode: StrictMode policy violation; ~duration=7 ms: android.os.StrictMode$StrictModeDiskReadViolation: policy=196671 violation=2
03-05 15:59:44.248 17046 17046 D StrictMode:    at android.os.StrictMode$AndroidBlockGuardPolicy.onReadFromDisk(StrictMode.java:1440)
03-05 15:59:44.248 17046 17046 D StrictMode:    at java.io.UnixFileSystem.checkAccess(UnixFileSystem.java:251)
03-05 15:59:44.248 17046 17046 D StrictMode:    at java.io.File.exists(File.java:807)
03-05 15:59:44.248 17046 17046 D StrictMode:    at android.app.ContextImpl.ensureExternalDirsExistOrFilter(ContextImpl.java:2463)
03-05 15:59:44.248 17046 17046 D StrictMode:    at android.app.ContextImpl.getExternalMediaDirs(ContextImpl.java:694)
03-05 15:59:44.248 17046 17046 D StrictMode:    at android.content.ContextWrapper.getExternalMediaDirs(ContextWrapper.java:282)
03-05 15:59:44.248 17046 17046 D StrictMode:    at org.mozilla.focus.utils.StorageUtils.getFirstRemovableMedia(StorageUtils.java:91)
03-05 15:59:44.248 17046 17046 D StrictMode:    at org.mozilla.focus.utils.StorageUtils.getAppMediaDirOnRemovableStorage(StorageUtils.java:34)
03-05 15:59:44.248 17046 17046 D StrictMode:    at org.mozilla.focus.widget.DataSavingPathPreference.pingRemovableStorage(DataSavingPathPreference.java:74)
03-05 15:59:44.248 17046 17046 D StrictMode:    at org.mozilla.focus.widget.DataSavingPathPreference.onAttachedToActivity(DataSavingPathPreference.java:35)
03-05 15:59:44.248 17046 17046 D StrictMode:    at android.preference.PreferenceGroup.onAttachedToActivity(PreferenceGroup.java:281)
03-05 15:59:44.248 17046 17046 D StrictMode:    at android.preference.PreferenceScreen.bind(PreferenceScreen.java:169)
03-05 15:59:44.248 17046 17046 D StrictMode:    at android.preference.PreferenceFragment.bindPreferences(PreferenceFragment.java:385)
03-05 15:59:44.248 17046 17046 D StrictMode:    at android.preference.PreferenceFragment.onActivityCreated(PreferenceFragment.java:208)
03-05 15:59:44.248 17046 17046 D StrictMode:    at android.app.Fragment.performActivityCreated(Fragment.java:2517)
03-05 15:59:44.248 17046 17046 D StrictMode:    at android.app.FragmentManagerImpl.moveToState(FragmentManager.java:1299)
03-05 15:59:44.248 17046 17046 D StrictMode:    at android.app.FragmentManagerImpl.addAddedFragments(FragmentManager.java:2407)
03-05 15:59:44.248 17046 17046 D StrictMode:    at android.app.FragmentManagerImpl.executeOpsTogether(FragmentManager.java:2186)
03-05 15:59:44.248 17046 17046 D StrictMode:    at android.app.FragmentManagerImpl.removeRedundantOperationsAndExecute(FragmentManager.java:2142)
03-05 15:59:44.248 17046 17046 D StrictMode:    at android.app.FragmentManagerImpl.execPendingActions(FragmentManager.java:2043)
03-05 15:59:44.248 17046 17046 D StrictMode:    at android.app.FragmentManagerImpl.dispatchMoveToState(FragmentManager.java:3032)
03-05 15:59:44.248 17046 17046 D StrictMode:    at android.app.FragmentManagerImpl.dispatchActivityCreated(FragmentManager.java:2979)
03-05 15:59:44.248 17046 17046 D StrictMode:    at android.app.FragmentController.dispatchActivityCreated(FragmentController.java:178)
03-05 15:59:44.248 17046 17046 D StrictMode:    at android.app.Activity.performCreate(Activity.java:7005)
03-05 15:59:44.248 17046 17046 D StrictMode:    at android.app.Activity.performCreate(Activity.java:6990)
03-05 15:59:44.248 17046 17046 D StrictMode:    at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1214)
03-05 15:59:44.248 17046 17046 D StrictMode:    at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2731)
03-05 15:59:44.248 17046 17046 D StrictMode:    at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2856)
03-05 15:59:44.248 17046 17046 D StrictMode:    at android.app.ActivityThread.-wrap11(Unknown Source:0)
03-05 15:59:44.248 17046 17046 D StrictMode:    at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1589)
03-05 15:59:44.248 17046 17046 D StrictMode:    at android.os.Handler.dispatchMessage(Handler.java:106)
03-05 15:59:44.248 17046 17046 D StrictMode:    at android.os.Looper.loop(Looper.java:164)
03-05 15:59:44.248 17046 17046 D StrictMode:    at android.app.ActivityThread.main(ActivityThread.java:6494)
03-05 15:59:44.248 17046 17046 D StrictMode:    at java.lang.reflect.Method.invoke(Native Method)
03-05 15:59:44.248 17046 17046 D StrictMode:    at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:438)
03-05 15:59:44.248 17046 17046 D StrictMode:    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:807)

**Comment by chianger** [comment]
non user facing so P2.
