### ISSUE TITLE
Action bar icon positions are crowded on Z3C device 

### ISSUE THREAD

**Issue by carol-mozilla** [mozilla-mobile/FirefoxLite#1682]
![unnamed](https://user-images.githubusercontent.com/6700296/37943530-83fb100a-31aa-11e8-8a2b-416e208d1e12.png)

Device: Sony Z3C

--
If there's 5 icons on the action bar.  the screen is below 360dp (w),
please leave 20dp (w) on the left and right sides ; icons are distributed on the horizontal equally.

**Comment by mTwTm** [comment]
We don't have a label for 1.0 bugs: This is a 1.0 bug

**Comment by chianger** [comment]
1.x life cycle is going to end soon so probably we won't do the UI refinement.
