### ISSUE TITLE
A user should be able to add a valid website to Home screen when the network is unstable

### ISSUE THREAD

**Issue by cynthiatang** [mozilla-mobile/FirefoxLite#1704]
STR:
1. Launch Rocket
2. Visit any website
3. Disconnect the network
4. Reload page
5. Tap menu -> Tap Add to Home screen

Expected Result:
 - A user can add a valid website to Home screen when the network is unstable  

Actual Result:
 - User cannot add it to Home screen 
 - Video: https://drive.google.com/open?id=1RsGk_j-2UZKm8-lqRr4FyPBMp3tle8s6

Device: Pixel 2
Android: 8.0
Rocket: 1.0.4(3162).nightly
WebView: 65.0.3325.109

**Comment by chianger** [comment]
Or maybe we should show a toast message to notify what's going on.
