### ISSUE TITLE
Would be nice to open a site from home by the same tab, When adding a site to home screen, open the site from home(launcher) repeatedly will open to different tabs

### ISSUE THREAD

**Issue by cynthiatang** [mozilla-mobile/FirefoxLite#1705]
(Issued by Jack)

STR:
1. Launch Rocket
2. Tap any topsite
3. Tap menu
4. Tap Add to Home screen 
5. Tap ADD AUTOMATICALLY
6. Tap the shortcut that you just add to home screen

Actual Result:
 - Rocket will open it in the new tab

Expected Result:
 - Rocket will open it in the same tab (same as Fennec and Chrome)

Device: Pixel 2
Android: 8.0
Rocket: 1.0.4(3162).nightly
WebView: 65.0.3325.109

**Comment by chianger** [comment]
UX improvement. We should look at how people use "addtohomescreen" and "tabs" before judging what works better for users.
