### ISSUE TITLE
Add to home screen Twitter icon is not completely round

### ISSUE THREAD

**Issue by cynthiatang** [mozilla-mobile/FirefoxLite#1707]
(Issued by Joe)

Expected: 
 - Twitter icon is completely round (same as Chrome)

Actual result:
 - Twitter icon is not completely round
 - Video: https://drive.google.com/open?id=1xhryiWjnRwJHCq4yCIjro_vrNd5suM-E

Device: Sony Z3C
Android: 6.0
Rocket: 1.0.4(3132).nightly

**Comment by chianger** [comment]
Seems to be a UX/UI improvement.
