### ISSUE TITLE
Failed to login Pinterest with Facebook account

### ISSUE THREAD

**Issue by cynthiatang** [mozilla-mobile/FirefoxLite#1712]
(Issued by Joe)
Z3C, Android 6.0

STR:
1. Launch Rocket
2. Visit pinterest.com
3. Tap "Continue with Facebook"

Expected result:
 -  A user can continue with Facebook

Actual result:
 - Nothing happened.
 - The button "Continue with Facebook" doesn't work.

Device: Pixel 2
Android: 8.0
Rocket: 1.0.4(3162).nightly
WebView: 65.0.3325.109

**Comment by chianger** [comment]
webcompat issue on turbo mode.
