### ISSUE TITLE
Rocket will eventually get ANR error after you add more than 99 tab pages

### ISSUE THREAD

**Issue by cynthiatang** [mozilla-mobile/FirefoxLite#1715]
(Issued by Vance)

STR:
1. Launch Rocket
2. Add more than 99 tabs

Actual result:
 - get ANR error

Samgsung S7
Rocket 1.0.4(2383).nightly

**Comment by cynthiatang** [comment]
I just verified it. This issue cannot be reproduced in Pixel 2 with Rocket: 1.0.4(3132).nightly

**Comment by weslyhuang** [comment]
out of May 12. ENG need other work first.
