### ISSUE TITLE
When pressed 'back' on search, shouldn't we get out of search mode immediately instead of needing to click back twice?

### ISSUE THREAD

**Issue by cynthiatang** [mozilla-mobile/FirefoxLite#1718]
STR:
1. Launch Rocket 
2. Visit any website
3. Tap Url bar -------------> A user wants to search something
4. Tap system Back key  ---> A user doesn't want to search something 
5. Tap system Back key

Expected result:
 - After step4, there is no search field at the bottom of the screen 

Actual result
 - A user cannot get out of search mode immediately. He/She have to tap system Back key again.
 - Video: https://drive.google.com/open?id=1Xuh8a6c3X8sO_7_N8F7jw6UL1GCNYRbr

Device: Pixel 2
Android: 8.0
Rocket: 1.0.4(3162).nightly
WebView: 65.0.3325.109

**Comment by mTwTm** [comment]
We had a conversation about this behaviour somewhere (maybe in another, maybe not) when Rocket 1.0 was launching. Irrc the conclusion was this is the expected behaviour. (Some ref Apps have the same behaviour as current behaviour and some are behaving the same as you proposed.)

**Comment by mTwTm** [comment]
We can consule UX team's opinion again when triaging this.

**Comment by cynthiatang** [comment]
Agree. I know that current behavior is following the UX spec. For bug bash event, user experiences are important. Rocket team would get user's feedbacks from here. Let's wait for UX team's opinions. Thank you. :)

**Comment by chianger** [comment]
It was discussed long ago. I'm marking this as "Feature-P3" to keep record.
