### ISSUE TITLE
It shows an empty page and url in the beginning when visiting some websites in a NEW tab

### ISSUE THREAD

**Issue by cynthiatang** [mozilla-mobile/FirefoxLite#1730]
STR:
 1. Launch Rocket
 2. Visit http://goo.gl/e1tCB
 3. Tap any website link
 4. Repeat Step2 and Step3

Expected result:
 - URL should not be empty

Actual result: 
 - It shows an empty page and url In the beginning
 - Image: 
    <img src="https://user-images.githubusercontent.com/12458450/37819369-35fbd14a-2eb8-11e8-863a-49802c5c482d.png" width="360">

Reproduced rate: 5/5

Device: Pixel 2
Rocket nightly: 2.0.0(3180).night
Android version: 8.1.0
WebView version 65.0.3325.109

**Comment by weslyhuang** [comment]
Roger fixed it partially. (load url first)

**Comment by cnevinc** [comment]
Looks good on my pixel2
