### ISSUE TITLE
Video&Audio should be stop after switching to another tab (only Redmi Note4 )

### ISSUE THREAD

**Issue by cynthiatang** [mozilla-mobile/FirefoxLite#1735]
STR:
1. Launch Rocket 
2. Add some tabs
3. Visit youtube.com 
4. Play any video
5. Open the tab tray
6. Open another tab

Expected result:
 - The video should be stopped

Actual result: 
 - A user can hear the video
 - This issue cannot be reproduced in Pixel 2, Samsung J7 and Redmi 4A

Reproduce rate: 5/5

Device: Redmi Note4
Rocket nightly: 2.0.0 (3236). nightly
Android version: 7.0
WebView version 65.0.3325.109

**Comment by weslyhuang** [comment]
ref UCmini
