### ISSUE TITLE
No voice after tapping the play button in https://www.moedict.tw/

### ISSUE THREAD

**Issue by cynthiatang** [mozilla-mobile/FirefoxLite#1780]
STR:
 1. Launch Rocket
 2. Visit https://goo.gl/gNAm6R
 3. Tap the play button to listen to the explanation

Expected Result:
 - User can listen to the explanation (Chrome and Fennec work well)

Actual Result:
 - no voice
 - This issue can be reproduced in Focus and Lightning

Device Redmi Note 4
Rocket 2.0.0(3466).nightly
Webview: 66.0.3359
Android: 7.0

**Comment by weslyhuang** [comment]
same for my Pixel XL, not device specific.

**Comment by weslyhuang** [comment]
may further investigate the website implementation.
