### ISSUE TITLE
Failed to login to Bukalapak even thought user disabled Turbo mode

### ISSUE THREAD

**Issue by cynthiatang** [mozilla-mobile/FirefoxLite#1789]
STR:
 1. Launch Rocket
 2. Tap the topsite "Bukalapak"
 3. Tap menu -> Tap Login -> Tap Login Dengan Google
 4. Login to Bukalapak with your google account 

Expected Result:
 - User can login to Bukalapak

Actual Result:
 - Failed to login to Bukalapak
 - This issue CANNOT be reproduced in UC browser and Chrome
 - Video: https://drive.google.com/open?id=19z-XycA-Oh-8YvCCJhlTbYd4vKsbTe8L 
    
Device: Pixel 2
Rocket 2.0.0(3502).nightly
Webview: 66.0.3359.82
Android: 8.0

**Comment by cynthiatang** [comment]
This issue can be produced in Rocket 1.1

**Comment by weslyhuang** [comment]
Top site login issue so S1. P2 (not blocking open beta 2) since not a downgrade to user comparing with Rocket 1.x.
