### ISSUE TITLE
Facebook chat icon not shown on malline.id 

### ISSUE THREAD

**Issue by joechengla** [mozilla-mobile/FirefoxLite#1792]
On Sony Z3C & Samsung J7 Prime
Chrome Shows
Firefox Not Show
Rocket Not Show

On Pixel
Chrome Shows
Firefox Not Show
Rocket Shows

**Comment by carol-mozilla** [comment]
On Pixel
Rocket not show with turbo mode on.
/version 65

**Comment by weslyhuang** [comment]
Pixel XL with Rocket 2.0.0 (3502)

FB Chat icon: 
1. no show with turbo mode ON.
2. show with turbo mode OFF.

**Comment by joechengla** [comment]
it's trubo mode for me too :)
