### ISSUE TITLE
[Smoke Test] Vimeo stops to play video after flipping a few times

### ISSUE THREAD

**Issue by Conjuror** [mozilla-mobile/FirefoxLite#184]
STR:
1. Launch Zerda and go to Vimeo
2. Choose a video to play
3. Put DuT in landscape
4. Put DuT in portrait
5. Repeat Step 3&4 a few times
Expected Result:
5. Display in expected mode
Actual Result:
5. Video is stopped to play

DuT: Oppo A37

Build: 249

**Comment by Conjuror** [comment]
Should check focus as well.

**Comment by NashTung** [comment]
Work for me.
Video:
https://drive.google.com/open?id=1_ZYr-HDRcPccfwQNfhstTYvA8-TaEE2g

Device: Redmi 4A
Rocket: 2.0.0(4168).nightly
Android: 7.1.2
Android Webview: 66.0.3359.126
