### ISSUE TITLE
Remove "Add to Home" button and implement "real" bookmark feature

### ISSUE THREAD

**Issue by harly21** [mozilla-mobile/FirefoxLite#1846]
Bookmark feature has been requested from our users from both Google Playstore and Rocket user survey. We have tried using "add to home" as an alternative to bookmark, but that isn't what user need and hence we recieve comment like below:
"Thank you so much guys for the multiple tabs feature But we still need conventional bookmarks option because the homescreen shortcut is a bad and kinda stupid idea."

Also, we don't get a lot of people using the "add to home" function and therefore suggest to remove it and implement a basic bookmark feature

**Comment by chianger** [comment]
"add-to-home" and "bookmark" are supposedly different use cases.
move this to discuss in the feature grooming.
