### ISSUE TITLE
The search suggestion cannot be related to top site "kapanlagi"

### ISSUE THREAD

**Issue by NashTung** [mozilla-mobile/FirefoxLite#1865]
STR

1.  Install Rocket 2.0
2. Launch Rocket 2.0
3. Tap on search field
4. Input a text "ka" but not press enter
5. The search suggestion is "kaskus.co.id"
6. The search suggestion cannot be related to top site "kapanlagi"

https://drive.google.com/open?id=111u6gCXpyPAyFmfGHNf0M1NMibw9JlMt

Expected result:

- The search suggestion should be related to top site "kapanlagi"

Actual result:

- The search suggestion cannot be related to top site "kapanlagi"

Reproduce rate: 100%

Device: Redmi 4A
Rocket: 2.0.0(3585)
Android: 7.1.2
Webview: 65:0.3359.126

**Comment by mTwTm** [comment]
I think this one's is by design. domain autocomplete is based on site popularity but there are some more factors around top-site selection. However we might want a domain list revisit.

**Comment by chianger** [comment]
the behavior of domain autocomplete is by design. no intention to change it at this moment.

**Comment by mTwTm** [comment]
FWIW, this is the list we're using to generate domain autocomplete (and priority) https://github.com/mozilla-tw/Rocket/blob/master/app/src/main/assets/domains/id

**Comment by NashTung** [comment]
Add video, and the other top site will be related on search suggestion

**Comment by mTwTm** [comment]
For the 5 search suggestions, they are provided by search providers (probably Google) and by current design we're not changing the suggestions. From your description (kaskus) I think you're referring to the domain auto-completion. As listed in https://github.com/mozilla-tw/Rocket/blob/master/app/src/main/assets/domains/id kaskus is before kapanlagi. This list is most likely compiled from [Alexa top 50](https://www.alexa.com/topsites/countries/ID) We currently don't prioritize top-sites when we're doing autocomplete and from @joechengla comment yesterday offline I think this is aligned to his expectation.
