### ISSUE TITLE
Add more test content on SSL certificated website

### ISSUE THREAD

**Issue by NashTung** [mozilla-mobile/FirefoxLite#1868]
Payment on line (i.e. credit card) and check the transaction can be done completely

Shopping on website (Yahoo, PChome), need credit card information to complete the secured transaction between bank and website.

The browser will display all the content and complete the process correctly.

**Comment by chianger** [comment]
Looks to me it's more like a "task", rather than a "bug" top triage?
If it's true we shall remove NeedTriage label.

**Comment by cynthiatang** [comment]
It should be a new feature.

**Comment by chianger** [comment]
Yes, per offline discussion with Wesly, this is feature for better handling certificates.
The detailed spec is missing though.
