### ISSUE TITLE
The history cannot record immediately during visiting website

### ISSUE THREAD

**Issue by NashTung** [mozilla-mobile/FirefoxLite#1870]
STR

1. Install Rocket 2.0
2. Launch Rocket 2.0
3. Visit a website
4. The history cannot record immediately during visiting website on the following situation:
- Loading bar does not be process properly
- The website is just loading properly

https://drive.google.com/open?id=1vl4BRfU9XV1wjNoFEjSyLJJE9lPsr8Ti

Expected result:

- The history can record immediately during visiting website

Actual result:

- The history cannot record immediately during visiting website unless the website is loading properly for a while

Device: Redmi 4A
Rocket: 2.0.0(3585)
Android: 7.1.2
Webview: 65:0.3359.126

**Comment by mTwTm** [comment]
This is kinda expected by current design. We insert an item at onPageFinished(), but this is definitely a good chance to revisit this 👍

**Comment by chianger** [comment]
potentially a data loss issue. S1 P1 to discuss in sprint planning.

**Comment by NashTung** [comment]
Add video
