### ISSUE TITLE
A notification is shown on a device with older Google Play Service

### ISSUE THREAD

**Issue by mTwTm** [mozilla-mobile/FirefoxLite#1896]
![screenshot_20180504-155211](https://user-images.githubusercontent.com/6755074/39622308-43187dd8-4fc4-11e8-8d0c-2f6f0e0c3e42.png)

However we don't see other Apps using Firebase showing this.

**Comment by mTwTm** [comment]
When I downgrade from 15.0.2 (May 2, 2018) to 11.8.0 (December 18, 2017) I don't see that Notification any more. So it is very likely that those Apps I mentioned is not suffering this since they're still on an older version of Firebase?

**Comment by chianger** [comment]
expected behavior.
