### ISSUE TITLE
Apk currently selected variant is not signed. Please specify a signing configurations

### ISSUE THREAD

**Issue by ariefbayu** [mozilla-mobile/FirefoxLite#1906]
Hi Guys,

I want to test build and hopefully work on some issues. For started, what should I do to remedy this error?
I can hard-code the signing... But, I get the impression that that's not the recommended way.

![photo_2018-05-08_21-58-16](https://user-images.githubusercontent.com/55084/39765035-1b5d029c-530b-11e8-8ba3-12da06fb4486.jpg)

**Comment by mTwTm** [comment]
Hi ariefbayu! In the Build Variants tab in the lower left of Android Studio, switch from focusWebkitBeta to focusWebkitDebug would let you build the debug version which is the one we use for daily developments. beta is for other purposes.

When you have changed to focusWebkitDebug, you might run into a temporary issue that we're currently trying to fix. See #1913 for a workaround.
