### ISSUE TITLE
The "Share Firefox Rocket Nightly with friends!" dialog shows up after dismissing the "Love Firefox Rocket Nightly?" notification

### ISSUE THREAD

**Issue by NashTung** [mozilla-mobile/FirefoxLite#1907]
STR

1. Install Rocket 2.0 Nightly
2. Launch Rocket 2.0 Nightly for 6th time
3. Show "Love Firefox Rocket Nightly?" dialog 
4. Dismiss the dialog
5. Launch Rocket Nightly for 6th times
6. Show "Love Firefox Rocket Nightly?" notification
7. Tap Love Firefox Rocket Nightly on the message
8. Dismiss the message
9. Launch Rocket Nightly for 4th times
10. Show "Share Firefox Rocket Nightly with friends!" dialog 

https://drive.google.com/open?id=1JOEhhoVRKEzeH9waJ7wgI1lSp6VNIAFZ

Expected result:

- The "Share Firefox Rocket Nightly with friends!" dialog does not show up

Actual result:

- The "Share Firefox Rocket Nightly with friends!" dialog show up

Reproduce rate: 100%

Device: Redmi 4A
Rocket: 2.0.0(4045). nightly
Android: 7.1.2
Webview: 66.0.3359.126

**Comment by chianger** [comment]
S2. more like UX improvement.

**Comment by cynthiatang** [comment]
<img width="907" alt="screen shot 2018-05-24 at 2 36 13" src="https://user-images.githubusercontent.com/12458450/40472676-bae42922-5f6c-11e8-8cd5-80c7d395ee93.png">

**Comment by mlwang32** [comment]
Similar behavior observed on Samsung Galaxy J7 (Android 7).

Screenshot:
![screenshot_20180816_sharefriend](https://user-images.githubusercontent.com/746727/44160690-c2299b00-a0ed-11e8-88aa-560eeef9bac0.png)
