### ISSUE TITLE
Pin website/top site to Rocket's home page

### ISSUE THREAD

**Issue by Jacklin-ux** [mozilla-mobile/FirefoxLite#1908]

**Comment by Jacklin-ux** [comment]
The draft spec: https://drive.google.com/file/d/1Nyr_yTwREq7py3hWFVbjRlOqoBNQPjJt/view?usp=sharing

**Comment by carol-mozilla** [comment]
Visual spec and assets: https://drive.google.com/open?id=1SU47xMvurwdVlul943ToIKT3N_AYPkc_

**Comment by mTwTm** [comment]
Remove UXVD Wanted tag since it's moved to ready for development already.

**Comment by weslyhuang** [comment]
purpose covered by bookmark somehow thus removed from TOP#20. (Ready for Development)
