### ISSUE TITLE
Faile to stop playing the video after tapping '+'

### ISSUE THREAD

**Issue by cynthiatang** [mozilla-mobile/FirefoxLite#1915]
STR:
 1. Launch Rocket 
 2. Visit youtube.com
 3. Tap a video 
 4. Tap '+'
 5. Visit any website

Expected result:
 - Stop playing the video

Actual result: 
 - Faile to stop playing the video 
 - Video: https://drive.google.com/open?id=12Rb97ovuJ3kXiX6E_4TSydd-I_57opkj

Reproduced rate: 2/5

Device: Pixel 2
Rocket: 2.0.0(3585) 
Android version: 8.1.0 
WebView version 66.0.3359.158

**Comment by walkingice** [comment]
from step 3 to step 4, it should be as quick as possible to hide tab
