### ISSUE TITLE
User Feedback: Able to translate webpage

### ISSUE THREAD

**Issue by harly21** [mozilla-mobile/FirefoxLite#1917]
User feedback on Google Play:  If there is an automatic translation feature. Definitely 100 stars jg I love

**Comment by joechengla** [comment]
dup with https://github.com/mozilla-tw/Rocket/issues/1438. let's keep track using this new one

**Comment by joechengla** [comment]
new tech available https://firebase.google.com/docs/ml-kit/android/translate-text
