### ISSUE TITLE
Users can view/edit/share after capturing full page screenshot 

### ISSUE THREAD

**Issue by Jacklin-ux** [mozilla-mobile/FirefoxLite#1936]

**Comment by chianger** [comment]
during 2.2 sprint planning we decided to tentatively take this.
meaning that we'll allocate resource to build it, but then depends on UX audit to determine whether to ship in 2.2.

**Comment by joechengla** [comment]
let's do a Firebase experiment on this with standard one-action snackbar 
e.g. 4 groups, each with different option (open or edit or share or no snackbar) to understand which has more traction and the performance of user engagement on screenshot (or even user retention) across the 4 groups

**Comment by joechengla** [comment]
My current thought is a snack bar that says screenshot saved and with 5 scenarios
1. No action
2. View 
3. Share 
4. Edit 
5. Delete
