### ISSUE TITLE
Refine FirebaseEventTest

### ISSUE THREAD

**Issue by cnevinc** [mozilla-mobile/FirefoxLite#1943]
Mock AppConstants.isReleaseBuild()  to always return false so in app:testFocusWebkitReleaseUnitTest  it'll pass.
I though Unit Tests only runs on debug build type. just like Espresso. Also need to find out why.

**Comment by mTwTm** [comment]
Sounds like a plan. In the meanwhile, I think all buildvariants have their test task, just like assemble.

**Comment by weslyhuang** [comment]
per status check, this one might be the only risky item for 2.3. (considering to leverage external partner's effort on it).
