### ISSUE TITLE
Failed to open a notification with link in a new tab immediately when playing a video in full-screen mode

### ISSUE THREAD

**Issue by cynthiatang** [mozilla-mobile/FirefoxLite#1958]
STR:
1. Launch Rocket 
2. Go to youtube.com and play a video in full-screen mode
3. Receive a notification with a link from Firebase 
4. Tap the notification  

Expected result:
 - Open the link in a new tab immediately 
 - Chrome: https://drive.google.com/open?id=1l3kM5QF08bG_1VcWnscgzu4hqruW1GpO 

Actual result: 
 - Stay in full-screen mode. Failed to open the link in a new tab immediately
 - Video: https://drive.google.com/open?id=1SPQS_jTyPOra6wG14pK8aLKVD16m-CcD 

Reproduced rate: 3/3

Device: Nexus 5
Rocket: 2.0.0(4396).night 
Android version: 6.0.1
Webview: 66.0.3359.158

**Comment by mTwTm** [comment]
My two cents here:
1. The link is opened with Rocket in the Chrome video.
2. For the rocket video, link is opened but we're still in full screen mode so the new tab is not brought to foreground.
