### ISSUE TITLE
The position of remove item is more lower on 3rd, 4th, 7th and 8th top site

### ISSUE THREAD

**Issue by NashTung** [mozilla-mobile/FirefoxLite#1978]
STR

1. Install Rocket 2.0
2. Launch Rocket 2.0
3. Long press on 3rd, 4th, 7th and 8th top site (The order from 1st to 8th top site is left to right, upper and lower)
4. The position of remove item is more lower

Video: https://drive.google.com/open?id=1CbUo-yELxcQG-OuRTOLZ8jyICdNG4Qul

Expected result:

- The position of remove item is same on all top site

Actual result:

- The position of remove item is different on all top site

Reproduce rate: 100%

Device: Advan i5C
Rocket: 2.1.0(4414)
Android: 5.1
Android Webview: 67.0.3369.49

**Comment by cynthiatang** [comment]
This issue **cannot** be reproduced in Pixel2 and Redmi 4A

This issue can be reproduced in Sony Z3C and OPPO A37f

**Comment by chianger** [comment]
minor visual impact.
