### ISSUE TITLE
The numbers of shortcut is limited to one on system home （maybe Advan only）

### ISSUE THREAD

**Issue by NashTung** [mozilla-mobile/FirefoxLite#1980]
STR

1. Install Rocket 2.0
2. Launch Rocket 2.0
3. Visit any website 
4. Add a shortcut on System home successfully
5. Visit other website
6. Add a shortcut on System home
7. The numbers of shortcut is limited to one on system home 

Video: https://drive.google.com/open?id=1IWa06WvZ0HTdbHGgg-5leqDzBQOZ3Jpk

Expected result:

- The numbers of shortcut cannot be limited

Actual result:

-  The numbers of shortcut is limited to one on system home 

Reproduce rate: 100%

Device: Advan i5C
Rocket: 2.1.0(4414)
Android: 5.1
Android Webview: 67.0.3369.49

**Comment by cynthiatang** [comment]
This issue cannot be reproduced in OPPO (Android 5.1.1) with WebView 66.x and 67.x

https://drive.google.com/open?id=1ILzFGErptMW8jyMhiHBdmyL-0Xq4uZu4

WebView:67.0.3396.49
Rocket 2.1.0(4414)
Device: Oppo A37f
Android: 5.1.1

Webview: 66.0.3359.158
Rocket 2.1.0(4414)
Device: Oppo A37f
Android: 5.1.1

**Comment by NashTung** [comment]
1. This issue can be reproduced on Webview 66.0.3359.158

2. This issue cannot be reproduced on Chrome
Video: https://drive.google.com/open?id=1Dtd7JnX3ge3QUNNCQNoyOoIqgNl_VLhV

3.  This issue cannot be reproduced on Redmi4a
Video: https://drive.google.com/open?id=1gG7EiMpFfwA84gVzzTvblTX5POda37-D

Device: Redmi 4A
Rocket: 2.1.0(4414)
Android: 7.1.2
Android Webview: 66.0.3359.158

**Comment by chianger** [comment]
QAWanted to check UC browser, Opera on this same Advan device.

**Comment by chianger** [comment]
+ firefox for android too.

**Comment by NashTung** [comment]
1. This issue cannot be reproduced on UC Browser (12.5.0.1109)
Video: https://drive.google.com/open?id=1bsQJotediOQ4VD8XFDc5xklXTaMvEswx

2. This issue can be reproduced on the following browser:
a. Opera Mini (33.0.2254.125672), cannot add any shortcut
Video: https://drive.google.com/open?id=1Bfm6XV774f94XhYGuLSO9DjVn3Ny2opp

b. Firefox (60.0.1)
Video:  https://drive.google.com/open?id=1t4JNSFG0daZYsVyBiEKw_hcCC7cnSdHc
