### ISSUE TITLE
Would be nice to inconsistent behavior between "history panel" and "tab list"

### ISSUE THREAD

**Issue by cynthiatang** [mozilla-mobile/FirefoxLite#2016]
(Issued by Wesley)

Test Case1:
1. Launch Rocket with some histories
2. Go Menu -> History
3. Tap any history and swipe right/left

Test Case2:
1. Launch Rocket with some histories
2. Go Menu -> History
3. Make the history panel at the half-opened status.
4. Tapping on the upper non-panel area 

Expected result:
 - Test case1: The history panel has swipe to close
 - Test case2: It will be full-screen view after tapping on the upper non-panel area

Actual result:
 - Test case1: The history panel doesn't have swipe to close
 - Test case2: It will close the history list after tapping on the upper non-panel area
 - Video: https://drive.google.com/open?id=1eNzOKQgdYSC7NH6vMkZ4GSn9llpKDyRy

Device: Redmi 4X 
Android: 7.1.2
Rocket: 2.1.1(4639).nightly
WebView: 66.0.3359.158

**Comment by chianger** [comment]
Usability improvement: s2
