### ISSUE TITLE
Unable to share a link to zerda

### ISSUE THREAD

**Issue by Conjuror** [mozilla-mobile/FirefoxLite#202]
as title. We should be able to receive links from other apps.

STR:

1. Launch Chrome/Firefox/UC Browser/whatever apps
2. Go to a page and select share

Expected Result:

2. Zerda should be on the list for sharing

Actual Result:

2. No Zerda on the list.

**Comment by mTwTm** [comment]
I think we should not accept share intents, open intents should be enough.

**Comment by NashTung** [comment]
This issue can be reproduced and the root cause as Teng-pao Yu mention it.

Video: (i.e. Chrome)
https://drive.google.com/open?id=1tzFNY1nfgVS5XxWXhaAvDm88UUTfYEt6

Device: Redmi 4A
Rocket: 2.0.0(4168).nightly
Android: 7.1.2
Android Webview: 66.0.3359.126
