### ISSUE TITLE
Cannot display some JSFiddle website correctly

### ISSUE THREAD

**Issue by Conjuror** [mozilla-mobile/FirefoxLite#203]
For an example, http://jsfiddle.net/jonathansampson/3gamh26o 

In Chrome, it can display completely and correctly.

Focus and display the page correctly but is zoom-in too much and cannot adjust.
UC Browser is the same as focus.

UC mini is totaly busted.

Opera mini is the same as Zerda is.

Suggest to put this in P2 and come back to it if we have enough time to study.

**Comment by NashTung** [comment]
This issue can be reproduced.
Video:
https://drive.google.com/open?id=1ih2dw-Xm_66LbHoHdrn6ZldlLU1PQXKl

Device: Redmi 4A
Rocket: 2.0.0(4168).nightly
Android: 7.1.2
Android Webview: 66.0.3359.126
