### ISSUE TITLE
The link on 3rd app does not launch Rocket app automatically after enabling make default browser

### ISSUE THREAD

**Issue by NashTung** [mozilla-mobile/FirefoxLite#2031]
STR

1. Install Rocket 2.1.1
2. Launch Rocket 2.1.1
3. Tab "Make default browser" on settings
4. Tab any link on 3rd app (Gmail)
5. The link does not open Rocket app directly

Video: https://drive.google.com/open?id=1oQCniCJJA7tctn11zDT4voD6mZXufrX1

Expected result: 

- The link will open Rocket app directly (since Rocket is set as default browser)

Actual result:

- The link does NOT open Rocket app directly

Reproduce rate: 100%

Device: Advan i5C
Rocket: 2.1.1(4587)
Android: 5.1
Android Webview: 67.0.3369.49

**Comment by cynthiatang** [comment]
Hi @NashTung , could you please use another 3rd app to verify it? For example, Keep. Thanks!

**Comment by chianger** [comment]
QAWanted to see if it's Gmail's tailormade behavior. Maybe try Gmail with other browser set as default.

**Comment by NashTung** [comment]
Hi Cynthia, the issue does not be reproduced in Google Note app.
Video: https://drive.google.com/open?id=1GR6HTD9rvwtKZKy_qx7aUGgDbfSUYpEX

Device: Advan i5C
Rocket: 2.1.1(4639).nightly
Android: 5.1
Android Webview: 67.0.3369.49

**Comment by chianger** [comment]
If this can only be reproduced on one single device, treat it as P2.
