### ISSUE TITLE
GeckoView wish list (draft)

### ISSUE THREAD

**Issue by cnevinc** [mozilla-mobile/FirefoxLite#2063]
Here's the wish list of features GeckoView can benefit Rocket:
1. Private Browsing
2. Better PWA support
3. Reader Mode (maybe?)
4. A-Frame/Gaming support 
5. AutoFill 
6. Network bandwidth monitoring and statistic ( how many data is used)
7. Data saving ( lower resolution image) and statistic
8. Debugging tool for web app developers

**Comment by walkingice** [comment]
* Better screenshot support

**Comment by mTwTm** [comment]
Let's label all features that we can benefit from GeckoView from now on.
