### ISSUE TITLE
Reader mode powered by Pocket

### ISSUE THREAD

**Issue by joechengla** [mozilla-mobile/FirefoxLite#2065]

**Comment by chianger** [comment]
is #1973 a dup of this?

**Comment by chianger** [comment]
previous design proposal is at  https://drive.google.com/file/d/1t1mqUxrC3gnqCIrKXbDjgamw-BtwgXrN/view?usp=sharing

**Comment by elin-moco** [comment]
I found that pocket have their own cache for reader mode.
If we are able to use that page cache, we will be able to claim "fast and data-saving".
Which might benefit acquisition.
