### ISSUE TITLE
Weird animation after editing bookmark

### ISSUE THREAD

**Issue by cynthiatang** [mozilla-mobile/FirefoxLite#2124]
(Issued by Teng-Pao)

1. Launch Rocket
2. Visit a webpage
3. Bookmark the current webpage
4. Tap EDIT

Actual Result: 
 - Weird animation after editting bookmark
 - https://drive.google.com/open?id=1HdDYfLcajg6Crroxre8c0EwrwoCQfKGr

Expected Result:
 - Wait for UX to check

Device: Pixel 2
Android 8.1.0
Rocket 2.2.0(5257).nightly
WebView 68.0.3440.40

**Comment by Jacklin-ux** [comment]
The animation from open edit page and finish editing in my Pixel2 looks good. I am not sure why the animation in your device looks weired?

**Comment by cynthiatang** [comment]
Here is the video for Nexus5 (Android 5.1.1)
https://drive.google.com/open?id=1kjLlb5yJzrugFlobzPItIrDUL2_Nhou7

**Comment by chianger** [comment]
QAWanted to see if this is reproducible.

**Comment by chianger** [comment]
not so obvious visual impact
