### ISSUE TITLE
Failed to play a video about "Learn more about Flipkart delivery and installation process" (Top 9 in India)

### ISSUE THREAD

**Issue by cynthiatang** [mozilla-mobile/FirefoxLite#2141]
STR
1. Launch Rocket
2. Visit goo.gl/Rga2LD
3. Scroll down 
4. Tap the video about "Learn more about Flipkart delivery and installation process"

Expected Result:
 - Play the video
 - Chrome works well 
 - https://drive.google.com/open?id=18XXMXooNeMitw09VstVPkFehw5_eckrN

Actual Result:
 - Failed to play the video
 - This issue can be reproduced in Rocket, Focus, Lightning
 - https://drive.google.com/open?id=1gzpqESj2mWbus5ssu0kF0cjXH4heTp0S

Pixel2
Android 8.1.0
Rocket 2.3.0(5330).nightly
WebView 68.0.3440.40

**Comment by chianger** [comment]
can you try Fennec to play the video, and see if there's indication of mixed content.

**Comment by cynthiatang** [comment]
I can use Fennec to play the video.

**Comment by chianger** [comment]
QAWanted to verify if this is actually due to mixed content.

**Comment by cynthiatang** [comment]
<img width="1241" alt="screen shot 2018-08-28 at 11 32 25" src="https://user-images.githubusercontent.com/12458450/44699363-6d572e80-aab6-11e8-90bb-1ec40658ac2b.png">

**Comment by cynthiatang** [comment]
This page is not a mixed-content page. @mTwTm said that there must be a yellow icon if the webpage is mexed-content page. for example 

<img width="929" alt="screen shot 2018-10-02 at 9 36 10" src="https://user-images.githubusercontent.com/12458450/46324575-b276ff00-c626-11e8-8eea-814b2bc33e4a.png">

**Comment by chianger** [comment]
S2: it's a 2nd/3rd level functionality in this use case
