### ISSUE TITLE
Failed to display 2 languages in settings (Lenovo A1000 only)

### ISSUE THREAD

**Issue by cynthiatang** [mozilla-mobile/FirefoxLite#2202]
STR:
 1. Go to Menu -> Settings -> Language

Actual result:
 - XXXXX (XXXX)
 - XXXXXX (XXXX)
    ![screenshot_2018-07-20-16-14-44](https://user-images.githubusercontent.com/12458450/42991877-88afabc6-8c39-11e8-9d2b-29d448a05497.png)

Lenovo A1000 
Android 5.1
Rocket 2.3.0(5661).nightly
WebView 67.0.3396.87

**Comment by mTwTm** [comment]
Possible solution shared by Max: https://stackoverflow.com/questions/29936070/how-to-detect-which-language-fonts-are-supported-by-device

**Comment by chianger** [comment]
P2 as current shipped locales are all good.
