### ISSUE TITLE
Inconsistent display - the string "download" (OPPO A37f only)

### ISSUE THREAD

**Issue by cynthiatang** [mozilla-mobile/FirefoxLite#2204]
Please see the picture. 

                Pixel 2                                           Oppo A37f 
<img width="897" alt="screen shot 2018-07-20 at 4 55 07" src="https://user-images.githubusercontent.com/12458450/42993751-c5029d7c-8c3e-11e8-9366-20d7aaa389b9.png">

Rocket 2.3.0(5661).nightly
WebView 67.0.3396.87

**Comment by chianger** [comment]
looks like this is Thai. Calling out to Thai speakers for feedback.

**Comment by veer66** [comment]
@chianger  Yes, it is terrible.

**Comment by chianger** [comment]
@veer66 what's the recommended solution for this case? Do you consider replace it with a shorter string? Also I'm curious how terrible this is. Does any of this show totally incorrect message?

**Comment by veer66** [comment]
@chianger 


1. Pixel 2'one on the left is acceptable.  It is like:

```
Download
ing
```

2. Oppo A37f's one is like:

```
Downlo
ading
```

**Comment by chianger** [comment]
S2: enhancment

**Comment by chianger** [comment]
It's tricky itself since the string is long. Do you happen to know how other applications (in Thai language) work around this? @veer66

**Comment by veer66** [comment]
@chianger Many years ago, some people used to put a zero-width space on the web for guiding word segmentation. However, I'm afraid that will cause more problems, by fixing one specific problem on only Oppo A37f.
