### ISSUE TITLE
Search suggestion is overlapped with system status bar

### ISSUE THREAD

**Issue by Conjuror** [mozilla-mobile/FirefoxLite#223]
Build 303

For an example, search suggestion for "google map" will overlap with system status bar.

**Comment by chianger** [comment]
UI polish so let's P2 this.

**Comment by mTwTm** [comment]
Unassign myself cause I'm not going to handle this in the near future.

**Comment by NashTung** [comment]
Work for me.
Video:
https://drive.google.com/open?id=1FFPA1h19hadsikoQElysJhNTQMZam3K6

Device: Redmi 4A
Rocket: 2.0.0(4168).nightly
Android: 7.1.2
Android Webview: 66.0.3359.126

**Comment by mTwTm** [comment]
Could be that the search suggestion for google map is shorter now. I can reproduce this with searching "abcdefghijklmnopqrstuvwxyzabcd" for now.
