### ISSUE TITLE
No any permission requests in private mode 

### ISSUE THREAD

**Issue by cynthiatang** [mozilla-mobile/FirefoxLite#2241]
1. Reinstall Rocket
2. Visit cnn.com in the Normal mode
3. Switch to private mode
4. Visit cnn.com
5. Long press an image 
6. Tap Save image  
7. Switch to Normal mode 
8. Repeat step4 to step6

Actual result:
 - After step 6, there is no System Storage Permission request in private mode. The image is saved. 
 - After step 8, it shows the System Storage Permission request in normal mode. the image is not saved before getting the permission
- Video: https://drive.google.com/open?id=125vYLOBxAiZFCThlvm8bYNH2wsSE_Pif

Expected result:
 - After step 6, the image should not be saved before getting the permission

Reproduce rate: 10/10

Redmi Note4 with Android 7.0
Rocket 2.4.0(5760).nightly
WebView 67.0.3396.87

Pixel 2 with Android 8.1.0
Rocket 2.4.0(5760).nightly
WebView 68.0.3440.40

**Comment by cynthiatang** [comment]
Here is the test result for Location permission

STR:
1. Reinstall Rocket
2. Switch to Private mode
3. Visit https://permission.site 
4. Tap Location
5. Switch to Normal mode
6. Visit https://permission.site
7. Tap Location

Actual result:
 - No system dialog for Location permission after step 4. Location button is yellow. 
 - Show a system dialog for Location permission after step 7
 - Video: https://drive.google.com/open?id=1F6ekJrAj35DXrakJK9Bc_F60tvhYb8DY

Expected result:
 -  Show a system dialog for Location permission after step 4

Reproduce Rate: 10/10

Pixel 2 with Android 8.1.0
Rocket 2.4.0(5760).nightly
WebView 68.0.3440.40

**Comment by chianger** [comment]
Per discussion, for first shipping it can be reject every permission by default. 
Further permission handling can be tracked as feature.

**Comment by chianger** [comment]
another clarification: file download is through download manager so it's not relevant to any permission given to Rocket.
