### ISSUE TITLE
Re-entering Rocket will be at Tab View (if previous state was in Prviate Browsing mode)

### ISSUE THREAD

**Issue by joechengla** [mozilla-mobile/FirefoxLite#2246]
Steps
1. Goto private browsing 
2. Press system HOME key
3. Go back to Rocket by tapping Rocket app icon
4. I will be at the Tab View instead of the Private Window

**Comment by joechengla** [comment]
Chrome
1. Goto private browsing and start browsing
2. Press system HOME key
3. Go back to Chrome by tapping Chrome app icon
4. I will be back at the Private Window

Fennne 
1. Goto private browsing and start browsing
2. Press system HOME key
3. Go back to Fennec by tapping Fennec app icon
4. I will be back at the Private Window

Rocket
1. Goto private browsing and start browsing
2. Press system HOME key
3. Go back to Rocket by tapping Rocket app icon
**4. I will be at the Tab View instead of the Private Window**

**Comment by chianger** [comment]
note: this item takes fairly big engineering effort.

**Comment by mTwTm** [comment]
It's PITA to do both private browsing and normal browsing with Webview. Could be something we can benefit from GeckoView.
