### ISSUE TITLE
Show an error page: The address wasn't understood after tapping Street View in the search result (Private browsing mode only)

### ISSUE THREAD

**Issue by cynthiatang** [mozilla-mobile/FirefoxLite#2251]
1. Launch Rocket
2. Switch Private browsing mode
3. Visit google.com
4. Enter "101" in Google's search filed
5. Tap "Street View" 

Actual result:
 - Show an error page: The address wasn't understood
 - Video: https://drive.google.com/open?id=1u2IMNSTAISH1LUOhbvmgPd8L--rrAsxJ

The result in the Normal browsing mode
 - Launch the app "Google map"

Pixel2
Android 8.1.0
Rocket 2.4.0 (5760).nightly
Webview 68.0.3440.40

**Comment by chianger** [comment]
priority decision pending.
