### ISSUE TITLE
Show an error page: The address wasn't understood after tapping Firefox for Android in mozilla.org page (Private browsing mode only)

### ISSUE THREAD

**Issue by cynthiatang** [mozilla-mobile/FirefoxLite#2258]
1. Launch Rocket
2. Switch to private browsing mode 
3. Visit mozilla.org
4. Tap Firefox for Android 

Actual result
 - Show the error page
    <img src="https://user-images.githubusercontent.com/12458450/43152198-8643b750-8fa0-11e8-9b9c-8880d46c2228.png" width="50%" height="50%">

Expected result:
 - Launch Play Store for downloading Firefox (the result in the Normal mode)

Only support domain suggestion
It should not provide search suggestions to users
Reproduce Rate: 10/10

Redmi Note4 with Android 7.0
Rocket 2.4.0(5760).nightly
WebView 67.0.3396.87

**Comment by chianger** [comment]
in normal mode the app link successfully redirect user to GP.
