### ISSUE TITLE
Cannot change the language immediately (private mode)  

### ISSUE THREAD

**Issue by cynthiatang** [mozilla-mobile/FirefoxLite#2261]
1. Reinstall Rocket
2. Launch Rocket
3. Go to Menu -> Settings -> Language -> Thai
4. Go to Home and check the search bar in the Normal browsing mode
5. Go to Home and check the search bar in the Private browsing mode
6. Go to Menu -> Settings -> Language -> English
7. Go to Home and check the search bar in the Normal browsing mode again
8. Go to Home and check the search bar in the Private browsing mode again

Actual result:
 - After step 5: show the string "Search or enter address" in Thai
 - After step 8: show the string "Search or enter address" in Thai
 - Video: https://drive.google.com/open?id=1qEW5xj5hBGjby8Yxf09j1L4CVt-fmWbk

Expected result:
 - After step 5: show the string "Search or enter address" in Thai
 - After step 8: show the string "Search or enter address" in English
 
Reproduce Rate: 10/10

Sony Z3C
Android 6.0.1
Rocket 2.4.0(5760).nightly
WebView 67.0.3396.87

**Comment by chianger** [comment]
Visual impact to be improved.
