### ISSUE TITLE
Revisiting a dialog after swtiching the locale would display wrong content

### ISSUE THREAD

**Issue by cynthiatang** [mozilla-mobile/FirefoxLite#2276]
Android System Language is English

STR
 1. Re-install Rocket
 2. Launch Rocket
 3. Go to Menu -> Settings -> Language -> Thai
 4. Go to Menu -> Settings -> Tap "Give feedback"
 5. Go to Menu -> Settings -> Disable "Send usage data" -> Tap "Give feedback"

Actual result:
 - Video: https://drive.google.com/open?id=1dnHDtNZW5_36ayUKkGHKXUdNRVRvYCFM

<img width="891" alt="screen shot 2018-07-25 at 10 12 01" src="https://user-images.githubusercontent.com/12458450/43247604-c571a228-90e7-11e8-840a-fe292af39bbc.png">

Expected result:
 - Show all strings in Thai

Reproduce rate: 10/10

All devices

**Comment by mTwTm** [comment]
Several factors are in the play here:
1. Firebase is turned off and goes to default when Give feedback is turned off.
2. Dialogs are not Locale-switcher aware (for now). So the English strings is already inflated when you first open the "We Love Feedback" part.
So this happens every time when one uses the switcher and clear a dialog before she switches. The second time she visit the dialog, it would have cached  content in a different locale.

**Comment by chianger** [comment]
QAWanted to see if re-launch the app user can see expected consistent dialog.

**Comment by cynthiatang** [comment]
It still shows the string in English after relaunch Rocket

https://drive.google.com/open?id=1koFsBbh3dhVDPnwqxx2CGmMilvINy5e-

Nexus5 
Android 5.1.0
Rocket 3.0.0(5988).nightly
WebView 67.0.3396.87

**Comment by chianger** [comment]
Enhancement: S2

**Comment by elin-moco** [comment]
Changing system language also won't change the feedback dialog text.
Only reinstall after changing language will get us updated string.

**Comment by cnevinc** [comment]
Firebase init happens in ContentProvider and before Activity starts, so the locale may not be used( need confirm)

**Comment by cynthiatang** [comment]
Hi @cnevinc ,
I verified it in Pixel 2 with Rocket 3.0.0(6232).
After step 5, if the user launches the app again, the title and description would be correct. ( "Love Firefox Rocket Nightly" is translated)

Video: https://drive.google.com/open?id=1qXjzqbE8paW5Wu5nVgrxdhUs8mdSKWD1

Pixel2
Android 8.1.0
Rocket 3.0.0(6232)
WebView 68.0.3440.91
