### ISSUE TITLE
No preview for screenshot

### ISSUE THREAD

**Issue by ghost** [mozilla-mobile/FirefoxLite#2286]
I took screenshot and it doesn't appearing.
Firefox Rocket 2.4.0(5887).nightly
Webview version - 59.0.3071.125
![photo6257762235422189692](https://user-images.githubusercontent.com/9081004/43357356-cdb03de6-9245-11e8-8714-1500f6dcd205.jpg)
![photo6257762235422189693](https://user-images.githubusercontent.com/9081004/43357357-cdddba14-9245-11e8-97a4-086f6cfbbf27.jpg)

cc @delphine

**Comment by joechengla** [comment]
maybe updating the webview will help?
https://support.mozilla.org/en-US/kb/screenshots-problem-firefox-rocket

**Comment by chianger** [comment]
No action from us at this moment since 59 is not in our testing scope
