### ISSUE TITLE
PH Top Site: Lazada gets hijacked by Lazada app

### ISSUE THREAD

**Issue by joechengla** [mozilla-mobile/FirefoxLite#2314]
on Huawei Nova 2i device

**Comment by cnevinc** [comment]
Something need to be fixed here
https://github.com/mozilla-tw/Rocket/blob/8c6161f0a17ad3a84224aedf1b58cdfdf8dfa6eb/app/src/webkit/java/org/mozilla/focus/webkit/FocusWebViewClient.java#L114
