### ISSUE TITLE
Cannot display images from ruten.com.tw

### ISSUE THREAD

**Issue by Conjuror** [mozilla-mobile/FirefoxLite#232]
Build 303
DuT: Pixel

STR:
1. Launch zerda
2. visit "www.ruten.com.tw"
3. Search for goods "switch"

Expected Result:
3. images are shown as goods' thumbnails

Actual Result:
3. Missing thumbnails

Also, confirmed that both Fennec and Focus can display thumbnails correctly.

**Comment by Conjuror** [comment]
All web compat are tracked with #342. Since it's not Top 100 ID sites, keep it alive and track separately.

**Comment by idiotmax** [comment]
Page in httpS but image not in httpS. Security concern, possible WontFix.


I/chromium: [INFO:CONSOLE(0)] "Mixed Content: The page at 'https://m.ruten.com.tw/' was loaded over HTTPS, but requested an insecure image 'http://e.rimg.com.tw/ahd/goods-ad-09_0828ok_1503558528.jpg'. This request has been blocked; the content must be served over HTTPS.", source: https://m.ruten.com.tw/ (0)

**Comment by idiotmax** [comment]
Possible workaround,
if (Build.VERSION.SDK_INT >= 21) {
        webview.getSettings().setMixedContentMode( WebSettings.MIXED_CONTENT_ALWAYS_ALLOW );
}

**Comment by Conjuror** [comment]
According to above messages, put back to triage and revisit it in Triage meetings.

**Comment by Conjuror** [comment]
[WebCompat] If there's no similiar issues on ID Top 100 sites, keep it as it is now.

**Comment by NashTung** [comment]
This issue can be reproduced.
Video:
https://drive.google.com/open?id=1MsImr9sqlNmSPCnxTVwpGT1Axu4YfJBe

Device: Redmi 4A
Rocket: 2.0.0(4168).nightly
Android: 7.1.2
Android Webview: 66.0.3359.126
