### ISSUE TITLE
would be nice to show JOIN NOW and the first banner at the same time

### ISSUE THREAD

**Issue by cynthiatang** [mozilla-mobile/FirefoxLite#2366]
1. Install Rocket 
2. Launch Rocket
3. Skip onboarding page
4. Check the first banner
5. Swipe left the first banner
6. Check the first banner

Expected Result
 - For the step4,  it would be nice to show JOIN NOW and the first banner at the same time
 - For the step6,  it would be nice to show 4 websites and the second banner at the same time

Actual Result
 - For the step4,  it doesn't show JOIN NOW and the first banner at the same time
 - For the step6,  it doesn't  show 4 websites and the second banner at the same time
 - Video: https://drive.google.com/open?id=1HhrYR1ifxBT9iYWCsAsWRd7C3jELyeGU

Reproduce Rate 10/10

All devices
Rocket 3.0.0(6084).nightly
WebView 68.0.3440.70

**Comment by chianger** [comment]
triage: nonblocking.
display a background placeholder to improve.

**Comment by chianger** [comment]
UX wanted to define the placeholder.
