### ISSUE TITLE
Deleting image from download page results in broken image

### ISSUE THREAD

**Issue by dakaizou** [mozilla-mobile/FirefoxLite#237]
STR:
1. Download an image
2. Push the menu button
3. Push the Download button
4. Push the more button
5. Push Delete file
6. Check the image

Build: 303
DuT: Samsung J7 Prime, mito, Redmi 4A

Build: 382
DuT: mito, Redmi 4A, Advan, Lenovo Vibe A, Sony Xperia Z3 Compact

**Comment by mTwTm** [comment]
Can't reproduce

**Comment by dakaizou** [comment]
[Video](https://drive.google.com/a/mozilla.com/file/d/0B0uVZlaHN366N2FGNlZQX0pzN0U/view?usp=sharing) reproducing on mito

**Comment by mTwTm** [comment]
Looks like the behavior/design of the Mito Gallery App. I'm suspecting that is the can't find previously available file logic for the Gallery. @dakaizou can you help find if the file is still visible in the File Explorer App, and/or Download through other browser and check if the same behavior holds?

**Comment by dakaizou** [comment]
mito

- Zerda: removed file _**found**_ in Gallery, not found in File Explorer
- Chrome: removed file not found in Gallery, not found in File Explorer
- UC: removed file _**found**_ in Gallery, not found in File Explorer

Redmi 4A

- Zerda: removed file not found in Gallery, not found in Explorer
- Chrome: removed file not found in Gallery, not found in Explorer
- UC: removed file not found in Gallery, not found in Explorer

**Comment by mTwTm** [comment]
That would be enough! Thanks! From my experiences I'd say that Chrome is doing something further steps such as notifying the MediaDB that the file is deleted so that all Gallery Apps would be notified about the remove so this awkward situation does not happen.

Engineering comment: Not very difficult but require some extra work. Will deal with this when this is listed as a P1 bug.

**Comment by mTwTm** [comment]
Unassign myself for this is triaged as P2

**Comment by NashTung** [comment]
Work for me. 
Video:
https://drive.google.com/open?id=1rSK5nIzhfT-sp7fidFQEyvZX7pGjqA77

Device: Advan i5C
Rocket: 2.0.0(4129).nightly
Android: 5.1
Android Webview: 51.0.2704.81
