### ISSUE TITLE
Failed to change the theme color after we disabled to show the banner

### ISSUE THREAD

**Issue by cynthiatang** [mozilla-mobile/FirefoxLite#2386]
STR: 
1. Launch Rocket
2. Tap the banner area after we disabled to show the banner

Expected result:
 - Change the theme color

Actual result:
 - Failed to change the theme color
 - Video: https://drive.google.com/open?id=1ekTfIlNV8K8b_NZ4-SYFHKMoP0LWTyTj

Reproduce Rate: 10/10

All devices
Rocket 3.0.0(6166).nightly

**Comment by chianger** [comment]
S2: ux enhancement
