### ISSUE TITLE
Private browsing without notification if Rocket made restricted app

### ISSUE THREAD

**Issue by joechengla** [mozilla-mobile/FirefoxLite#2394]

**Comment by joechengla** [comment]
6190 works as expected with notification showing up when private browsing

**Comment by chianger** [comment]
only one device (android 9.0) can reproduce.

**Comment by joechengla** [comment]
I think I found the root case. I accidentally had my Rocket as restricted app. After I remove the restriction I can see notification 
https://drive.google.com/file/d/1PwnXseu18BRlq0-Yt29QLt0zeJWjJ8Vv/view?usp=sharing
