### ISSUE TITLE
User cannot play some videos in landscape mode (Normal Browsing)

### ISSUE THREAD

**Issue by cynthiatang** [mozilla-mobile/FirefoxLite#2395]
1. Launch Rocket
2. Visit goo.gl/W7sgRc
3. Play the video in landscape mode

Expected Result
 - A user can play the video in landscape mode

Actual Result
 - A user cannot play the video in landscape mode
 - This issue cannot be reproduced in Focus
 - https://drive.google.com/open?id=1oBc0-gjuiWj8Tox6fTuOSufnTPl6CAdi

Reproduce Rate: 10/10

Pixel 2
Android 8.1
Rocket 3.0.0(6193).nightly
WebView 68.0.3440.91

**Comment by cynthiatang** [comment]
This issue can be reproduced when users watch portrait videos. (5 videos)

**Comment by chianger** [comment]
S1 but this actually depends on full "landscape mode" support. which is a feature in our backlog.
