### ISSUE TITLE
Word "today" has not been translated to "dina iki" (Javanese)

### ISSUE THREAD

**Issue by nfmia** [mozilla-mobile/FirefoxLite#2397]
In the following sections: 
a. screenshot history;
![bug 1](https://user-images.githubusercontent.com/42309002/43998252-b7e8f278-9e1b-11e8-8480-c8b4ce736b96.jpg)

b. browsing history, 
![bug](https://user-images.githubusercontent.com/42309002/43998254-bd7ea174-9e1b-11e8-9ad0-57bb974f01bf.jpg)

the word "today" has not been translated to "dina iki" (Javanese). It also happened in Sundanese (Su)

**Comment by fauzanalfi** [comment]
Additional information: it's only happened in "jv" and"su" and not in Indonesian (id)

**Comment by chianger** [comment]
maybe intermittent. QAWanted to see if this still happens.

**Comment by cynthiatang** [comment]
I can reproduce this issue.

**Comment by chianger** [comment]
Still reproducible on Javanese and Sundanese. The word "yesterday" isn't localized either.
