### ISSUE TITLE
Failed to erase private-browsing data after killing all Rocket actives from Task manager

### ISSUE THREAD

**Issue by cynthiatang** [mozilla-mobile/FirefoxLite#2400]
STR
1. Launch Rocket
2. Switch to Private mode
3. Visit a website
4. Tap system Task manager
5. Kill all Rocket actives
6. Relaunch Rocket and make sure that user erased private browsing data successfully

Expected 
  - Erase private browsing history

Actual result
 - After step 5, the private-browsing notification disappeared.  
 - After step 6, the previous private-browsing page is still in private mode without any notification. 
 - Video: https://drive.google.com/open?id=1hoYzqGJUKyPjrbiM_ScAjGNJWY0CUvkk

Lenovo 1000m
 Android 5.1
Rocket 3.0.0(6193)
WebView 68.0.3440.91

OPPO A37f 
Android 5.1.1
Rocket 3.0.0(6193)
WebView 68.0.3440.91

**Comment by chianger** [comment]
5.x is somewhat different here.
S2 as UX enhancement.
