### ISSUE TITLE
Rocket crashed twice during testing

### ISSUE THREAD

**Issue by mlwang32** [mozilla-mobile/FirefoxLite#2405]
Prerequisite:
N/A

STR:

User was executing normal testing operations

Expected result:
App should stay on over the course of testing

Actual result:
App crashed during normal testing, please see log for details
[advan_log.txt](https://github.com/mozilla-tw/Rocket/files/2281857/advan_log.txt)

Reproduce Rate: Happened only twice

Device: Advan i5C
Rocket Ver.: 3.0.0(6166).nightly
Android Ver.: 5.1
WebView: 67.0.3396.87

**Comment by mTwTm** [comment]
Take a brief look but failed to find relevant crash to diagnose STR.
