### ISSUE TITLE
System status bar disappear

### ISSUE THREAD

**Issue by dakaizou** [mozilla-mobile/FirefoxLite#241]
System status bar becomes blank on certain devices when browsing.

Build: 303
DuT: Redmi 4A

**Comment by Conjuror** [comment]
Due to the icons are redmi system bar is white and with no background. it'll look like while blank in Zerda app.

https://drive.google.com/a/mozilla.com/file/d/0B11T5xYLeXAOSkMwal9JY3FQbEE/view?usp=sharing

**Comment by chianger** [comment]
Android 6.0

**Comment by joechengla** [comment]
seems fixed already

**Comment by dakaizou** [comment]
Still reproducible on Redmi
Build: 1428

**Comment by cynthiatang** [comment]
This issue can be reproduced. 
Video: https://drive.google.com/open?id=1u7pWA31PcPew2a4jkK51e1ACVuqwkSP9

Device: Redmi Note 4
Rocket: 2.0.0(4212).nightly
Android: 7.0
Android Webview: 66.0.3359.158
