### ISSUE TITLE
Would be nice to stay in Task manager after killing Rocket normal active

### ISSUE THREAD

**Issue by cynthiatang** [mozilla-mobile/FirefoxLite#2413]
STR
 1. Launch other apps
 2. Launch Rocket
 3. Switch to private mode
 4. Tap Task manager
 5. Kill Rocket-Normal-Active

Expected Result
 - Stay in Task manager

Actual Result:
 - Back to system Home. It doesn't stay in Task manager
 - Launch Rocket and close it 
 - Erase private-browsing history
 - Show the toast twice.
 - Video https://drive.google.com/open?id=19TobamVRpBWm2d0NSoFqtX-CcFW8BG0F 

Reproduce Rate: 10/10

Redmi Note 4X
Android 7.0
Rocket 3.0.0(6193)
WebView 68.0.3440.91

**Comment by chianger** [comment]
S2 for this is UX enhancement.
