### ISSUE TITLE
Load private browsing performance

### ISSUE THREAD

**Issue by joechengla** [mozilla-mobile/FirefoxLite#2418]
Sometimes I feel like I'm waiting for private browsing activity to load and show up on my Pixel XL

**Comment by chianger** [comment]
+1. I came cross the same

**Comment by chianger** [comment]
oh actually different, it got stuck at the initial dark background page.

**Comment by chianger** [comment]
Consider to improve perceived performance, which this initiation of private mode is actually creating a separate process.
