### ISSUE TITLE
Import Bookmark from Firefox Account

### ISSUE THREAD

**Issue by mTwTm** [mozilla-mobile/FirefoxLite#2424]
We might not want to sync heavily (yet), but doing an import (and maybe export) interface sounds like something that can meet user needs but is also not too complex.

**Comment by chianger** [comment]
For Firefox Account import it might need mozilla android component?

**Comment by mTwTm** [comment]
We won't need them if we're not syncing. There is an export to html option in each browser.

**Comment by mTwTm** [comment]
This user agrees with me 😎 Feature request: sync/export bookmarks. Would prefer export because Firefox already has sync.

**Comment by tigercosmos** [comment]
Hope this feature release earlier.

**Comment by chianger** [comment]
relevant to #3033

**Comment by RichyHBM** [comment]
Would be great to have a simple import/export function just to be able to back them up

**Comment by kdm6389** [comment]
Bookmarks are lifeline,
also most important is password saving for rubbish website.
