### ISSUE TITLE
When device internal storage is almost full, download via Rocket will not trigger toast message warning user the internal storage is full

### ISSUE THREAD

**Issue by mlwang32** [mozilla-mobile/FirefoxLite#2433]
Prerequisite:
Internal storage (not SD card) is almost full

STR:
1. Launch Rocket
2. Visit a page with files to download
3. Attempt to download a file with its size over available storage

Expected result:
Warning toast message should be triggered

Actual result:
No warning toast message is observed

Reproduce Rate: 100%

Device: Samsung Galaxy J7 Prime
Rocket Ver.: 3.0.0(6193)
Android Ver.: 7.0
WebView: 67.0.3396.68

Screenshot:
![bug_internalstoragefull](https://user-images.githubusercontent.com/746727/44157941-3102f600-a0e6-11e8-9374-7060fec65e07.png)

**Comment by cynthiatang** [comment]
@mlwang32 
Please provide the video. Thanks

**Comment by mlwang32** [comment]
Please see the video with the link below:
https://drive.google.com/file/d/1xty7yBPtHjjxmnbmMNHiDOogAIW8sYRm/view?usp=sharing

**Comment by chianger** [comment]
S2: UX enhancement
