### ISSUE TITLE
After original screenshot image is removed by other App, thumbnail image is still displayed under menu - My shots

### ISSUE THREAD

**Issue by mlwang32** [mozilla-mobile/FirefoxLite#2434]
Prerequisite:
Existing screenshot

STR:

1. Remove a screenshot from other app
2. Launch Rocket
3. Tap on Menu
4. Tap on My shots
5. Tap on the thumbnails for missing image

Expected result
Thumbnail image should show default placeholder image after original image is removed

Actual result:
Original thumbnail image still displayed

Reproduce Rate: 100%

Device: Samsung Galaxy J7 Prime
Rocket Ver.: 3.0.0(6193)
Android Ver.: 7.0
WebView: 67.0.3396.68

Screenshot:
![screenshot_20180816_thumb1](https://user-images.githubusercontent.com/746727/44158875-7de7cc00-a0e8-11e8-9704-fcfa910f1cd9.png)
![screenshot_20180816_thumb2](https://user-images.githubusercontent.com/746727/44158876-7de7cc00-a0e8-11e8-8775-b3fc53a0df23.png)

**Comment by chianger** [comment]
seems we talked about this same issue before. let's triage to determine whether we want to fix it.
