### ISSUE TITLE
Private browsing gets cleared when open link from 3rd party app

### ISSUE THREAD

**Issue by joechengla** [mozilla-mobile/FirefoxLite#2440]
1. Privately browse something using rocket 
2. Don't close rocket and Goto a different app
3. Open link in 3rd part app using rocket
4. Link gets opened in rocket but private browsing also gets cleared

**Comment by chianger** [comment]
QAWanted to verify if the behavior is different across OS versions.

**Comment by chianger** [comment]
S2: enhancement
