### ISSUE TITLE
Localize 'autocomplete' for new markets

### ISSUE THREAD

**Issue by chianger** [mozilla-mobile/FirefoxLite#2442]

**Comment by chianger** [comment]
Per discussion we can take Firefox Focus as reference

**Comment by chianger** [comment]
Or Fennec.

**Comment by weslyhuang** [comment]
open question: do focus/fennec has that for all our new markets?

**Comment by cnevinc** [comment]
> open question: do focus/fennec has that for all our new markets? need dev to help check.

Fennec has only one list.
Focus have the same amount of list with us

**Comment by cnevinc** [comment]
I've looked at the sites in https://www.alexa.com/topsites/countries/TH
But we should pick and choose some of them. Not all of them are appropriate for top sites.

**Comment by chianger** [comment]
since we don't have the predefined domain list in place, i'm moving this ticket back to "in discussion".

**Comment by chianger** [comment]
since we don't have the predefined domain list in place, i'm moving this ticket back to "in discussion".
