### ISSUE TITLE
Need a transition from capturing screenshot to My shot's onboarding, or show "Screenshot saved" toat

### ISSUE THREAD

**Issue by cynthiatang** [mozilla-mobile/FirefoxLite#2448]
(Issue by Jack)
1. Install Rocket 3.1
2. Visit a website
3. Tap screenshot button

Expected result:
 - Need a transition from capturing screenshot to My shot's onboarding, or show "Screenshot saved" toat

Actual result:
 - No transition

Pixel2
Android 8.1.0
Rocket 3.0.0(6354)
WebView 68.0.3440.91

**Comment by chianger** [comment]
S2: enhancement.
