### ISSUE TITLE
Screenshot onboarding point at the wrong element (once)

### ISSUE THREAD

**Issue by cynthiatang** [mozilla-mobile/FirefoxLite#2449]
(Issued by Joe)

1.  Visit a website
2. Tap screenshot button
3. check the string "capturing screenshot of entire page ..."

![screenshot_20180820-160751](https://user-images.githubusercontent.com/12458450/44329747-dd9ef800-a497-11e8-96c1-4a1579b406fb.png)

**Comment by mlwang32** [comment]
Tested on Android 5.1, 6.0.1 and 7.0, did not find the issue described above.

**Comment by cynthiatang** [comment]
HI @mlwang32 , thanks for your help to verify it.

**Comment by chianger** [comment]
Unreproducible.  Le's close it if still not reproducible by Sep-M.

**Comment by chianger** [comment]
STR:
quickly rotate the phone between landscape/portrait mode.
