### ISSUE TITLE
The length of search bar in normal mode and private mode is different

### ISSUE THREAD

**Issue by cynthiatang** [mozilla-mobile/FirefoxLite#2451]
1. Compare the length of the search bar in normal mode and private mode

Actual
 - The length of search bar in normal mode and private mode is different
 - Video: https://drive.google.com/open?id=1N1PvuibF37LQSC8kO97OwtJbmSHgSuXF

Expected result:
 -  The length of search bar in normal mode and private mode is the same

All device

**Comment by chianger** [comment]
Peko said in private mode the length should be the same as normal mode.

**Comment by chianger** [comment]
UX improvement.
