### ISSUE TITLE
After cancelling download from the system notification list, no toast message is shown and the file remains on the download list.

### ISSUE THREAD

**Issue by mlwang32** [mozilla-mobile/FirefoxLite#2463]
Prerequisite:
N/A

STR:

1. Launch Rocket
2. Visit a page with files to download
3. Tap a file to download
4. Pull down system tray from the top of the screen
5. Tap cancel to cancel the download

Expected result:
A toast message is shown to notfiy the user the download is cancelled and the file is removed from the download panel.

Actual result:
No toast message for cancel download, file remains on the download list

Reproduce Rate: 100%

Device: Samsung Galaxy J7 Prime
Rocket Ver.: 3.0.0(6354)
Android Ver.: 7.0
WebView: 68.0.3440.91

Clip;
https://drive.google.com/open?id=1zBgseXtSjELQVZH8Uu7CZOVksYOOg4Do

**Comment by chianger** [comment]
We're currently using system download manager, so not much we can do.
It's UX enhancement suggestion. P3.

**Comment by mlwang32** [comment]
Cancelling download from system notification will remove it from the rocket downloads panel on android 8.
