### ISSUE TITLE
Experiment: Try different onboarding

### ISSUE THREAD

**Issue by joechengla** [mozilla-mobile/FirefoxLite#2489]
As Mozilla, we'd like to test different onboarding slides to understand how it helps with retention and engagement. Currently we have a fixed order of onboarding slides for all users 
1. Browse faster than ever
2. Screenshot the whole page
3. Next-level privacy
4. Save data=save money

- As Mozilla, we'd like to serve different onboarding slides in different order to users in different markets to understand how it helps with retention and engagement. 
- As Mozilla, we'd like to serve different onboarding slides in different order to users coming in from different acquisition channel to understand how it helps with retention and engagement.

**Comment by joechengla** [comment]
link to #1786

**Comment by mTwTm** [comment]
This will probably A/B tested by ourselves rather than by Firebase because of the timing issue. (Firebase not ready yet at onboarding.)

**Comment by chianger** [comment]
depends on #3079 and #3080

**Comment by chianger** [comment]
we can deploy after spikes mentioned above.
In parallel, MKT (@elin-moco ) can work on defining the configurations for target markets.
