### ISSUE TITLE
spike for #2515 Firebase in app messaging

### ISSUE THREAD

**Issue by mTwTm** [mozilla-mobile/FirefoxLite#2516]
Let's first take a look at the sdk, what it offers, and apk size imapct...etc.

**Comment by chianger** [comment]
refer to #2515

**Comment by cnevinc** [comment]
1. Limitation on criteria:  Firebase in-app message can let you set the trigger event, but you can do "2 minutes after the event" or "after the n-th xxx event"
2. There are bugs in 17.3. The dependency has a conflict with FCM. We have FCM, so it's not working.
