### ISSUE TITLE
multitab for private browsing

### ISSUE THREAD

**Issue by joechengla** [mozilla-mobile/FirefoxLite#2537]
as a user, I want to be able to have multiple private tabs, just like in normal browsing

**Comment by chianger** [comment]
very rough estimation is that it takes two weeks to implement and another two weeks to stabilize it

**Comment by chianger** [comment]
[Update] there are actually two options to implement: 1. GeckoView based. 2. Leverage  Android components 3. on top of current architecture

**Comment by chianger** [comment]
Upgrade Private browsing enhancement to P1.

**Comment by maverick74** [comment]
On the first tests of Firefox Lite, this is the main reason that keeps me from migrating from main Firefox!

Is there an ETA for this?

(as an off-topic and as mere curiosity, 
is Firefox based on Reference Browser?

What about the fantastic adblocking, is it based on any particular addon?)

**Comment by mTwTm** [comment]
Can't answer the ETA part but I can answer the other questions:

Lite is actually forked from Focus (though diverged a lot later) and the tracking protection ability is also derived from focus code base.
