### ISSUE TITLE
Failed to show "Don't ask again for this site until exit" again after tapping Home 

### ISSUE THREAD

**Issue by cynthiatang** [mozilla-mobile/FirefoxLite#2576]
Location permission: Allow

STR 
 1. Launch Rocket
 2. Visit baidu.com or mapquest.com
     --> show the dialog "Don't ask again for this site until exit"
 3. Tap Home (or press system Power button)
 4. Tap Rocket again ( or press system Power button again )
 5. Visit baidu.com or mapquest.com again

Expected Result:
 - After step4, the dialog "Don't ask again for this site until exit" should not disappear
 - After step5, it will show the dialog "Don't ask again for this site until exit" again

Actual Result:
 - After step4, the dialog disappeared
 - After step5, no dialog anymore even if users visit other websites
 - https://drive.google.com/open?id=1ZVqtU1-R7IFbEgLTDirohvUy4M8jeWg8

Pixel 2 
Android 8.1.0
Rocket 3.2.0(6852)
68.0.3440.91

**Comment by chianger** [comment]
S2 for it's enhancement. 
Note: Fennec can keep the dialog unclosed so it has no problem.
