### ISSUE TITLE
shopping promotion on 1111

### ISSUE THREAD

**Issue by joechengla** [mozilla-mobile/FirefoxLite#2599]

**Comment by cnevinc** [comment]
Should we reference this document to filter the sites? 
https://firefox-source-docs.mozilla.org/mobile/android/fennec/defaultdomains.html
I've checked Nightly(only in Taiwan) and they look fine. But should we document this campaign somewhere?

We may also need QA support to make sure all sites are compatible with Lite. If we send any extra data to the website, we should update our Telemetry wiki.
