### ISSUE TITLE
When visiting a website without network connection, website name under tab tray change between "Firefox Rocket" and "Webpage not available"

### ISSUE THREAD

**Issue by mlwang32** [mozilla-mobile/FirefoxLite#2635]
STR:

1. Launch Rocket
2. Disconnect the network
3. Visit to any website
4. Tap the tab tray 
5. Check the tab card elements
6. Tap search, then visit same website
7. Check tab tray again

Expected result:
On step 5 and 7, website name should be "Webpage not available"

Actual result:
The first time website name shows "Firefox Rocket", the second time it shows "Webpage not available"

Device and Rocket version:
Rocket 3.2.0(7057)
Device: Nexus 5
WebView: 68.0.3440.91
Android: 6.0.1

Clip:
https://drive.google.com/open?id=19medHXaiTApyTQ-j74st-fyeTK5a_D94

**Comment by chianger** [comment]
More like a UX enhancement to me. 
I believe it's also not regression.
