### ISSUE TITLE
Saved image cannot be viewed when on private mode

### ISSUE THREAD

**Issue by mlwang32** [mozilla-mobile/FirefoxLite#2645]
Precondition:
Have existing tab

STR:

1. Launch Rocket
2. Visit youtube in private mode
3. Long tap on an image and tap save image on the context menu

Expected result:
Image can be saved and viewed

Actual result:
System notification shows download but image cannot be viewed

Device and Rocket version:
Rocket 3.2.0(7057)
Device: Nexus 5
WebView: 68.0.3440.91
Android: 6.0.1

Clip:
https://drive.google.com/open?id=1kTJllALTlmGMd8pwn5Cm61UJCq4NLkKJ

**Comment by mlwang32** [comment]
Retest result:

Test result: Fail (image saved as a .bin file)
Rocket 3.1.0(6668)
Device: Nexus 5
WebView: 68.0.3440.91
Android: 6.0.1
Clip: https://drive.google.com/open?id=11aGc2yPFQsCyFchaD7txEX1lT-2EcuV2

**Comment by chianger** [comment]
Similar to #2653
