### ISSUE TITLE
Same image can be saved and opened in normal mode but not in private mode

### ISSUE THREAD

**Issue by mlwang32** [mozilla-mobile/FirefoxLite#2653]
STR
1. Launch Rocket
2. Visit wikipedia.org on normal mode
3. Long tap on wikipedia logo next to its title and tap save image
4. Open the image in system notification
5. Tap tab tray and enter private mode
6. Visit wikipedia.org again
7. repeat step 3-4

Expected result:
Same image downloaded from both normal and private mode should open 

Actual result:
Image downloaded from private mode cannot be opened 

Device and Rocket version:
Rocket 3.2.0(7057)
Device: Nexus 5
WebView: 68.0.3440.91
Android: 6.0.1

Clip:
https://drive.google.com/open?id=12sPz9rCa8kFfTkg-S8k_1tCOqZk5t0IY

**Comment by chianger** [comment]
save image is considered frequent used feature so this unexpected function is S1.
Though priority is TBD. 
note: this may not be always reproducible in all devices.
