### ISSUE TITLE
Find-in-page: Keyboard is sometimes hidden 

### ISSUE THREAD

**Issue by mlwang32** [mozilla-mobile/FirefoxLite#2655]
STR:

1. Launch Rocket
2. Visit Mozilla
3. Tap menu, then find in page

Expected result:
Keyboard should be open

Actual result:
Sometimes keyboard is hidden

Device:
Frequency: 3/4 or 4/5
Rocket 3.2.0(7095)
Device: Redmi 4X
WebView: 68.0.3440.91
Android: 7.1.2

Frequency: 1/4
Rocket 3.2.0(7095)
Device: Nexus 5
WebView: 68.0.3440.91
Android: 6.0.1

Frequency: rarely
Rocket 3.2.0(7095)
Device: Advan i5C
WebView: 68.0.3440.91
Android: 5.1

**Comment by chianger** [comment]
It happens a few times on my PixelXL.

**Comment by chianger** [comment]
this fix requires UI architecture change so let's not do this at this moment. same as #2657
