### ISSUE TITLE
Find-in-page: tapping cross on search bar won't close find in page mode

### ISSUE THREAD

**Issue by mlwang32** [mozilla-mobile/FirefoxLite#2657]
STR:

1. Launch Rocket 
2. Visit en.wikipedia.org/wiki/Mozilla
3. Tap Menu -> Find in page
4. Find the word "mozilla"
5. Tap x to close the find in page mode

Expected result: 
Find-in-page mode will close

Actual result:
Only search bar is closed, keyboard remains open

Rocket version:
3.2.0(7095)

Device and test results:

1. Fail
Device: Redmi 4X
WebView: 68.0.3440.91
Android: 7.1.2

2. Pass
Device: Nexus 5
WebView: 68.0.3440.91
Android: 6.0.1

3. Fail
Device: Advan i5C
WebView: 68.0.3440.91
Android: 5.1

**Comment by chianger** [comment]
It happens a few times on my PixelXL..
Maybe relevant to #2655

**Comment by cynthiatang** [comment]
Fail
OPPO A371 
Android 5.1.1
Rocket 3.2(7095).nightly
Webview 69.0.3497.100

======================

Pass
Lenovo A1000m
Android 5.1.1
Rocket 3.2(7095).nightly
Webview 69.0.3497.100
======================

pass
Vivo 1606
Android 6.0.1
Rocket 3.2(7095).nightly
Webview 69.0.3497.100

**Comment by chianger** [comment]
this fix requires UI architecture change so let's not do this at this moment.

**Comment by chianger** [comment]
removing assignee as Julian is no longer actively working on this.
