### ISSUE TITLE
Refine Topsite loading

### ISSUE THREAD

**Issue by mTwTm** [mozilla-mobile/FirefoxLite#2667]
Topsite loading currently takes ~450ms to load. A crucial part of it is bitmap decoding and dominant color picking. This can be enhanced in many ways. We should find some time to do this.

**Comment by mTwTm** [comment]
See #2628 for benchmarks.

**Comment by iamVP7** [comment]
Can i try by disabling the top site loading. I cloned the code recently, wanted to work on good first bugs.

**Comment by mTwTm** [comment]
This one would be a relatively complicated one given to achieve this we will need to optimize image decoding and/or database schema. We have a good first issue label that you might be interested.
