### ISSUE TITLE
no such table: browsing_history_legacy (code 1): , while compiling: DROP TABLE browsing_history_legacy

### ISSUE THREAD

**Issue by mTwTm** [mozilla-mobile/FirefoxLite#2672]

**Comment by chianger** [comment]
per discussion it might auto-recover as user keeps using it. 
leave the "needtriage" label so that we can revisit this in a few days.

**Comment by mTwTm** [comment]
I tend to believe this is merely some false positive on certain devices so try catch or those sort of thing should be enough.
