### ISSUE TITLE
Website shortcut cannot be added to system home screen (Advan i5C)

### ISSUE THREAD

**Issue by mlwang32** [mozilla-mobile/FirefoxLite#2714]
Description
User cannot add shortcut to system home screen

STR
1. Launch rocket
2. Visit a website
3. Tap menu -> tap add to home icon

Expected result
A shortcut to the website should be added to the system home screen

Actual result
Rocket closes, no shortcut was added to home

Clip
https://drive.google.com/open?id=1FVVH_bqRyo2aqY3d7H4eECueIQSIJsVr

Device info
Rocket 3.3.0(7339)
Device: Advan i5C
WebView: 69.0.3497.100
Android: 5.1

Reproduce Rate
5/5

**Comment by cynthiatang** [comment]
@mlwang32 could you please test it via Chrome?

Note:  This issue cannot be reproduced on OPPO A371 with Android 5.1.1
https://drive.google.com/open?id=1J1_Ecb-Z0OmFJH42PhX5CR5Gb8_tww5y

Rocket 3.3.0(7339)
WebView: 69.0.3497.100

**Comment by mlwang32** [comment]
@cynthiatang user can add shortcut to home screen using Chrome.
[https://drive.google.com/open?id=19NPdoqe7uK8_6fX2z-543Stl95KW-PsN](url)

Chrome 69.0.3497.100

**Comment by chianger** [comment]
so it looks like a regression, but so far it happens on one device only. (Advan i5c)?

**Comment by chianger** [comment]
QAWanted to check regression window:

Per the testing result it happened between these two builds. Can we get specific window to a nightly level? 

    Rocket 3.1.0(6668)
    WebView: 69.0.3497.100
    Advan i5C (Android 5.1)
    Pass

    Rocket 3.3.0(7202)
    WebView: 69.0.3497.100
    Advan i5C (Android 5.1)
    Fail

**Comment by ivantw08** [comment]
Rocket 3.1.0(6747)
WebView: 69.0.3497.100
Advan i5C (Android 5.1)
Pass

Rocket 3.2.0(6783)
WebView: 69.0.3497.100
Advan i5C (Android 5.1)
Fail

**Comment by ivantw08** [comment]
another issue about shortcut found #2857
