### ISSUE TITLE
Prevent crash by remote config

### ISSUE THREAD

**Issue by cnevinc** [mozilla-mobile/FirefoxLite#2727]
**Why/User Benefit/User Problem**
Prevent crash by remote config

**User story**
If we use the remote config as integer, but the serverside is string, make sure this won't crash the client

**Acceptance Criteria (how do I know when I’m done?)** 
1. Set remote config as string, use it as integer: shouldn't crash, should use the default value
2. Set remote config as integer, use it as string: shouldn't crash, should use the default value

**Additional context**
There's no crash now, but we should do it before it happens.

**Comment by mTwTm** [comment]
@cnevinc Is this already solved?
