### ISSUE TITLE
[dogfooding] Long press search on home, show "paste" context menu

### ISSUE THREAD

**Issue by Conjuror** [mozilla-mobile/FirefoxLite#275]
build 357. suggest to put as P2.

**Comment by NashTung** [comment]
Work for me.
Show "Frequent phrases" 
Video:
https://drive.google.com/open?id=1-ouiyrNpuaB9XEj_EZfTd-4H_7UfDgzm

Device: Redmi 4A
Rocket: 2.0.0(4168).nightly
Android: 7.1.2
Android Webview: 66.0.3359.126

**Comment by mTwTm** [comment]
This bug is about tapping on the "fake" search box in Home. So to me, it's still there.

**Comment by mTwTm** [comment]
Remove duplicate severity tag S3, only keeping S2.
