### ISSUE TITLE
Private mode's keyboard background in normal mode  

### ISSUE THREAD

**Issue by ivantw08** [mozilla-mobile/FirefoxLite#2762]
**Describe the bug**
Private mode's keyboard background in normal mode  .
Chrome's keyboard background is white in normal mode.

In chrome app, there are 2 different types of windows. Normal window and Incognito window.
In normal window, keyboard background is blank.
![63487d5d-c877-45d7-8164-70a75eefe264](https://user-images.githubusercontent.com/28133026/47060127-e2193000-d1fe-11e8-8be7-ebe01b8a180d.jpg)

In Incognito window, there is a watermark in the background.

![a8fd0c64-7407-4fa7-869e-dc0ce396aec1](https://user-images.githubusercontent.com/28133026/47060364-e3972800-d1ff-11e8-9406-24f9c459fca6.jpg)

**Steps To Reproduce**

1. Launch Rocket.
2. Click search.

or

1. Launch Rocket.
2. open a website page.
3. click the url area.

**Expected behavior**
Keyboard show up with white background.

**Actual behavior**
Keyboard show up with private mode background.

**Screenshots/videos**
https://drive.google.com/file/d/1_vw84jNjGGeLfMhEARIQCkLKs4Axhzi9/view?usp=sharing

**Device info (please complete the following information):**

- Device: Nexus 5 , Redmi 4X
- OS: Android: Android: 5.1 ,Android: 7.1.2
- Webview 69.0.3497.100
- Version 3.4.1(7597)

**Reproduce rate**
100%

**note**
Advan i5C does not have private mode's keyboard background in Chrome and Focus app.

**Comment by cnevinc** [comment]
I don't understand why this is a bug. @ivantw08 Could you please explain why?
