### ISSUE TITLE
Important Night Mode refactor work

### ISSUE THREAD

**Issue by cnevinc** [mozilla-mobile/FirefoxLite#2773]
Refactor Night Mode - Make it easy to maintain 
1. Put Night Mode in a separate module - (Separation of concerns)
2. Extract intent object out of AdjustBrightnessDialog (Single Responsibility)
3. Add tests to protect the switching logic between activities. (protect the assumption of activity switching. Maybe use application scope observer to align the state between different activities).

**Comment by weslyhuang** [comment]
1. Put Night Mode in a separate module - (Separation of concerns)
    --> 1st commit of PR#2796 by Nevin
2. Extract intent object out of AdjustBrightnessDialog (Single Responsibility)
    --> 2nd commit of PR#2796 by Joseph, ready for review
