### ISSUE TITLE
 Invaild url have previous shortcut's website

### ISSUE THREAD

**Issue by ivantw08** [mozilla-mobile/FirefoxLite#2831]
**Steps To Reproduce**
1. Launch a website (ex: amazon.com)
2. Go to a invalid website (ex:a.b.c)
3. Click menu -> shortcut

**Expected behavior**
Shortcut with invalid url .

**Actual behavior**
Showed the previous website(amazon.com)

**Screenshots/videos**
https://drive.google.com/open?id=1wDqwsQVT-RdhU8aBrPPFhnRXazufx0oa

**Device info (please complete the following information):**

- Device:nexus 5
- OS: Android: 6.0.1
- WebView: 69.0.3497.100
- Firefox Lite: 1.0.0(7855)

**Comment by weslyhuang** [comment]
don't look like a release blocker (adding short-cut for an error page).

**Comment by chianger** [comment]
S2 to me. This is somewhat edge case.
