### ISSUE TITLE
blank area cannot change background  by tapping 2 times 

### ISSUE THREAD

**Issue by ivantw08** [mozilla-mobile/FirefoxLite#2849]
**Steps To Reproduce**
1. Launch Lite
2. remove any site's cion 
3. tap 2 times the area where had icon

**Expected behavior**
change background's color 

**Actual behavior**
nothing 

**Screenshots/videos**
https://drive.google.com/file/d/1CwJhU_Lvbp2ZRYx8IYVPc3qm8gvWRZd-/view

**Device info (please complete the following information):**

- Lite 1.0.0(7916)
- Device: Redmi 4A
- WebView: 69.0.3497.100
- Android: 7.1.2

**Comment by chianger** [comment]
probably by design. let me circulate with more people to confirm

**Comment by mTwTm** [comment]
Bug that needs some workaround. Suggest low priority though.
