### ISSUE TITLE
Create country-specific domain lists

### ISSUE THREAD

**Issue by cnevinc** [mozilla-mobile/FirefoxLite#2872]
**Why/User Benefit/User Problem**
Create a country-specific domain list
We need to follow this process to pick and sanitize the domain list.
https://firefox-source-docs.mozilla.org/mobile/android/fennec/defaultdomains.html

**User story**
As a user. I would like the autocomplete list becomes more suitable for my region.

**Comment by dimqua** [comment]
Besides, would be nice to have an option to add your own domains to this list. Such an option is already present in Firefox Focus.
