### ISSUE TITLE
VPN icon never show again after expressVPN installed 

### ISSUE THREAD

**Issue by ivantw08** [mozilla-mobile/FirefoxLite#2889]
**Description:**
Tap the no option when ExpressVPN is installing. Vpn icon will never show again.

**Steps To Reproduce**
1. Launch Firefox Lite
2. Tap VPN icon and allow to download ExpressVPN app
3. Relaunch Firefox Lite when  ExpressVPN app is installing
4. Tap VPN icon then tap "NO" option.
5. Relaunch Firefox Lite after ExpressVPN installation finish

**Expected behavior**
VPN icon never show again after expressVPN installed 

**Actual behavior**
VPN icon should show again after expressVPN installed 

**Screenshots/videos**
https://drive.google.com/open?id=1tcfGjEBXPg-O6D0F-ANnJSHoYKS1mw-J

**Device info (please complete the following information):**
 - Device: Nexus 5
 - OS:  Android 6.0.3
 - Webview: 69.0.3497.100
 - Version: 1.0.1(8139 nightly)

**Comment by Jacklin-ux** [comment]
It's OK -> when installing and users click "No", we hide the vpn icon. 
But what I expect is when launch Firefox Lite next time and find vpn app has been installed, show vpn icon. Is it doable?

**Comment by chianger** [comment]
S2 for it's UX enhancement. We'll look at data and revisit this.
