### ISSUE TITLE
User feedback: video mode there should be some facilities like volume ,brightness incresing system. There should be some systen to forward video by 10 seconds like that.

### ISSUE THREAD

**Issue by joechengla** [mozilla-mobile/FirefoxLite#2921]
video mode there should be some facilities like volume ,brightness incresing system. There should be some systen to forward video by 10 seconds like that.

**Comment by witsmo** [comment]
Not able to reproduce with Samsung S8 Android 8 
Firefox Lite 1.0.5(8905).nightly
WebView version:71.0.3578.99
