### ISSUE TITLE
Disable browsingWebsiteBackAndForward_backAndFrowardToWebsite

### ISSUE THREAD

**Issue by mTwTm** [mozilla-mobile/FirefoxLite#2932]
See #2855 
It's failing at a rate more than 10%, we should remove this test to stop blocking our workflow.

**Comment by cnevinc** [comment]
see: https://app.bitrise.io/build/b9cebd4f9bb44e39 & https://app.bitrise.io/build/3340e111adcca247

I'll have a PR and disable it first
