### ISSUE TITLE
[Smoke Test] History won't be updated imediately

### ISSUE THREAD

**Issue by Conjuror** [mozilla-mobile/FirefoxLite#294]
Build 382

Prerequisite:
1. Some browsing history in Zerda

STR:
1. Launch Zerda
2. Tap on settings
3. Tap on History
4. Tap on any browsing history
5. Repeat Step 2 & 3 and observe the list

Expected Result:

5. The browsing history is updated

Actual Result:

5. History will be updated a few seconds later.

**Comment by joechengla** [comment]
seems fixed already?

**Comment by NashTung** [comment]
This issue can be reproduced.
Video:
https://drive.google.com/open?id=1kNoZ75kulj1vIRle2MpZtTonp9_bP28v

Device: Redmi 4A
Rocket: 2.0.0(4168).nightly
Android: 7.1.2
Android Webview: 66.0.3359.126
