### ISSUE TITLE
User feedback: The night mode is increasing the screen brightness drastically instead of turning it black with white fonts

### ISSUE THREAD

**Issue by joechengla** [mozilla-mobile/FirefoxLite#2961]
The night mode is increasing the screen brightness drastically instead of turning it black with white fonts... I think it's a bug..pls fix it...still m giving five stars..for appreciation & motivation !!!

**Comment by chianger** [comment]
per the description, it's actually by design. the brightness part is dup as #2972 
black background with white fonts are likely feature.
