### ISSUE TITLE
Can't download large file 

### ISSUE THREAD

**Issue by cnevinc** [mozilla-mobile/FirefoxLite#2966]
File: https://dl.google.com/dl/android/studio/install/3.2.1.0/android-studio-ide-181.5056338-mac.dmg

**Comment by mTwTm** [comment]
Can't reproduce on my Android 8 Nokia 5.1... Could it be that this happens when you don't have enough space on your device?

**Comment by chianger** [comment]
For this bug the feasible scope is to enhance user experience by providing a proper message, saying "internal storage is not sufficient".
