### ISSUE TITLE
Please transplant this feature

### ISSUE THREAD

**Issue by ghost** [mozilla-mobile/FirefoxLite#2984]
@chianger @mTwTm @josephyu1110 
![screenshot_2018-11-29-00-54-01-965_org mozilla firefox](https://user-images.githubusercontent.com/45565984/49380010-92a9a780-f74b-11e8-91ce-5663f4f479c4.png)

Here we have to change to "block the remote font"

thank you!

**Comment by chianger** [comment]
For reference: Firefox Focus has the feature "block web fonts" but by default it's off.
