### ISSUE TITLE
Make install tracking more accurate.

### ISSUE THREAD

**Issue by cnevinc** [mozilla-mobile/FirefoxLite#3019]
**Why/User Benefit/User Problem**
Make install tracking more accurate. 

**User story**
There's a new way to track user install for Adjust. But it need to update the SDK and the implementations. See :
https://github.com/adjust/android_sdk#google-play-referrer-api
https://developer.android.com/google/play/installreferrer/igetinstallreferrerservice
https://developer.android.com/google/play/installreferrer/library

**Acceptance Criteria (how do I know when I’m done?)** 
1. Test the referral in Adjust console using Nightly / Beta build

**Comment by Daisy-pliu** [comment]
Discuss  with @chianger no qa wanted need
