### ISSUE TITLE
Integrated Firefox Account with custom attributes for Lite users

### ISSUE THREAD

**Issue by chianger** [mozilla-mobile/FirefoxLite#3033]
**Why/User Benefit/User Problem**
To start creating relationship with our users, Firefox Account is our first step to do so.

**User story**
As Mozilla, I would like make use of Firefox Account infrastructure to save specific custom app data for users; such as reward points for example. 

**Acceptance Criteria (how do I know when I’m done?)** 
1. Users can create/sign in to Firefox Account
2. We can save our custom data and retrieve it using Firefox Account 
3. We have properly implemented UI event telemetry

**Additional context**

### put correct labels ###
Add corresponding labels from the right panel to make it clearer
telemetry wanted - does this introduce adding or modifying telemetry?
UX/VD wanted - does this require UX/VD input to make the story ready for development
l10n wanted - does this introduce adding or modifying in-product strings?
help wanted - does this feature suitable for people other than the core team to wok on?

**Comment by cnevinc** [comment]
change to P1 on @chianger's behalf.

**Comment by cnevinc** [comment]
I imagine there's a use case like this:
When the user first enters history panel, we ask them if they want to see their history in Firefox Account, and then ask them to sign in ..... [sample](https://github.com/mozilla-mobile/android-components/tree/master/samples/sync-history)

**Comment by chianger** [comment]
My apology for typo of that comment. 
This should be P2 (upgraded from P3).
