### ISSUE TITLE
Shopping search  (enhancement of #3028)

### ISSUE THREAD

**Issue by Jacklin-ux** [mozilla-mobile/FirefoxLite#3054]
The proposal link: https://drive.google.com/file/d/1U2CKeuje5LiTrSJFLq5yG_q1i_aSlFvl/view?usp=sharing

--------------------------------------

**Why/User Benefit/User Problem**
To make something easier ...etc

**User story**
As a ..., I would like ...

**Acceptance Criteria (how do I know when I’m done?)** 
1.
2.
3.

**Additional context**

### put correct labels ###
Add corresponding labels from the right panel to make it clearer
telemetry wanted - does this introduce adding or modifying telemetry?
UX/VD wanted - does this require UX/VD input to make the story ready for development
l10n wanted - does this introduce adding or modifying in-product strings?
help wanted - does this feature suitable for people other than the core team to wok on?

**Comment by chianger** [comment]
This design is further enhancement of #3028
