### ISSUE TITLE
After leaving the private mode, tapping exit, the app returns to the private mode on Android 9

### ISSUE THREAD

**Issue by mTwTm** [mozilla-mobile/FirefoxLite#3056]
This seems to be an Android 9 bug which is tracked here: https://issuetracker.google.com/issues/122493536

**Comment by mTwTm** [comment]
We do, however, might have other workarounds like launching home (?) if we want to fix this.

**Comment by chianger** [comment]
on android 9 only and this is likely android's issue. 
we have no intention to work around for this at this moment

**Comment by mTwTm** [comment]
From the issue tracker
>  The development team has fixed the issue that you have reported and it will be available in a future build.
Let's close this and only deal with it if we have a lot of outstanding Android 9 devices that don't have this fix when it becomes the mainstream.
