### ISSUE TITLE
Desktop sites which are not friendly for mobile.

### ISSUE THREAD

**Issue by dakaizou** [mozilla-mobile/FirefoxLite#306]
Firefox focus has the same issue
[Testing page](https://books.google.com.tw/books?id=8piZf6fXimcC)

[Screenshots on different browsers](https://drive.google.com/drive/folders/0B0uVZlaHN366YmUzbWlMbUl6aEE?usp=sharing)

Build: 401
DuT: mito, Advan

**Comment by Conjuror** [comment]
Move to P2 due to not mobile first.

**Comment by mTwTm** [comment]
Related to #1284

**Comment by mTwTm** [comment]
Related to #1137
