### ISSUE TITLE
Add download failure event ping in download manager

### ISSUE THREAD

**Issue by elin-moco** [mozilla-mobile/FirefoxLite#3069]
**Why/User Benefit/User Problem**
Occasionally having negative reviews regarding download problems.
https://play.google.com/apps/publish?account=7083182635971239206#ReviewDetailsPlace:p=org.mozilla.rocket&reviewid=gp:AOqpTOGcJYoXckugvk_jQI99hNX0G1RClLHQJ_ncBvtYCZAadOoGjpZzPj_ROgZfhSKIZZr742_TcFmoJL9YMOc
https://play.google.com/apps/publish?account=7083182635971239206#ReviewDetailsPlace:p=org.mozilla.rocket&reviewid=gp:AOqpTOEPVX8ZqIHRqstjiMncudUaI20C4_qKPndbe7FeSueNl4U7yP11LO_9q_gQlqKzbG0e_pqFXHQBPXbhl_o

**User story**
As a PM (I'm writing this on behave of Joe), I would like to learn about the cause of download failure, and the range of impact, so we can take actions accordingly if any chance to fix it.

**Acceptance Criteria (how do I know when I’m done?)** 
1. Be able to know the percentage of users facing download problem
2. Be able to know the cause of the problems

**Suggested event structure:**
 -  Download failed/show/download/error {cause}

**Comment by chianger** [comment]
this is follow up of #2002 since we want to further understand this issue.
priority to be discussed in the grooming meeting.

**Comment by elin-moco** [comment]
Suggested event structure:
 - Download failed/show/download/error {cause}

**Comment by chianger** [comment]
Size M to include discussion of what telemetry infra for collecting the errors and the scope.

**Comment by elin-moco** [comment]
Maybe we should not record this as event ping, probably send non-fatal error to Firebase crashlytics?
