### ISSUE TITLE
Can not see image downloaded snack bar in private mode

### ISSUE THREAD

**Issue by Daisy-pliu** [mozilla-mobile/FirefoxLite#3070]
**Steps To Reproduce**
1. launch app 
2. open private mode
3. long click any image 
3. click [save image]

**Expected behavior**
ask for access permission, show snack bar [file donwloaded] and [open]

**Actual behavior**
not show  snack bar, only notification shows downloaded image completed

**Device info (please complete the following information):**
 - Pixel 2 (9.0)
 - Redmi 4X (7.1.2)
 - Vivo 1606 (6.0.1)

**Reproduce rate**
10/10

**Comment by chianger** [comment]
see also #2519 and #2645

**Comment by chianger** [comment]
it's actually a feature not implemented in private mode. 
tagging P1 as we want to improve Private mode for our users.

**Comment by chianger** [comment]
QAWanted for test case

**Comment by chianger** [comment]
looks like #2653 is relevant

**Comment by josephyu1110** [comment]
Will add setDestinationInExternalPublicDir to download request in private session to let downloaded file is openable.

**Comment by mTwTm** [comment]
Push back to the next sprint due to conflict. (It's also still under review.)

**Comment by Daisy-pliu** [comment]
**verify:**❌
**Test version**
RC 1.1.4 (10373)
**Test step :** 
1. launch app
2. open https://mozilla.slack.com/archives/DE18AFX53/p1549184862000200 in private mode 
3. long click any image 
4. click [save image]

**Expected behavior:**
ask for access permission, show snack bar ,show notification [file donwloaded] and [open]

**Actual behavior**
not show snack bar,show access permission, no notification to show image downloaded  - Google Pixel 2 (9.0)
not show snack bar, show access permission, only show notification to show image downloaded  - Redmi 4x (7.1.2)

Reproduce rate
5/5

**Comment by Daisy-pliu** [comment]
**Verify:** ❌
**Test version**
RC 1.1.4 (10373)
**Test step :** 
1. launch app
2. open https://downloadfiletest-eab8a.firebaseapp.com/ in private mode 
3. long click any image 
4. click [save image]

**Expected behavior:**
ask for access permission, show snack bar ,show notification [file donwloaded] and [open]

**Actual behavior**
not show snack bar, show ask for access permission, only show notification for image downloaded  - Redmi 4x (7.1.2)

**Reproduce rate**
5/5

**Comment by Daisy-pliu** [comment]
[private mode enhancement test case](https://docs.google.com/spreadsheets/d/1AJZaeNDln6TJWjoilB3oz9AYpVkCTCkH4tXoo9oJMz8/edit?ts=5bea38ae#gid=169764628&range=D336) is ready
