### ISSUE TITLE
Remove in-product "Rocket" and "Zerda"s

### ISSUE THREAD

**Issue by mTwTm** [mozilla-mobile/FirefoxLite#3076]
We've renamed from zerda to rocket and now Firefox Lite. This is a low priority task to remove all Rocket or Zerda occurrences in non-user-facing places like comments.

**Comment by bear-my-wrath** [comment]
Hello, I'd like to solve this bug.

**Comment by mTwTm** [comment]
Nice! Feel free to send a pull request and I'll check for the rest :).
