### ISSUE TITLE
Support Private Browsing Custom Tabs

### ISSUE THREAD

**Issue by joechengla** [mozilla-mobile/FirefoxLite#3087]
**Why/User Benefit/User Problem**
To make something easier ...etc
To be completed

**User story**
As a user, I would like open third party app links in Private Browsing.

**Acceptance Criteria (how do I know when I’m done?)** 
1.  To be completed
2.
3.

**Additional context**

### put correct labels ###
Add corresponding labels from the right panel to make it clearer
telemetry wanted - does this introduce adding or modifying telemetry?
UX/VD wanted - does this require UX/VD input to make the story ready for development
l10n wanted - does this introduce adding or modifying in-product strings?
help wanted - does this feature suitable for people other than the core team to wok on?

**Comment by chianger** [comment]
Upgrade Private browsing enhancement to P1.

**Comment by chianger** [comment]
Confirmed that this is P3 atm together with #3120
