### ISSUE TITLE
Download failed/paused; Downloading Animation beside ... menu isn't stopped

### ISSUE THREAD

**Issue by joechengla** [mozilla-mobile/FirefoxLite#3093]
1.0.9 (9567)
When download failed or paused the indicator still show downloading 
Device: Samsung (6.0.1)/Sony Z3C (6.0.1)
Samsung (6.0.1) will always download failed https://github.com/mozilla-tw/FirefoxLite/issues/3097

Sony Z3C steps 
1. Use Lite to download a file (keep Lite in foreground)
2. Turn off Wifi (or data) thru notification
3. System notification removes the downloading indication
4. Lite (in foreground) still show downloading indicator on the ...menu

This only occurs if Lite has been always in the foreground. If I went to other apps then come back to Lite, this symptom will not happen

**Comment by chianger** [comment]
relevant to #3096. 
S2 as visual enhancement
