### ISSUE TITLE
"Firefox Lite Nightly is running in the background" while moving file to SD card 

### ISSUE THREAD

**Issue by joechengla** [mozilla-mobile/FirefoxLite#3094]
1.0.9 (9567)
it will show up easily if downloading a big file 
Device:
Sony Z3C (6.0.1)
vivo (6.0.1)
Maybe we can change the notification message later on.

Sony Z3C Steps
1. Download a big file (e.g. 500MB) using Lite 
2. When download is finished (and Lite is moving the file from internal to SD Card - user doens't know the file is being moved)
3. System will show a persistent notification "Firefox Lite Nightly is running in the background"
4. The message will disappear when the file move is completed

**Comment by manddy** [comment]
@joechengla If the user has selected internal storage in the settings even then the file be moved SD card?could you please clarify this.
