### ISSUE TITLE
[UI Testing] setDelay for MockWebServer

### ISSUE THREAD

**Issue by cnevinc** [mozilla-mobile/FirefoxLite#3110]
when using MockWebServer, the page finishes loading too fast that when we register the SessionIdelingResource, it's already done and thus IdlingResource never get the complete signal.
[see](https://github.com/mozilla-tw/FirefoxLite/blob/b86fe9e05d5fe0cc9698441c236d8b23d2469d8d/app/src/androidTest/java/org/mozilla/focus/autobot/SessionRobot.kt#L38)

To avoid this, try to use 
and upgrade the latest version[( testImplementation("com.squareup.okhttp3:mockwebserver:3.12.1"))](https://github.com/square/okhttp)

**Comment by rpappalax** [comment]
@cnevinc did you notice if this helped to resolve your issue?  We may be blocked from upgrading our mockwebserver version for fenix for now so just wanted to verify if that helped at all
