### ISSUE TITLE
Consider changing default night mode brightness to "very dim" 

### ISSUE THREAD

**Issue by joechengla** [mozilla-mobile/FirefoxLite#3121]
User feedback: Night mode isnt working. Only the tab and bar gone black, the webpage is still white and it burned my eyes. Will change to 5 if it is fixed

https://play.google.com/apps/publish?account=7083182635971239206#ReviewDetailsPlace:p=org.mozilla.rocket&reviewid=gp:AOqpTOFQsXJ7wXimpkORkDdPTcWNGfU4y3rlJPKWmurLaReQ7zdqbbxxpGHvNZ8RK0RNFvvPrvb7y9ZHEKsFAFA

**Comment by iadeelzafar** [comment]
@mTwTm is it up for grabs now? If yes, please assign me this.

**Comment by mTwTm** [comment]
@Jacklin-ux do we have a proposal?

**Comment by Jacklin-ux** [comment]
One idea from user feedback we can implement:
- Disable device's blue light when turn on night mode. We also can have its switch when open night mode's settings. (The design and the effect is as below)
<img width="375" alt="Screenshot 2019-04-22 at 10 14 57 AM" src="https://user-images.githubusercontent.com/22672569/56479335-91ed9400-64e7-11e9-8cf3-cdc0f524ad15.png">

FYR.

**Comment by iadeelzafar** [comment]
@Jacklin-ux This looks great.
Can I go forward implementing this? @mTwTm

**Comment by mTwTm** [comment]
Yes! Now that we have the UX approval it should be a wise use of your time so feel free to get started.

**Comment by iadeelzafar** [comment]
@mTwTm I did some research on how we can dim the screen using code and I found this app [Dimmer](https://github.com/code-crusher/Dimmer) very useful. I'm moving forward with a similar approach for dimming the screen.

**Comment by iadeelzafar** [comment]
@mTwTm I've made this sample app to show how I'm going to implement the feature of cancelling blue light. Have a look at this [repo](https://github.com/iadeelzafar/Dim).

**Comment by iadeelzafar** [comment]
@mTwTm @Jacklin-ux @cnevinc

**Comment by Jacklin-ux** [comment]
@weslyhuang please add this to planning

**Comment by chianger** [comment]
@iadeelzafar can you submit a PR so that we can arrange resource to review?

**Comment by iadeelzafar** [comment]
@chianger I'll make a PR soon. I just created a sample app so that you guys could confirm if this is the right way to approach this feature.
