### ISSUE TITLE
The download hint and menu buttons show at different location while switching between home page and browsing page

### ISSUE THREAD

**Issue by Jacklin-ux** [mozilla-mobile/FirefoxLite#3135]
**Describe the bug**
Downloading... you will obviously see the download hint and menu buttons show at different location while switching between home page and browsing page

**Steps To Reproduce**
Switch between home page and browsing page, you will see they are at different location

**Expected behavior**
They are at the same location

**Actual behavior**
Show at different place

Pixel3
1.0.1(9745),nightly
71.0.3578.99

**Comment by chianger** [comment]
Visual improvement.
