### ISSUE TITLE
Migrate from support libraries to AndroidX

### ISSUE THREAD

**Issue by pocmo** [mozilla-mobile/FirefoxLite#3137]
Migration tracking meta issue: https://github.com/mozilla-mobile/android-components/issues/1903

For details please read the linked meta issue.

TL;DR: We want to switch from the support libraries to the AndroidX libraries since that is where new features are getting developed. We need downstream app projects to migrate first before we can migrate up the dependency tree (Android Components, Application Services, GeckoView, ..).

**Comment by Daisy-pliu** [comment]
This refactoring has huge impact so a full run test is requested after PR landing.
