### ISSUE TITLE
long click to websearch will fail when go back through task manager 

### ISSUE THREAD

**Issue by Daisy-pliu** [mozilla-mobile/FirefoxLite#3142]
**Description**
long click to websearch will fail when go back through task manager 

**Steps To Reproduce**
1.  launch external app ex: Gmail
2. long click on any text ex: News
3. choose [websearch] to open search "News" result with firefox lite
4. once lite open successfully, open task manager to back to Gmail
5. long click on any other text ex: Shopping
6. choose [websearch] to open search "Shopping" result with firefox lite

**Expected behavior**
it opens search "Shopping" result with firefox lite 

**Actual behavior**
it opens search "News" result with firefox lite 

**Screenshots/videos**
https://mozilla.slack.com/archives/C6NHAKGQ3/p1549211310190500

**Device info **
Device info 1
 - Device: Google pixel 3 XL
 - OS: 9.0
 - Webview: 71.0.3578.99
 - Version: 1.0.10(9617)

Device info 2
 - Device: Google pixel 2
 - OS: 9.0
 - Webview: 71.0.3578.99
 - Version: 1.0.10(9617)

Device info 3
 - Device: Samsung galaxy s7 edge
 - OS: 8.0
 - Webview: 71.0.3578.99
 - Version: 1.0.10(9617)

**Reproduce rate**
10/10

**Note**
on step 4. if we tap back button to back to Gmail instead of using system task manager, it will work. 
This issue not happen on Nexus (6.0.1), vivo 1606 (6.0.1), Redmi 4x(7.1.2) with same version 1.0.10(9617) and same webview 71.0.3578.99

**Comment by chianger** [comment]
Per the note, switching with back button works fine. Giving S2.
