### ISSUE TITLE
Distribute Firefox Lite on Xiaomi App Store in India and Indonesia

### ISSUE THREAD

**Issue by joechengla** [mozilla-mobile/FirefoxLite#3212]
https://bugzilla.mozilla.org/show_bug.cgi?id=1386740

**Comment by chianger** [comment]
action: to confirm with RelMan how we will further manage the future APK releases

**Comment by chianger** [comment]
On April-18, we have the package name claimed on Xiaomi store and Sylvestre uploaded apk. There is the signature issue not resolved yet.

**Comment by chianger** [comment]
On April-18, we have the package name claimed on Xiaomi store and Sylvestre uploaded apk. There is the signature issue not resolved yet.
