### ISSUE TITLE
Fix default browser settings telemetry

### ISSUE THREAD

**Issue by elin-moco** [mozilla-mobile/FirefoxLite#3220]
**Describe the bug**
As per discussions with @mTwTm @cnevinc, the state of default browser settings should only contain True/False, but currently we have 85% null instead. 

**Steps To Reproduce**
Check this telemetry dashbaord:
https://sql.telemetry.mozilla.org/queries/47751#129153

**Expected behavior**
There should be no 'null' in pref_default_browser setting

**Actual behavior**
There are 85% of null in pref_default_browser

**Reproduce rate**
This is across all versions/devices.

**Additional context**
@mTwTm @cnevinc took a quick look into the code, may have some unnecessary code copied from previous code base.

**Comment by chianger** [comment]
Might have been fixed by https://github.com/mozilla/telemetry-streaming/pull/225

**Comment by chianger** [comment]
There might be technical limitation when we first built this.

**Comment by elin-moco** [comment]
This will depend on this ticket: https://github.com/mozilla-tw/FirefoxLite/issues/3272

**Comment by chianger** [comment]
Add to above comment, we do need #3272 to understand if this #3220 is actionable.

**Comment by mTwTm** [comment]
https://github.com/mozilla-tw/FirefoxLite/blob/86da749c2caf5fd2367601a3da62e4bcdb9c428c/app/src/main/java/org/mozilla/focus/telemetry/TelemetryWrapper.kt#L275 This is what I mean :)

**Comment by chianger** [comment]
more like a telemetry change request, let's track this as feture.
