### ISSUE TITLE
Download status won't be updated to right message? 

### ISSUE THREAD

**Issue by Jacklin-ux** [mozilla-mobile/FirefoxLite#3224]
**Describe the bug**
When downloading and turn off Wi-Fi, download status won't be updated to exclamation mark. 

**Steps To Reproduce**

**Expected behavior**

**Actual behavior**
A clear and concise description of what you actually discovered.

**Screenshots/videos**
If applicable, add screenshots/videos to help explain your problem.

**Device info (please complete the following information):**
 - Device: [e.g. Pixel3]
 - OS: [e.g. Android 9]
 - Webview [e.g. 69.0.3497.100]
 - Version [e.g. 1.1.1(10326).nightly]

**Reproduce rate**
How many times you can reproduce such issue, given the testing rounds

**Additional context**

**Comment by chianger** [comment]
This is a bug but not a feature. Leaving to triage for clarifying severity.

**Comment by chianger** [comment]
S3 as minor visual improvement.
Note that the UI updates to correct screen when user updates the UI.
