### ISSUE TITLE
Update Affiliated Game link to Top Site in India

### ISSUE THREAD

**Issue by joechengla** [mozilla-mobile/FirefoxLite#3238]
// TBD

**Comment by chianger** [comment]
To be clarified:
which topsite to be pushed out and the link as well.

**Comment by chianger** [comment]
https://games.gamezop.com/?id=Pa6YWojZa

**Comment by chianger** [comment]
landscape mode issue to be investigate.

**Comment by chianger** [comment]
see also #1231

**Comment by chianger** [comment]
back to in discussion waiting for biz deal confirmation
