### ISSUE TITLE
Geolocation does not work on LineageOS

### ISSUE THREAD

**Issue by mossroy** [mozilla-mobile/FirefoxLite#3257]
**Describe the bug**
When a website tries to geolocate the device, it always fails.

**Steps To Reproduce**
1. Go to 'https://developer.mozilla.org/en-US/docs/Web/API/Geolocation_API#Live_Result' (or any other website that uses geolocation
2. Click on "Show my location" in "Live result"
3. Accept the prompts to allow geolocation
4. See that the geolocation icon does not appear, and that geolocation is not done

**Expected behavior**
The latitude/longitude should be returned by the browser, and displayed in the webpage

**Actual behavior**
The latitude/longitude is never sent

**Device info (please complete the following information):**
 - Device: Samsung S2 and ZTE Open C
 - OS: LineageOS 14.1
 - Webview : 69.0.3497.109 and 71.0.3578.99
 - Version : 1.1.3

**Reproduce rate**
Every time

**Comment by mTwTm** [comment]
Thanks for reporting, could be a LineageOS 14.1 only issue. Tagging QAwanted.

**Comment by mossroy** [comment]
Thanks.
You might be right as I just noticed geolocation does not work either on the standard browser of the OS (based on webview too, I suppose).
I should have mentioned that geolocation works fine with Firefox 64 and 65 (more precisely Fennec F-Droid) on both devices.

**Comment by Daisy-pliu** [comment]
Can not reproduce
Test version : 1.4.0(11337)
device: samsung 8.0 webview: 74.0.3729.77
test step: [steps](https://github.com/mozilla-tw/FirefoxLite/issues/3257#issue-417749166)
video: [geolocation video](https://drive.google.com/open?id=1hOQPADnMxD33kWUyHD32Vos84eCHZJJ7)
