### ISSUE TITLE
Add a feature to save passwords

### ISSUE THREAD

**Issue by mossroy** [mozilla-mobile/FirefoxLite#3259]
**User story**
As a user of Firefox Lite, I would like that avoid having to type my login/passwords each time I have to login on a website

**Acceptance Criteria (how do I know when I’m done?)** 
1. Go to any website that requires an authentication
2. Type a login/password to login. The browser should propose to save them
3. Logout from this website (or come back later enough for the potential "remember me" cookie to be expired)
4. Got to the same website again : the browser should propose to fill the login form (or the basic authentication) with the login/password it has saved

**Additional context**
Ideally, the login/password database could be synchronized with Firefox Sync, but saving password without syncing them would already be great

**Comment by jidanni** [comment]
https://bugzilla.mozilla.org/show_bug.cgi?id=1542112

**Comment by AndhikaWB** [comment]
Sorry for necroing but I also need this feature. This is the only reason I never set Firefox Lite as my main browser. Using Android's built-in autofill is not a good solution for me since I don't really trust Google for keeping all my passwords. I think this feature should be on a higher priority.
