### ISSUE TITLE
Fix test "saveImageThenDelete_imageSaveAndDeleteSuccessfully"

### ISSUE THREAD

**Issue by Daisy-pliu** [mozilla-mobile/FirefoxLite#3264]
**Describe the bug**
On Nexus 5X (8.0) 

**Steps To Reproduce**
Test case no: TC0187
Test case name: Save image
Steps:
1. Launch Rocket and visit a website with images
2. Long press on the selected image
3. Tap on "Save image"
5. Click menu
6. Click download manager
7. Check download item matches as expected

**Expected behavior**
it can see the loaded image in download manager

**Actual behavior**
when open download manager, it does not see any image downloaded 

**BItrise Screenshots/videos**
[video](https://app.bitrise.io/build/7974d8cba46cc6ec )  
failing time in video: 10:53

**Device info**
- Emulator Nexus 5X API 26 (8.0)

**Reproduce rate**
3/10

**Comment by cnevinc** [comment]
not working on it so un-assign myself
