### ISSUE TITLE
Add a setting to forget tabs after closing

### ISSUE THREAD

**Issue by mossroy** [mozilla-mobile/FirefoxLite#3270]
**User story**
As a user with a not-powerful device (slow CPU and only 512MB of RAM), I would prefer that Firefox Lite always opens the homepage instead of restoring the tabs from last session. It would make startup faster.
Current workaround : always close all tabs before closing the browser

**Acceptance Criteria (how do I know when I’m done?)** 
1. Look for a setting to forget tabs and enable it
2. Open a few tabs with different web pages
3. Close the browser
4. Re-open the browser
5. It should open the home page, without restoring the tabs

**Comment by chianger** [comment]
I recall that we had the "UX" discussion at the very beginning of kicking off Firefox Lite.
This is a valid tradeoff, but we at the end we chose the current design.

**Comment by mTwTm** [comment]
Private Mode would be another option, however, sessions are not remembered there.
