### ISSUE TITLE
FirefoxLite can't download images from unsplash.com or any other sites

### ISSUE THREAD

**Issue by Scripterr** [mozilla-mobile/FirefoxLite#3325]
**Describe the bug**
Firefox lite cann't download the images from 'unsplash.com' or any other sites.

**Steps To Reproduce**
1. Go to `https://unsplash.com/`
2. Click on `download button` of any of the image presented. 

**Actual behavior**
Download icon shows in menu bar but no download notification in notification bar.
Clicking on download item in menu shows `unknown` item and status of the download is shown paused.
**Expected behavior**
Download starts and notification for the download shows up.

**Screenshots/videos**

**Device info :**
 - Device: [lenovo k8 note]
 - OS: [ Android 8.0.0]
 - Webview [72.0.3626.121]
 - Version [1.1.4(10373)]

**Reproduce rate**
2/2

**Additional info:**
Previously all image downloaded were named unknown with `.bin` file extension.

**Comment by mTwTm** [comment]
Thanks for the report!
I can actually download with my device with some `.bin` extension. 
Device info :
    Device: [Nokia 5.1 plus]
    OS: [ Android 9]
    Webview [72.0.3626.121]
    Version [1.1.4(10373)]

One item we're always curious about is:
Can you check if one of your internal storage or sdcard is full?

**Comment by Scripterr** [comment]
> item we're always curious about is:
Can you check if one of your internal storage or sdcard is full?

No I have enough free internal storage upto 22 Gb so it's not a problem.

**Comment by Scripterr** [comment]
Sorry accidentally closed it.

**Comment by Scripterr** [comment]
New update about the issue, so after some time later i got the download notification about download started and image being downloading.
So i tested in the mozilla reference browser which also uses android default download manager and the same problem happened.
This doesn't seems like the firefox lite's but android download manager's issue.

Should i close this issue or leave it open as images are still not correctly named with right file extension.

**Comment by chianger** [comment]
QAWanted to verify again before getting decision.

**Comment by mTwTm** [comment]
If that's the case I have experienced something similar: I guess that there are some unknown back-off behavior when there is some network issue (either sever down or unstable client network) Sometimes it back-offs so long that the download does not appear for quite a while. New downloads are not showing as well because the queue is stuffed.

**Comment by Daisy-pliu** [comment]
Test steps:
1. launch app
2. search [unsplash.com]
3. tap [download icon] on any photo

Test result: 
it is downloading file [download.bin] which is not expected as it should be a [jpg] file.
However if I download this photo from Chrome is shows downloading [emily-wilson-1458438-unsplash.jpg] which can be opened as expected.

**Comment by mTwTm** [comment]
Related to: #1201

**Comment by chianger** [comment]
requires download manager. track as feature.
