### ISSUE TITLE
User feedback: website Panproxy.com or Atozproxy.com not working 

### ISSUE THREAD

**Issue by joechengla** [mozilla-mobile/FirefoxLite#3332]
When I open website Panproxy.com or Atozproxy.com and similar websites then I was entered my Desired website which i want to open in Proxy then it wasn't open. This is a Big Bug in this Browser even CM BROWSER opened easily.

**Comment by Daisy-pliu** [comment]
Test version : 1.2.1 (10858)
**SC1 Panproxy**
1. launch app
2. search "Panproxy.com"
3. tap [FB icon] it shows FB site correctly
4 search [google.com] in search field it shows Google site correctly

**SC2 Atozproxy.com**
1. launch app
2. search "Atozproxy.com"
3. tap [Youtube icon] it shows Youtube site correctly
4 search [google.com] in search field it shows Google site correctly

Test Result:
Both proxy site can browse to target site. This issue can not be reproduced
