### ISSUE TITLE
Life feed flashes when quickly press system back key continuously

### ISSUE THREAD

**Issue by joechengla** [mozilla-mobile/FirefoxLite#3335]
1. Open Firefox Lite Life Feed
2. Quickly press system back key continuously
3. Life feed flashes

**Comment by chianger** [comment]
S2: visual enhancement

**Comment by joechengla** [comment]
https://drive.google.com/file/d/16778bBEV7pDt0sOIVD-ICYMTRGzHyf-s/view?usp=sharing

**Comment by luntik2012** [comment]
#3369
