### ISSUE TITLE
Can't open "GRABON" links by Firefox Lite (feedback from one Indian interview user)

### ISSUE THREAD

**Issue by Jacklin-ux** [mozilla-mobile/FirefoxLite#3336]
The user mentioned he clicks the link of GRABON app and open it by Firefox Lite, but open Lite's home page (or previous tab) instead of open the link page. But Focus, Fennec can open the link.

GRABON is just one use case of him, he also have the same issue on other apps.

Version [1.1.4]

**Comment by chianger** [comment]
3rd party app interaction enhancement.
