### ISSUE TITLE
User feedback: deleting files in Android Settings delete downloads too

### ISSUE THREAD

**Issue by mTwTm** [mozilla-mobile/FirefoxLite#3365]
I think there's one duplicate issue around uninstalling removes everything, this one is similar and kinda expected but impacting users in a stronger level.

> One sweet mistake and boom!!! I've always been happy with you guys. Until something disastrous happened. Your decision to put downloaded files inside Android directory, turns out to be something nightmarish. What is just happened to me? When the app size is getting quite big, I thought that it was because of the caches, and the history, and so on. So I go to device Settings and delete the app data. And boom! Everything's gone. I think this is an issue need to be considered, immediately. TY

**Comment by chianger** [comment]
QAWanted to check other browsers' behavior.

**Comment by Daisy-pliu** [comment]
**Test case**
1. launch lite
2. go to https://downloadfiletest-eab8a.firebaseapp.com/
3. long click image to save image or download any file
4. open chrome
5. search file:///sdcard/Download to check downloaded files exists
6. go to [system app] -> [FF lite] -> [clear data]
7. open chrome
8. search  file:///sdcard/Download

**Actual result/ expected result**
downloaded file exists and can be viewed

**Note**
when user tap [long screenshot icon] on FF lite and user performs clear system app data, the  screenshot will be removed.

**Comment by Daisy-pliu** [comment]
Can reproduce
**Test case**
1. launch lite with SD card installed
2. go to https://downloadfiletest-eab8a.firebaseapp.com/
3. long click image and save image or download any test file
4. open myfiles -> sdcard-> android -> media -> rocket-> downloads-> pictures -> download file exists
5. go to [system app] -> [FF lite] -> [clear data]
6. open myfiles -> sdcard-> android -> media -> rocket-> downloads-> pictures

**Actual result**
downloaded file not exists

**expected result**
downloaded file exists and can be viewed

**Video**
[video](https://drive.google.com/file/d/1P5rvTYNvz4AbVwTBdLHzvy9rVi2CbZWx/view?usp=sharing)

**Device**
samsung s7 edge 8.0|

**Comment by mTwTm** [comment]
I'm pretty sure it's fixable for internal storage as long as we're not using the DownloadManager.
@Jacklin-ux and I tried Facebook, Chrome, Meitu, and UC today and all of the images downloaded/generated to internal storage in these platforms will keep as well.

**Comment by chianger** [comment]
per above comment, to fix the behavior it requires to build a separate download manager. 
this is more like a feature.
