### ISSUE TITLE
[Smoke Test] Cache amount is inconsistent with system

### ISSUE THREAD

**Issue by Conjuror** [mozilla-mobile/FirefoxLite#337]
After browsing some websites, check App information from Android Settings.

In my example, it tells Zerda App uses 26.7 MB Cache.
Back to Zerda and press "Clear Cache". The snackbar is shown 17MB Cache was cleared.

**Comment by mTwTm** [comment]
We only clear webview cache but not the whole App cache, not sure if we need to change the implementation, though.

**Comment by NashTung** [comment]
This issue can be reproduced as Teng-pao Yu mention it.
Video:
https://drive.google.com/open?id=1NZ_eVlnK_g41LcKbsLHI4hh88XtnPYcs

Device: Redmi 4A
Rocket: 2.0.0(4168).nightly
Android: 7.1.2
Android Webview: 66.0.3359.126
