### ISSUE TITLE
Firefox Lite should support Android's password auto-fill APIs

### ISSUE THREAD

**Issue by callahad** [mozilla-mobile/FirefoxLite#3393]
**User story**

As a user of a password manager, I would like Firefox Lite to prompt me to autofill my logins on websites so that I don't have to manually copy-and-paste or transcribe my passwords.

**Acceptance Criteria (how do I know when I’m done?)** 
1. Using Bitwarden, 1Password, Firefox Lockbox, or similar: focusing a password field on a login form should offer autofill suggestions.

**Additional context**

With Firefox Lockbox now available on Android, we should support the Android Autofill APIs so that it's usable with Firefox Lite.

**Comment by mTwTm** [comment]
Thanks for filing yes this sounds like something we should triage at a higher priority now that Lockbox is out

**Comment by 3xploiton3** [comment]
And lastpass
