### ISSUE TITLE
Add goal and features to README.md

### ISSUE THREAD

**Issue by PanderMusubi** [mozilla-mobile/FirefoxLite#3396]
**User story**
As a user and develiper, I would like read the goal of this project in the readme file and also specific features and a short comparison or positioning to default of Firefox.

**Acceptance Criteria (how do I know when I’m done?)** 
1. Add goal and specific features to README.md
2. Add positioning or comparison to default Firefox and/or Fennec https://f-droid.org/en/packages/org.mozilla.fennec_fdroid/

**Comment by mTwTm** [comment]
@joechengla Feel free to edit the readme if you have more to share.
