### ISSUE TITLE
Fails to work with Just Search

### ISSUE THREAD

**Issue by ildar** [mozilla-mobile/FirefoxLite#3398]
Just Search (Simple Assist app with multiple search providers) - https://f-droid.org/app/co.pxhouse.sas
Search page simply doesn't show up in many cases if FxLite is already used. Hard to describe step by step. Someone please test and help describing.

**Comment by chianger** [comment]
@ildar can you record a video ? I really don't know how to reproduce.

**Comment by ildar** [comment]
>
>
> Now I've little more power, ready to describe ))
Case 1:
1. Open Fx Lite
2. Long tap Menu button to get Just Search bar (set as Default Assistant)
3. Type "Fx Lite"
4. Press Search on the keyboard
5. See nothing happens

**Comment by ildar** [comment]
Case 2:

> 1. Press Home to suspend Fx Lite
2. Long tap Menu button
3. Type "Fx Lite" (with space)
4. Push Search
5. See FxLite failing to open `https://duckduckgo.com?q=fx lite` (notice
missing slash)

Share what you experience in such scenarios please.

**Comment by ildar** [comment]
will a screencast help with the issue or you were able to reproduce?

**Comment by chianger** [comment]
UX issue around 3rd party app interaction.
