### ISSUE TITLE
Say on Bugzilla to go to GitHub when looking for the place to file Firefox Lite bugs

### ISSUE THREAD

**Issue by jidanni** [mozilla-mobile/FirefoxLite#3423]
Yes one does not want the common user from filling up the bug tracker with
frivolous bug reports, hence https://github.com/mozilla-tw/FirefoxLite/
is not mentioned anywhere in the app or on Google Play.

But at least on https://bugzilla.mozilla.org/enter_bug.cgi where one
sees "Firefox for Android" add a note where also to file bugs about
Firefox Lite. Thanks.

https://bugzilla.mozilla.org/show_bug.cgi?id=1542111

**Comment by mTwTm** [comment]
@joechengla Do you think it'd be a good idea to have this link provided on Google Play?
