### ISSUE TITLE
Sharing a download

### ISSUE THREAD

**Issue by manddy** [mozilla-mobile/FirefoxLite#3424]
User story
As a  user I would like to share my downloaded once it is downloaded on the browser

Acceptance Criteria 
1.Make the UI changes for adding a button button 
2.Implementing the sharing button

Screenshots
![ss3](https://user-images.githubusercontent.com/22556185/55689746-e3edd000-59a5-11e9-86bd-8fcd716012e3.jpeg)

**Comment by manddy** [comment]
@mTwTm @cnevinc  I would like to work on this feature, should I go forward with this feature?

**Comment by mTwTm** [comment]
@Jacklin-ux Can you review and comment on if we want this feature?

**Comment by mTwTm** [comment]
@manddy Feel free to start a pull request but we will need @Jacklin-ux 's decision on if we want to land this, maybe you can wait for his comment as well!

**Comment by manddy** [comment]
@mTwTm @Jacklin-ux  Should I work on this feature ? kindly guide me.
