### ISSUE TITLE
R8 and byte-level optimizations should be enabled for release builds

### ISSUE THREAD

**Issue by colintheshots** [mozilla-mobile/FirefoxLite#3456]
**User story**
As a user, I would like the released app to run faster due to optimizations. All Mozilla Android products should use R8 and byte-level ProGuard optimizations.

**Acceptance Criteria (how do I know when I’m done?)** 
Both R8 and byte-level optimizations are enabled in release builds.

**Additional context**
Switching to R8 will significantly improve release build times. https://android-developers.googleblog.com/2018/11/r8-new-code-shrinker-from-google-is.html

Enabling byte-level optimizations will improve application run times.

**Comment by mTwTm** [comment]
With #3457 we've seen that turning R8 directly on gives us a size-regression. We might want to take a look at if we can avoid that hit which will happen soon when Android Gradle Plugin 3.4 is out.

**Comment by mTwTm** [comment]
and AGP is now live on stable 😅

**Comment by mTwTm** [comment]
Resolved in AGP 3.4

**Comment by mTwTm** [comment]
Duplicate to #3502

**Comment by mTwTm** [comment]
Oh actually the byte-level optimizations part is not a duplicate and it will give us a big size shrink! @colintheshots can you send another pr with just the `'proguard-android-optimize.txt'` part once #3503 is resolved?

**Comment by chianger** [comment]
Not sure if this is still a valid ticket and requires efforts?

**Comment by mTwTm** [comment]
It has limited engineering efforts but we might want a thorough test to make sure nothing breaks. It's a ~0.2 MB size improvement if we think it's worth it.
