### ISSUE TITLE
Remove current tab then show keyboard directly (in private mode)

### ISSUE THREAD

**Issue by Jacklin-ux** [mozilla-mobile/FirefoxLite#3460]
<img width="309" alt="Screenshot 2019-04-15 at 11 15 16 AM" src="https://user-images.githubusercontent.com/22672569/56105634-cb665280-5f6f-11e9-8d4f-0c77ba521a8f.png">

Please refer to use case 4 in the ux spec: https://drive.google.com/file/d/1-hWrmCpK6wjmIg82tP9rmN9Z6o6MOft5/view

**Comment by iadeelzafar** [comment]
Working on this.

**Comment by iadeelzafar** [comment]
This is the solution that I've come up with. 
In the ```onDeletedClicked()``` method when ```ScreenNavigator.get(activity).popToHomeScreen(true)``` is called, in the ```popToHomeScreen``` method, I've added these two lines of code.
          ```InlineAutocompleteEditText urlView = (InlineAutocompleteEditText) findViewById(R.id.url_edit);```
          ```ViewUtils.showKeyboard(urlView);```

But this initialization of ```InlineAutocompleteEditText``` isn't working.
```findviewbyId cannot be found```

Please enlighten me if I'm going in the right direction or not. @Jacklin-ux  @mTwTm
