### ISSUE TITLE
Shortcut created by add to homescreen doesn't work correctly

### ISSUE THREAD

**Issue by Conjuror** [mozilla-mobile/FirefoxLite#3463]
**Describe the bug**
As title, sometimes, shortcut doesn't work correctly. Tapping on the shortcut will go to Firefox Lite home screen only.

```STR will be edited once we have a certain way to reproduce```

**Steps To Reproduce**
1. Launch Firefox Lite and go to a website
2. Tap menu and add the link to homescreen
3. Close Firefox Lite/Remove all exist pages in FirefoxLite/Relaunch Firefox Lite
4. Tap the shortcut on Homescreen
5. Repeat Step 3 & 4

**Expected behavior**
4. Firefox Lite is launched and the shortcut link is opened correctly.

**Actual behavior**
4. Firefox Lite is launched but on homescreen only.

**Screenshots/videos**
If applicable, add screenshots/videos to help explain your problem.

**Device info (please complete the following information):**
 - Device: Pixel 3
 - OS: Android 9.0
 - Webview 74.0.3729.77
 - Version 1.4.0 (11337)

**Reproduce rate**
60%

**Additional context**

**Comment by Conjuror** [comment]
**STR update:**
This is much easier for reproducing.
1. Create a shortcut by add a page to homescreen
2. Tap the shortcut created in step 1
3. Tap on menu, current pages, and tap the "X" to remove all opened pages
4. Tap on system home button
5. Tap on the shortcut created in step 1

The steps have a better way to reproduce the issue. My estimation is around 80%.

**Comment by chianger** [comment]
putting in next sprint so that we won't lose track of it.
