### ISSUE TITLE
Add remote config "version" and send to telemetry

### ISSUE THREAD

**Issue by elin-moco** [mozilla-mobile/FirefoxLite#3471]
**Describe the bug**
Lany found that life feed usage dropped around 50% since 4/11

**Steps To Reproduce**
Not clear

**Expected behavior**
Users in India can see and use life feed

**Actual behavior**
One community member reports that he can't see life feed,
another one reports that he can.
Both have send usage data enabled and updated to build 11115.

**Screenshots/videos**
Lifefeed drop since 4/11
https://console.firebase.google.com/project/zerda-dcf76/analytics/app/android:org.mozilla.rocket/events~2Freport~2Fopen__panel__lifefeed_news%3Ft=1&params=_r..eventId%253Dopen__panel__lifefeed_news%2526_r..tabIndex%253D0%2526_u..dataFilters%253Daudience%252C32%252CEQ%252CDIMENSION%252C&cs=app.m.events.detail&r=default&g=1

Firstrun push also dropped on 4/11
https://console.firebase.google.com/project/zerda-dcf76/analytics/app/android:org.mozilla.rocket/events~2Freport~2Fget__firstrun_push__null%3Ft=1&params=_r..eventId%253Dget__firstrun_push__null%2526_r..tabIndex%253D1%2526_u..dataFilters%253Daudience%252C32%252CEQ%252CDIMENSION%252C&cs=app.m.events.detail&r=default&g=1
![photo_2019-04-16_10-35-04](https://user-images.githubusercontent.com/3771202/56178069-670cc700-6033-11e9-8474-4f0f79c735da.jpg)

**Device info (please complete the following information):**
 - Device: [e.g. Pixel2]
 - OS: [e.g. Android 8.1.0]
 - Webview [e.g. 69.0.3497.100]
 - Version [e.g. 3.3.0(7183).nightly]

**Reproduce rate**
How many times you can reproduce such issue, given the testing rounds

**Additional context**

**Comment by cnevinc** [comment]
Suggestion:
Add a remote config "version" and send out the value as an important setting.
So that we can query the number of users who's is getting the latest remote config version.

Note: when updating any remote config, we should manually update this field.

**Comment by chianger** [comment]
it's not urgent according to recent data

**Comment by chianger** [comment]
Need more discussion to see how to get this done: once for all (requires telemetry arc) or one config by one.
