### ISSUE TITLE
[Bug] Different style in "No screenshots" empty view

### ISSUE THREAD

**Issue by iadeelzafar** [mozilla-mobile/FirefoxLite#3505]
**Describe the bug**
All other empty views are using a consistent style ```"@style/PanelEmptyHolderText"```. But in the ```No screenshots``` emptyview this style is not being used and thus the consistency in empty views can't be seen.

**Steps To Reproduce**
1. Go to bottom menu and select ```My shots```
2. Then select ```bookmarks```
3. Feel the difference.

**Expected behavior**
Same style should be used in all empty views.

**Actual behavior**
Same style is not being used. 

**Screenshots/videos**

No shots           |  No bookmarks
:-------------------------:|:-------------------------:
![liteA1](https://user-images.githubusercontent.com/36811908/56502932-8cb33800-652d-11e9-913b-c4a02e2cbff9.png)  |  ![liteA2](https://user-images.githubusercontent.com/36811908/56502936-8e7cfb80-652d-11e9-959a-11a6501cf3a8.png)

**Device info (please complete the following information):**
 - Device: Galaxy Nexu
 - OS: API 24

**Reproduce rate**
100%

**Comment by iadeelzafar** [comment]
Making a PR for this.

**Comment by mTwTm** [comment]
Oh thanks but we actually don't want the italic now, see #3133 can you help remove the italic in `"@style/PanelEmptyHolderText"` in this commit as well?

**Comment by iadeelzafar** [comment]
@mTwTm sure. I'll do that.
