### ISSUE TITLE
Standardize commit messages

### ISSUE THREAD

**Issue by pengrad** [mozilla-mobile/FirefoxLite#3507]
As discussed here https://github.com/mozilla-tw/FirefoxLite/issues/3162#issuecomment-485326421
I've probably chosen not best commit message and it led to manually closing of issue.
In commit history I mostly see _"Issue #... - description"_ pattern and that's what I used.

It would be great to have some kind of rules for that, and maybe use "Closes #..." as well.
Please consider to standardize it.

**Comment by mTwTm** [comment]
Yes that's something we always wanted to do. @cnevinc Let's discuss here and update the readme once we have the conclusion.
