### ISSUE TITLE
Add a download menu item 

### ISSUE THREAD

**Issue by jidanni** [mozilla-mobile/FirefoxLite#3525]
I was trying to download a file, when I discovered there's just no download button at all.

For instance, try to download a few KML files from https://www.jidanni.org/sitemap.html , (and then import them into the Google Earth application.)
I had to use chrome to do it.

**Comment by jidanni** [comment]
See also https://bugzilla.mozilla.org/show_bug.cgi?id=1546274#c2

**Comment by chianger** [comment]
Not quite sure I understand this issue fully. 
Firefox Lite can actually download the KML file, and there is a panel by tapping " menu > Downloads" to look for what had been downloaded.

I guess, is this issue more for offline use case like #2467  ?

**Comment by jidanni** [comment]
It turns out that one needs just a short tap to download. However one would always think that would be on the long press menu. So even though you might think it's wasteful duplication, please also put it in the long press menu. Thank you.

**Comment by jidanni** [comment]
Short tapping on a .kml downloads it.
But short tapping on a .conf opens it, with no way to download!

**Comment by chianger** [comment]
It's a feature then. Current behavior is by design.
