### ISSUE TITLE
[dogfooding] search bar on home screen should be able to close by back key

### ISSUE THREAD

**Issue by Conjuror** [mozilla-mobile/FirefoxLite#353]
click search bar on home page then press back key directly, suggest to close search mode

**Comment by Conjuror** [comment]
When search bar is empty, back key should dismiss keyboard directly.

**Comment by NashTung** [comment]
This issue can be reproduced.
Video:
https://drive.google.com/open?id=16hUGEYdK4tvSE03eb6s-VQ0oYkjnOvUP

Device: Redmi 4A
Rocket: 2.0.0(4168).nightly
Android: 7.1.2
Android Webview: 66.0.3359.126
