### ISSUE TITLE
Can't find in page for certain page

### ISSUE THREAD

**Issue by mTwTm** [mozilla-mobile/FirefoxLite#3557]
**Describe the bug**

**Steps To Reproduce**
1. Visit `https://developer.android.com/ndk/guides/abis`
2. Click on 'Search in Page'

**Expected behavior**
User can search

**Actual behavior**
The search bar shows and disappears

**Screenshots/videos**

**Device info (please complete the following information):**
 - Device: Nokia 5.1 plus
 - OS: 9.0
 - Webview 74.0.3729.136
 - Version 1.5.1(11790)

**Reproduce rate**
5/5

**Comment by chianger** [comment]
I can reproduce in android 8 too
