### ISSUE TITLE
Bukalapa affiliate links response 403 error

### ISSUE THREAD

**Issue by Daisy-pliu** [mozilla-mobile/FirefoxLite#3559]
**Describe the bug**

**Steps To Reproduce**
1. VPN in indo
2. life feed is enabled for indo on remote config on production
3. swipe up
4. tap any link provided by Bukalapa

**Expected behavior**
open a new tab and see correct  Bukalapa page

**Actual behavior**
open a new tab and see noting as it response 403

**Screenshots/videos**
[slack thread](https://mozilla.slack.com/archives/G5QBPEK4J/p1557140954019100)

**Device info (please complete the following information):**
all
 
**Verison**
RC 1.5.1 , 1.4.0 (any version with indo life feed feature)

**Reproduce rate**
5/5

**Comment by weslyhuang** [comment]
per standup discussion, there might be a potential service stability issue (?) as @elin-moco has observed similar things recently. For longer-term we may want to take further actions like:

1. monitor & record the service stability (manually, or even setup automatic mechanism to regularly check it for trend)
2. get BD/Product's involvement for next step

We may use this one for followup in grooming, or open a separate ticket if preferred.

**Comment by chianger** [comment]
Root cause is that our monitoring service was considered suspicious and banned by their backend, so that the monitoring has to stop.
No actionable item at this moment.
