### ISSUE TITLE
Sudden rotation from protrait to landscape when open link in screenshot viewer

### ISSUE THREAD

**Issue by Daisy-pliu** [mozilla-mobile/FirefoxLite#3579]
**Describe the bug**
Sudden rotation from protrait to landscape when open link in screenshot viewer

**Steps To Reproduce**
1. launch app
2. on portrait mode
3. take screenshot
4.  tap [menu]-> [myshots]
5. click any shot
6. rotate to landscape
7. tap [link] button

**Result:**
user see suddenly page rotate to portrait and then landscape mode

**expectation:**
see the link is opened in landscape mode 

**Device info (please complete the following information):**
 - Device: Pixel 2 (9.0)

**Reproduce rate**
5/5

**Slack**
[slack discussion](https://mozilla.slack.com/archives/G5QBPEK4J/p1557473165166100)

**Video**
[video on Slack](https://mozilla.slack.com/archives/G5QBPEK4J/p1557473141165600)
 
Note : not happen on Vivo 6.0.1

**Comment by chianger** [comment]
Function still working so this is UX enhancement

**Comment by Daisy-pliu** [comment]
Happen on Redmi 4X (7.1.2)
