### ISSUE TITLE
Quick search with Buka failed

### ISSUE THREAD

**Issue by Daisy-pliu** [mozilla-mobile/FirefoxLite#3582]
**Steps To Reproduce**
1. insert indo sim card
2. tap [search field]
3. input text [red skirt]
4. tap [buka] icon

**Expected behavior**
search red skirt result in Buka site

**Actual behavior**
search result failed with 403

**Device info (please complete the following information):**
all

**Reproduce rate**
4/4

**Additional context**
partner API service not stable

**Comment by chianger** [comment]
at least we'll figure the root cause out.

**Comment by Daisy-pliu** [comment]
Now Buka is back to service. I will report this issue to our partner.
