### ISSUE TITLE
Can not download after kill and relaunch  (Android 6 )

### ISSUE THREAD

**Issue by Daisy-pliu** [mozilla-mobile/FirefoxLite#3598]
**Steps To Reproduce**
1. launch app
2. go to site : https://downloadfiletest-eab8a.firebaseapp.com/ (or https://www.w3schools.com/howto/tryit.asp?filename=tryhow_html_download_link)
3. tap to download [pdf file] (or on https://www.w3schools.com/howto/tryit.asp?filename=tryhow_html_download_link  tap image to download)
4. kill app & relaunch
5. go to site : https://downloadfiletest-eab8a.firebaseapp.com/ (or on https://www.w3schools.com/howto/tryit.asp?filename=tryhow_html_download_link  tap image to download)
6. tap to download [pdf file]

**Expected behavior**
download pdf file successfully

**Actual behavior**
can not download ,it does nothing

**Device info (please complete the following information):**
 - Device: Vivo 6.0.1
 - Version : 1.6.0 (12105), 1.4.0 (11336)

**Reproduce rate**
5/5

**Log**
[Vivo (6.0.1) download failed log](https://docs.google.com/document/d/1SiarKabQXM-beqC1OS4Hd40ONYYywURLXTEtaQKPbXg/edit?usp=sharing)

**Additional context**
Not sure all Android 6.0 get this issue as we only have 1 Android 6 test device
Not happen on Pixel 2 (9.0) ,Samsung S7 edge (8.0)

**Comment by chianger** [comment]
QAWanted to check emulator android 6.0

**Comment by Daisy-pliu** [comment]
On emulator Nexus 5X API23 (6.0), Nexus 6 API 23  (6.0) after user click download link it does nothing even in the first time launch.
On emulator Nexus 5X API 26 (8.0), Pixel 2 API 28(9.0) It does not have such download issue.

**Comment by Daisy-pliu** [comment]
This is a webview issue that on Android 6.0, certain HTML download format can lead to download not responding.

Android 6 with older webview, user can not download it with below format
```
<a href="./downloads/files/5MB.zip" download="5MB.zip">
    <p>Tap to download 5MB file (not support Andorid 6.0)</p>
</a>
```
Android 6 with older webview user can download it with below format
```
<a href="./downloads/files/10MB.zip">
  <p>Tap to download 10MB file</p>
</a>
```

**Comment by chianger** [comment]
The scope doesn't seem to be fully clarified yet. I heard there might be something to do with webview version but also heard that reproducible with recent webview.

**Comment by chianger** [comment]
qawanted to check UC mini (and other webview based browsers) with the same webview.

**Comment by Daisy-pliu** [comment]
will try on UCmini browser

**Comment by Daisy-pliu** [comment]
UC mini works on Vivo with same webview version and site

**Comment by chianger** [comment]
S1 P2 given the information we have. 
Action item no clear
