### ISSUE TITLE
Push notification to add private mode shortcut

### ISSUE THREAD

**Issue by Jacklin-ux** [mozilla-mobile/FirefoxLite#3637]

**Comment by Jacklin-ux** [comment]
UX spec: https://drive.google.com/file/d/1p33EtI3MjM1zBqYba19kF2qCmVwdi6kr/view?usp=sharing
(Please refer to use case 4)

**Comment by chianger** [comment]
Scope: requires to support firebase config to trigger the push notification

**Comment by TLHuang** [comment]
The visual for adding shortcut dialog is updated, please find the visual spec here https://zpl.io/bo8OygW
