### ISSUE TITLE
vivio 1606 (6.1.1) can not add to home screen

### ISSUE THREAD

**Issue by Daisy-pliu** [mozilla-mobile/FirefoxLite#3674]
**Steps To Reproduce**
1. launch app
2. tap any topsite
3. tap [setting]-> [add to home screen]

**Expected behavior**
site is added to home screen

**Actual behavior**
no site is added to home screen

**Device info (please complete the following information):**
 - Device: vivo 6.1.1 

**Reproduce rate**
5/5

**Additional context**
Note: this issue happens on Opera and Firefox browser app

**Comment by Daisy-pliu** [comment]
probably related to below
https://github.com/mozilla-tw/FirefoxLite/issues/2057 (edited) 
https://github.com/mozilla-tw/FirefoxLite/issues/2714 (edited) 
https://github.com/mozilla-tw/FirefoxLite/issues/3463

**Comment by chianger** [comment]
function break but probably due to device itself. not easy actionable from firefox lite client side.
