### ISSUE TITLE
[dogfooding] popup menu keeps on home screen after switching app

### ISSUE THREAD

**Issue by Conjuror** [mozilla-mobile/FirefoxLite#368]
1. long press on top site and see the REMOVE button; 2. system task switch back and forth.  => the "remove" icon shows on the top-left corner

build 461

**Comment by mTwTm** [comment]
Step:

    Launch Rocket
    Touch and hold any top site to bring up "Remove" button
    Tap Android's Home Key
    Go back to Rocket

Actual Result:

    The Remove button is in the upper-left corner
    Video: https://youtu.be/BLLXkOj9PUk
    This issue can be reproduced on Redmi 4A and Sony Z3C.
    This issue cannot be reproduced on Google Pixel.

Expected Result:

    The Remove button is not in the upper-left corner

Reproduction rate: 10/10
Rocket version: 1.0.1710

======================================
Device name: Redmi 4A
Android version: 6.0.1 MMB29M

Device name: Sony Z3C
Android version: 5.0.2 MMB29M

**Comment by NashTung** [comment]
This issue can be reproduced.
Video:
https://drive.google.com/open?id=1VywLhTlV63WIqCqi1j5enjy6811Z8gDG

Device: Redmi 4A
Rocket: 2.0.0(4168).nightly
Android: 7.1.2
Android Webview: 66.0.3359.126
