### ISSUE TITLE
Can not show private mode set as default 

### ISSUE THREAD

**Issue by Daisy-pliu** [mozilla-mobile/FirefoxLite#3680]
**Steps To Reproduce**
1. launch lite -> tap [setting]-> [add private mode shortcut to home screen]
2. launch playstore
3. tap link on playstore 
4. open [FFlite private browsing] app and choose [always]
5. back to playstore
6. open same link
7. go to [settings] -> [more]-> [default apps]
 

**Expected behavior**
6. it will default open with private mode
7. it shows [FFLite private mode] is default browser app

**Actual behavior**
6. it will default open with private mode
7. it shows [FFLite] is default browser app

**Screenshots/videos**
If applicable, add screenshots/videos to help explain your problem.

**Device info (please complete the following information):**
 - Samsung 8.0
 - pixel 9.0
 - nexus 6.0.1 

Note : on Vivo 6.1.1 this issue not happened
**Reproduce rate**
8/8

**Additional context**
@Jacklin-ux  I am not sure we will enhance it or not ?

**Comment by chianger** [comment]
technical limitation for android 6.0+
Non actionable unless we implement other UX flow to enhance it.

**Comment by sblatz** [comment]
We're considering adding this feature in Fenix and also noticed this issue. We are considering this as a solution: https://github.com/mozilla-mobile/fenix/pull/5721/files#diff-842c3d4ac654e221b378bcb5855d8cc1R47-R57

Essentially we have a toggle in settings that flips on when the "always" button is pressed. 

<img width="350" alt="image" src="https://user-images.githubusercontent.com/4400286/66002322-4953e280-e458-11e9-98d0-7de22f2aff73.png">

@chianger would that work for Lite too?
