### ISSUE TITLE
[Regression] Italic strings on tabs is truncated

### ISSUE THREAD

**Issue by Conjuror** [mozilla-mobile/FirefoxLite#3693]
**Describe the bug**
"No browsing history", "No downloads", and "No bookmarks" are truncated on the newest build.

**Steps To Reproduce**
1. Launch Firefox Lite
2. Click on Menu
3. Tap on bookmark/download/history
4. observe the strings

**Expected behavior**

**Actual behavior**
A clear and concise description of what you actually discovered.

**Screenshots/videos**
If applicable, add screenshots/videos to help explain your problem.

**Device info (please complete the following information):**
 - Device: Oppo
 - OS: 7.1.1
 - Webview 75.0.3770.89
 - Version 1.7.0(12757)

**Reproduce rate**
How many times you can reproduce such issue, given the testing rounds

**Additional context**

**Comment by Conjuror** [comment]
![Screenshot_2019-06-13-15-13-30-08](https://user-images.githubusercontent.com/1625148/59411989-1a552a80-8def-11e9-8926-c9420be4520c.png)
![Screenshot_2019-06-13-15-13-34-16](https://user-images.githubusercontent.com/1625148/59411990-1a552a80-8def-11e9-98d8-65890c8e8725.png)
![Screenshot_2019-06-13-15-13-41-72](https://user-images.githubusercontent.com/1625148/59411992-1aedc100-8def-11e9-9f45-01a82b1a344d.png)

**Comment by Conjuror** [comment]
The issue wasn't there in last release.
https://drive.google.com/drive/u/1/folders/1pMGzdOfdOvfcv8kORbRgQuiHKY4NEgrD

**Comment by Daisy-pliu** [comment]
Not happened on Samsung 8.0 , Redmi 4X (7.1.2) . 
This issue maybe device specific issue so it will not block release.
