### ISSUE TITLE
Remove obsolete string resources around private_browsing_dialog_shortcut

### ISSUE THREAD

**Issue by chianger** [mozilla-mobile/FirefoxLite#3697]
After #3696 merged, we have below strings obsolete: 
string name="private_browsing_dialog_add_shortcut_title"
string name="private_browsing_dialog_add_shortcut_content"
string name="private_browsing_dialog_add_shortcut_no"
string name="private_browsing_dialog_add_shortcut_yes"

**Comment by Conjuror** [comment]
follow up for issue #3696
