### ISSUE TITLE
Cant show Hindi in news feed lang after set app settings to Hindi

### ISSUE THREAD

**Issue by Daisy-pliu** [mozilla-mobile/FirefoxLite#3703]
**Describe the bug**
Described in the spec: 
When open Life feed the first time then check Lite’slanguage (just check one time). If using “Hindi” then setnews language as “Hindi”, otherwise set as “English”

**Steps To Reproduce**
1. fresh install Lite
2. skip onboardings 
3. tap [settings]-> [language] -> [hindi]
4. tap system back
5. swipe [up] to see life feed 
6. tap [settings] 

**Expected behavior**
should see [Hindi] as language 

**Actual behavior**
see [english] as language 

**Screenshots/videos**
[slack video ](https://mozilla.slack.com/archives/G5QBPEK4J/p1560887053009000)

**Device info (please complete the following information):**
 Redmi 4X 7.1.2

**Verison**
RC1.8.0(12867)

**Reproduce rate**
4/4

**Additional context**
@Jacklin-ux please help on verification

**Comment by Daisy-pliu** [comment]
confirm with @Jacklin-ux  this is not a blocker.

**Comment by chianger** [comment]
is it dup of #3738 ?

**Comment by Daisy-pliu** [comment]
no, #3738 is about layout text lang (like categories: top news,sports..) while #3703 is about news lang

**Comment by chianger** [comment]
Flow to enhance but since changing locale doens't happen that often. P2
