### ISSUE TITLE
Glean evaluation

### ISSUE THREAD

**Issue by cnevinc** [mozilla-mobile/FirefoxLite#3713]
Here are the minutes with EM BI team, Data Engineering team, IT, and me at Whistler All Hands.

Glean is the new Telemetry library in Android-components.
All future updates will be in that.

## Benefit:  
- Auto document generation
- Auto Amplitude integration 
- Metrics/Histogram support ( no need to update core ping schema any more)
- Align session-time calculation among other mobile products.
- DebugView to debug data pipeline in Production mode ( to see if data collection works as expected)
- See more [here](https://docs.telemetry.mozilla.org/concepts/glean/glean.html#what-does-it-offer)

Here are some documents:
https://docs.telemetry.mozilla.org/concepts/glean/glean.html
https://mozilla.github.io/glean/book/index.html

## APK size Impact
- The new library will increase the APK size for 0.3 MB in a release build. But I think it should be fine cause we'll also retire the old Telemetry library.
![image](https://user-images.githubusercontent.com/1287363/59888100-dfb53a00-937a-11e9-81f8-1aa4641c5938.png)

## Data migration 
After using Glean, the data will go to different tables, too. Here are some data migration we talked about in the meeting with the data engineering team:
 - Telemetry data: We can join the old tables with views.  So it should be fine.
 - Amplitude data: We might need to create a new Amplitude project and lost the old data there. But If we can ask the Amplitude consultant to find out other migration solution(e.g. keeping the old client ID), then it should be fine.

**Comment by cnevinc** [comment]
# meeting minutes 9/18
## Conclusion:
Using Glean is a must cause old telemetry system will be depreciated soon.
## Action Items:
### Engineering
Currently, there is no action item from the engineering side
### BI
Figure out the features that the BI team will use, the impact of current data flow design, how to work with our application backend, data migration plan (Amplitude, Telemetry), and design for future machine learning pipeline?

**Comment by joechengla** [comment]
Meeting with Allesio on Sept 20, 2019

Rampdown schedule?   
The Glean SDK can be adopted by products at their leisure. Moving forward, the Glean SDK will be the only available option. service-telemetry is deprecated, but we won't be removing it until all products are migrated



Glean written from day 0 to support Kotlin (works best with Kotlin, Java may need some fix)
Is FxLite written in Java or Kotlin? 



How to send, what to send, what goes into which metric, high level metric type https://mozilla.github.io/glean/book/user/metrics/index.html



What products has adopted ?
Fenix, FireTV, Fx Reality, lib-crash of android components




可以幫我問其他產品轉換到glean花了多久  https://github.com/mozilla-mobile/firefox-tv/pull/2158/files#diff-1e8cc461a266ee4c7567864cb3b35b62
	FireTV had service-telemtry + glean at the same time 
	Data in 2 tables <— Frank / Michael Camela 
	FireTV may keep 2 tables separate 
	FxReality - TBD

	Gecko is already integrated with Glean. Huge plus if we use Gecko
	


舊telemetry跟amplitude 的轉移，
	Amplitude data migration issue - Frank question 



跟data steward review一定要透過bugzilla嗎？
	Yes, Glean has baseline data collection. 
	Yes, for new telemetry, the usual process. There is a lib-crash sample https://github.com/mozilla-mobile/android-components/blob/master/components/lib/crash/metrics.yaml   need to go thru this or else glean will fail at build time 	<— Sebstian 



有沒有API 可以拿user 的 glean user id
	Glean SDK has client ID. But doesn’t expose it to the customer of SDK (due to privacy)
	


SDK是否跟telemetry一樣是Singleton,
	There is a singleton. Just need to call glean.initialize. Glean register lifecycles (glean takes care of the rest) 



Client 可否統計總共送出多少kb的event
	Not quite	
	Can get some info Glean.debug.viewer https://docs.telemetry.mozilla.org/concepts/glean/debug_ping_view.html
	https://debug-ping-preview.firebaseapp.com/
	Can work with us to design something (throttling. e.g)	

Baseline ping
{"metrics":{"string":{"glean.baseline.locale":"en-US"},"timespan":{"glean.baseline.duration":{"time_unit":"second","value":3}}},"ping_info":{"ping_type":"baseline","experiments":{"fenix-test-2019-08-05":{"branch":"b"}},"seq":9,"start_time":"2019-09-14T05:52+03:00","end_time":"2019-09-14T05:52+03:00"},"client_info":{"telemetry_sdk_build":"12.0.0","first_run_date":"2019-09-14+03:00","os":"Android","android_sdk_version":"28","os_version":"9","device_manufacturer":"samsung","device_model":"SM-T515","architecture":"armeabi-v7a","app_channel":"release","app_build":"12550444","app_display_version":"2.0.0-rc.2","client_id":"103234fe-db13-4c72-b352-1395aed9fdf0"}}



Glean works with SoftVision QA - https://debug-ping-preview.firebaseapp.com/
Provide API to write unit test  https://mozilla.github.io/glean/book/user/testing-metrics.html


Allasio can create a migration template
Allasio will ask Frank about a single view for new/old data

**Comment by Dexterp37** [comment]
The Glean team has put together a [migration checklist document](https://docs.google.com/document/d/1k7GabrWCDKp7Ae8mqr-XFnFxIuNlxsJM52D-1uVmgb0/edit?ts=5d8aadbd) in order to help products migrating from service-telemetry to the Glean SDK.

The document also outlines a mechanism to estimate the efforts required for the migration. Please do reach out if more information is needed.
