### ISSUE TITLE
Click i on blocked trackers' number to show its SUMO page

### ISSUE THREAD

**Issue by Jacklin-ux** [mozilla-mobile/FirefoxLite#3720]
**User story**
As a user, I would like to see trackers' SUMO page because I don't really understand ads trackers and why "blocked trackers" benefits to me.

**Acceptance Criteria (how do I know when I’m done?)** 
1.
2.
3.

**Additional context**

**Comment by chianger** [comment]
We potentially need separate SUMO page for this
