### ISSUE TITLE
[Crash] HttpURLConnectionClient.kt linw 56

### ISSUE THREAD

**Issue by Daisy-pliu** [mozilla-mobile/FirefoxLite#3730]
**Describe the bug**
HttpURLConnectionClient.kt line 56 -> https://console.firebase.google.com/u/0/project/zerda-dcf76/crashlytics/app/android:org.mozilla.rocket/issues/1dc971fe8bb9775583ceae279ef5825f?time=last-seven-days&sessionId=5D11749201CE000122165B6D82B87C9B_DNE_0_v2

**Additional comment**
only happens on 1.8.0 due to Android component issue

**Comment by chianger** [comment]
potential blocker for 1.8.0

**Comment by Conjuror** [comment]
for monitoring
