### ISSUE TITLE
Settings button on news feed page should be with animation when tapped

### ISSUE THREAD

**Issue by Conjuror** [mozilla-mobile/FirefoxLite#3739]
**Describe the bug**
As title, the Settings icon on news feed page should be with animation when tapped

**Steps To Reproduce**
1. Launch Firefox Lite
2. Slide up from the bottom to launch NewsFeed
3. Tap on the Settings icon on the upper-right and observe

**Expected behavior**
3. An animation as tapped and then settings page is shown 

**Actual behavior**
3. No animation for the settings button

**Screenshots/videos**
If applicable, add screenshots/videos to help explain your problem.

**Device info (please complete the following information):**
 - Version 1.8.0(13000)

**Reproduce rate**
How many times you can reproduce such issue, given the testing rounds

**Additional context**

**Comment by chianger** [comment]
no button ripple effect.
