### ISSUE TITLE
Unexpected redirection when visiting review pages of CNET.com in Private Mode

### ISSUE THREAD

**Issue by StellaTseng** [mozilla-mobile/FirefoxLite#3741]
Unexpected redirection when visiting review pages of CNET.com in "Private Mode" :  https://www.cnet.com/reviews/sony-wh-xb900n-extra-bass-review/

No able to reproduce by using Normal Mode. 

Thank you!

**Comment by Daisy-pliu** [comment]
It is suddenly redirect to cnet:///reviews/reviews/sony-wh-xb900n-extra-bass-review/?link_click_id=674060355655490535. 
but I did not see this crash in crashlytics 
version : 1.8.0 (12883)
Test device: Samsung 8.0, Redmi 7.0
Video:  [video](https://drive.google.com/file/d/1zY8pPt6R-FRSzJqcjjLoUBkeCrpQz7-7/view?usp=sharing)

**Comment by Daisy-pliu** [comment]
It is suddenly redirect to cnet:///reviews/reviews/sony-wh-xb900n-extra-bass-review/?link_click_id=674060355655490535. 
but I did not see this crash in crashlytics 
version : 1.8.0 (12883)
Test device: Samsung 8.0, Redmi 7.0
Video:  [video](https://drive.google.com/file/d/1zY8pPt6R-FRSzJqcjjLoUBkeCrpQz7-7/view?usp=sharing)
