### ISSUE TITLE
Track the APK size footprint for each PR / feature

### ISSUE THREAD

**Issue by cnevinc** [mozilla-mobile/FirefoxLite#3752]
**User story**
As a developer, I would like to track the APK size impact by each pull request.

As we'll soon over 4 MB in a short period of time, and size seems to be very important for us, we should do it asap.

Every commit/merge will impact the APK size. Weather increase or decrease.
I'd like a tool to trace the footprint of any PR.

**Acceptance Criteria (how do I know when I’m done?)** 
 We can have a chart and see the APK size history for each feature/PR

**Comment by Conjuror** [comment]
Adding label with RelMgt/RelEng. We should be able to track the status of APK size. To be specific, we'd like to track the size of "app-signed.aab". Is that correct? @cnevinc
