### ISSUE TITLE
Site origin info for downloaded file

### ISSUE THREAD

**Issue by joechengla** [mozilla-mobile/FirefoxLite#3774]
https://play.google.com/apps/publish?account=7083182635971239206#BetaFeedbackDetailsPlace:p=org.mozilla.rocket&feedbackid=gp:AOqpTOG8BHK30oILpnpmvyQm1iYI8e33ARp3KqSVluspg7TK6lPKT8607MrDwSR-cbIyNBOukq_-mdNt2YtY-RpA6w

**Comment by shubhamkumar1739** [comment]
Can I work on this?
