### ISSUE TITLE
User feedback: Video Fullscreen

### ISSUE THREAD

**Issue by joechengla** [mozilla-mobile/FirefoxLite#3788]
The news and feed section is very good and bug free but i am still experiencing problem in streaming youtube videos as when i go fulscreen it always stays in portrait mode which is very common feature in other browser. I suggest to fix this problem so when video is switched to full screen it should be in landscape mode even if the auto rotation is turned off.
https://play.google.com/apps/publish?account=7083182635971239206#BetaFeedbackDetailsPlace:p=org.mozilla.rocket&feedbackid=gp:AOqpTOFezKJ6ENeEN-7mDonjF6fRsYpjGdhHhWY1nFSIiEEMb3uysS8Ektd-PeV_my7zBvuHRWvgrB5u35D-LX9bOw

**Comment by chianger** [comment]
test comment
