### ISSUE TITLE
All toolbar icons disabled when Application recreated

### ISSUE THREAD

**Issue by mTwTm** [mozilla-mobile/FirefoxLite#3789]
**Describe the bug**
See screenshots

**Steps To Reproduce**
1. Open any page
2. Try to get the process killed by opening a lot of Apps (or, try: https://github.com/derekwilson/RamEater)
3. Re-launch Lite via recent apps (Not sure if reproducible via launcher icon)

**Expected behavior**
Most of the icons, at least reload should be available

**Actual behavior**
All icons are disabled

**Screenshots/videos**
![Screenshot_20190726-190042](https://user-images.githubusercontent.com/6755074/61944792-778cf000-afd9-11e9-93fa-dcf76e9cfd07.png)

**Device info (please complete the following information):**
 - Device: Nokia 5.1 plus
 - OS: Android 9
 - Webview 75.0.3770.143
 - Version 1.9.1(13361)

**Reproduce rate**
10/10

**Additional context**

**Comment by joechengla** [comment]
+1, I'm encountering this quite a bit these days too but I haven't found how to reproduce it 

Thanks Tyu :)

**Comment by joechengla** [comment]
Encountered again with 1.9.1(13691).nightly
