### ISSUE TITLE
[Question] Why is FirefoxLite not updated in F-droid since v1.4.0 ?

### ISSUE THREAD

**Issue by sebma** [mozilla-mobile/FirefoxLite#3822]
**Question**
[Question] Why is [FirefoxLite not updated in F-droid since v1.4.0](https://f-droid.org/en/packages/org.mozilla.rocket/) ?

**Device info (please complete the following information):**
 - Device: Galaxy Note 3
 - OS: Android: 5.0
 - Webview: No idea of how to find it on Android5 (My UA says Chrome/37.0.0.0)
 - Version: 1.4.0

**Comment by articlecat** [comment]
Yes, Firefox Lite should be updated to the latest version.

**Comment by Iey4iej3** [comment]
This issue could be merged with https://github.com/mozilla-tw/FirefoxLite/issues/3827

**Comment by Bubu** [comment]
See https://github.com/mozilla-tw/FirefoxLite/issues/3827#issuecomment-574892773
