### ISSUE TITLE
FDroid

### ISSUE THREAD

**Issue by userkilled** [mozilla-mobile/FirefoxLite#3827]
Why aren't there new FF Lite releases in FDroid?

**Comment by 3xploiton3** [comment]
Firefox Lite (Fast and Lightweight Web Browser) - https://f-droid.org/app/org.mozilla.rocket

**Comment by userkilled** [comment]
When will the new versions be?  They do not match.

**Comment by Iey4iej3** [comment]
Reference: https://gitlab.com/fdroid/rfp/issues/786

**Comment by Iey4iej3** [comment]
Developers for F-Droid failed to build it without Firebase. See [here](https://gitlab.com/fdroid/fdroiddata/issues/1668#note_183228500) for details.

**Comment by Bubu** [comment]
We are about to remove the app from f-droid as we cannot build any newer versions: https://gitlab.com/fdroid/fdroiddata/merge_requests/6194
