### ISSUE TITLE
News UI revamp with multimedia contents (for IN&ID)

### ISSUE THREAD

**Issue by joechengla** [mozilla-mobile/FirefoxLite#3901]

**Comment by weslyhuang** [comment]
need to check feasibility with Dev before moving to "ready for Dev".

**Comment by weslyhuang** [comment]
still in UX design, add the "feature" label so be excluded from daily launch-blocker(P0) scanning.

**Comment by chianger** [comment]
Jack had discussed the spec with benjamin/nevin weeks ago. 
Still need metrics.
