### ISSUE TITLE
Display a snackbar with redeem action when user killed activity when redeeming voucher

### ISSUE THREAD

**Issue by harly21** [mozilla-mobile/FirefoxLite#3906]
**Describe the bug**
Display a snackbar with redeem action when user killed activity when redeeming voucher

**Steps To Reproduce**
1. Go to reward page and press gift
2. Press the redeem button
3. kill the activity and restart Firefox lite

**Expected behavior**
Display a snack bar with redeem button

<img width="1213" alt="Screen Shot 2019-10-28 at 5 00 41 PM" src="https://user-images.githubusercontent.com/5945418/67670954-f403e600-f9af-11e9-96f3-a8a790ca5f99.png">

**Comment by Mozillove** [comment]
After discussing with developer, it's an edge case for now. Remove this issue from this sprint and will keep monitoring it. Thanks.
