### ISSUE TITLE
[BugBash] [Feature request] Shopping Search button on Firefox Lite's Home should have an indicator hinting users about whether they already have a search results or not.

### ISSUE THREAD

**Issue by Conjuror** [mozilla-mobile/FirefoxLite#3908]
[Feature request] Shopping Search button on Firefox Lite's Home should have an indicator hinting users about whether they already have a search results or not.

**Comment by benjamin-cheng** [comment]
@FinnickC could you help to provide the indicator asset? Thank you!

**Comment by FinnickC** [comment]
https://zpl.io/V0pX9v9
