### ISSUE TITLE
Content home is not applied in Night Mode

### ISSUE THREAD

**Issue by Conjuror** [mozilla-mobile/FirefoxLite#3910]
**Describe the bug**
as title, content tab (vertical home) doesn't apply with Night Mode.

**Steps To Reproduce**
1. Launch Firefox Lite and enable Night Mode
2. Tap [News]
3. Tap on a news

**Expected behavior**
1. Brightness of screen is aligned with Night Mode settings
2. Brightness of screen is aligned with Night Mode settings
3. Brightness of screen is aligned with Night Mode settings

**Actual behavior**
1. Brightness of screen is aligned with Night Mode settings
2. Brightness is the same as phone settings
3. Brightness of screen is aligned with Night Mode settings

**Device info (please complete the following information):**
- Build (15951)

**Reproduce rate**
5/5

**Additional context**

**Comment by benjamin-cheng** [comment]
@FinnickC  could you please help to provide the visual SPEC on Zeplin? Thank you!

**Comment by FinnickC** [comment]
UI Spec
https://zpl.io/2jYgBZq
