### ISSUE TITLE
[BugBash]Content home support Block image

### ISSUE THREAD

**Issue by Daisy-pliu** [mozilla-mobile/FirefoxLite#3944]
**Describe the bug**
When enable Block image, the images in content home should be blocked.

**Steps To Reproduce**

**Expected behavior**

**Actual behavior**

**Screenshots/videos**

**Device info (please complete the following information):**
 - Version 16060

**Reproduce rate**

**Additional context**
@Jacklin-ux  could you let us know your expectation? is it a feature request?

**Comment by Jacklin-ux** [comment]
My expectation is as I mentioned-> When enable Block image, the images in content home of all verticals should be blocked. It's a feature request.
