### ISSUE TITLE
Deep link to install Firefox Lite

### ISSUE THREAD

**Issue by Daisy-pliu** [mozilla-mobile/FirefoxLite#3967]
**Describe the feature**
Share Game
I’m playing a really cool game. Check it out!
https://www.gamezop.com/g/N1sZfO1fWqg?id=j8YuvGCo5
there's some branding opportunities here to mention Firefox Lite and drive installs

**Feature suggestion:** 
Deep link to install Firefox Lite first and then once installed, use Firefox Lite to open the game link to play directly 

**Additional**
bug bash feature suggestion from @joechengla

**Comment by weslyhuang** [comment]
@Mozillove just to confirm, do you want bring this to grooming? then set it P0 if yes. thanks!

**Comment by Mozillove** [comment]
@weslyhuang Yes, I'd like to bring this to feature grooming. However, there are other higher-priority issues so I changed it to P0. Is it a good idea if I remove it from the project for now? thanks.
