### ISSUE TITLE
In "Find in page" mode ,tap mini url bar but search field doesn't display.

### ISSUE THREAD

**Issue by Jack-king-1** [mozilla-mobile/FirefoxLite#3970]
**Describe the bug**
In "Find in page" mode ,tap mini url bar but search field doesn't display.

**Steps To Reproduce**
1. Go to any website.
2. Click menu
3. Tap "Find in page" and don't close keyboard.
4. Tap mini url

**Reproduce rate**
5/5
**Additional context**
All of devices and Android version have this issue.

**Comment by Conjuror** [comment]
Disable TC0150 since it continuously failed the case.
