### ISSUE TITLE
Video Ads on Darts FRVR do not play

### ISSUE THREAD

**Issue by joechengla** [mozilla-mobile/FirefoxLite#3976]
build 16663 
https://drive.google.com/file/d/1Xr5FzxiB5pMOAjaaJn6InTY8-sfbjiuS/view?usp=sharing
1. Play Darts FRVR
2. Play for a while and you may be asked to view video ads
3. Accept to view video ads

What I observed:
Firefox Lite shows black screen (as attached image)
Firefox preview shows black screen
Chrome doesn't play video either and directly show thank you and closes itself 

will this impact our revenue?

**Comment by Mozillove** [comment]
@joechengla Did you open the game from top sites? Seems like the game was opened in the normal browser mode. Thank you.
