### ISSUE TITLE
[BugBash]Shopping search prompt in shopping site is hard to swipe up to see once it is close

### ISSUE THREAD

**Issue by Daisy-pliu** [mozilla-mobile/FirefoxLite#3979]
**Describe the bug**
Shopping search prompt in shopping site is hard to swipe up to see once it is close

**Steps To Reproduce**
1. Go to Flipkart site
2. Swipe down the shopping search prompt on the bottom of the page
3.Hard to swipe up to display the prompt again

**Device info (please complete the following information):**
  - Version 16060

**Reproduce rate**

**Additional**

**Additional context**
from bug catcher : @harly21

**Comment by youwenliang** [comment]
This bug is invalid since we won't allow users to swipe up the prompt again.
According to #3907
