### ISSUE TITLE
Toast for informing user that Game shortcut is created successfully

### ISSUE THREAD

**Issue by Conjuror** [mozilla-mobile/FirefoxLite#3986]
**Describe the bug**
Follow mozilla-tw/mango#91 , we should have a toast to inform users that the shortcut on homescreen is created successfully (or not)

**Comment by Mozillove** [comment]
Zeplin (Visual design): https://app.zeplin.io/project/5d3e6ee752e9500d60e1f07e/screen/5dcbbdea101ee1bf67eb3930
The string "shortcut created" is under translation, will update here once it's done.
