### ISSUE TITLE
[Smoke Test] Images can still be saved in Block Image mode

### ISSUE THREAD

**Issue by dakaizou** [mozilla-mobile/FirefoxLite#420]
as title

Build: 540
DuT: mito

**Comment by Conjuror** [comment]
I believe it happens on all devices.

**Comment by chianger** [comment]
Seems not critical but let's leave the call to UX.

**Comment by NashTung** [comment]
This issue can be reproduced
Video: 
https://drive.google.com/open?id=1PTOc34Alvmu69nSs4rwh5HajuT6sY0I3

Device: Redmi 4A
Rocket: 2.0.0(4168).nightly
Android: 7.1.2
Android Webview: 66.0.3359.126

**Comment by NashTung** [comment]
It can be reproduced
Video:  https://drive.google.com/open?id=1hG5EQOK2ir7JRoIShBVmq-6uc9Vfstr3

Device: Redmi 4A
Rocket: 2.2.0(4809).nightly
Android: 7.1.2
Android Webview: 67.0.3396.68
