### ISSUE TITLE
Homecustomization with vertical content

### ISSUE THREAD

**Issue by Jacklin-ux** [mozilla-mobile/FirefoxLite#4388]
As a user, I want to choose topics or verticals which I am interested in so that I can easily see and access vertical content when I open browser.
As Mozilla, we believe moving vertical content (with ads) to browser home can increase transaction and ads revenue.

Ideas:
Game home, Shopping home, Lifestyle home, Travel home...

**Comment by weslyhuang** [comment]
Hi @Jacklin-ux even for "features" we'd like to have a priority assigned (P0 if you are going to bring this to grooming, otherwise P1 or lower). Would you help set a priority for this one? Thanks.
