### ISSUE TITLE
Close content tab directly 

### ISSUE THREAD

**Issue by joechengla** [mozilla-mobile/FirefoxLite#4395]
Change "Back" behavior to "Close" behavior. Tap to close content tab directly. No change in visual  icon

**Comment by lanyliu** [comment]
We'll treat it as new features since they're different behaviors (back vs. close). 
Waiting for PM's data request form.

**Comment by chianger** [comment]
Looks like the UX flow is clear. Removing NEED UX/VD but keep NEED METRICS

**Comment by shsu571** [comment]
Check with BI about the data spec.

**Comment by shsu571** [comment]
Need to make new google sheet and data review doc -> send request to BI team to review

**Comment by shsu571** [comment]
click <- => close content tab

**Comment by lanyliu** [comment]
Telemetry Spec 
https://docs.google.com/spreadsheets/d/1ziSnLqrHG-1S-72X5c39Myng1Yq_WG0CNq8aQkaNQhI/edit#gid=888392947

Data review
https://docs.google.com/document/d/1dZU5rX7ooXaGfZZy8dvccy7wwOrRtEpTfB_5qN7sHlI/edit#
