### ISSUE TITLE
We should include webstorage size we freed up when "Clear cache" is clicked.

### ISSUE THREAD

**Issue by mTwTm** [mozilla-mobile/FirefoxLite#440]
In, #434 we're freeing up the whole WebStorage when clear cache is clicked but the size shown in the toast does not include these WebStorage files.

**Comment by joechengla** [comment]
i think this is already done?

**Comment by mTwTm** [comment]
I'm not sure if we really want this but this should be simple. (Please ask the status of this bug before doing it if you don't want to start a pull request but get it blocked.)
