### ISSUE TITLE
Crash 2.0.3 on shopping search 

### ISSUE THREAD

**Issue by Daisy-pliu** [mozilla-mobile/FirefoxLite#4404]
**Describe the bug**
crash log in [crashlytics](https://console.firebase.google.com/u/0/project/zerda-dcf76/crashlytics/app/android:org.mozilla.rocket/issues/000e55faa4fc56ead9edea8a7bd7d555?time=last-seven-days&sessionId=5DE03B030186000160A32EE136D4BB25_DNE_0_v2)

**Additional context**
probably new remote config on EC site makes user with old remote config get crash. It only happens once, next time app will be fine. but still need dev effort on such error handling.

**Comment by youwenliang** [comment]
my steps to reproduce:
1. Clean cash & data for FIrefox Lite (production)

2. Open Firefox Lite Preview
3. Use shopping search and see the results
4. Leave Firefox Lite Preview without closing the app

5. Open Firefox Lite (production) and see the onboarding for content & services
6. Close Firefox Lite (production) and open again to see the onboarding for shopping search
7. Tap shopping search and search a keyword

8. Expecting to see the results but crashed and jumped to Firefox Lite Preview's shopping search results.

Let me know if you can follow the steps @Daisy-pliu

**Comment by weslyhuang** [comment]
priority assigned thus remove need triage.

**Comment by Daisy-pliu** [comment]
can not reproduce on QA side 
Device: Android 9 Pixel 2. 
Nightly : 2.04(17427)
Prod: 2.0.4 (17368)
