### ISSUE TITLE
Cannot focus on skipping advertisement in Game

### ISSUE THREAD

**Issue by Conjuror** [mozilla-mobile/FirefoxLite#4425]
**Describe the bug**
User cannot skip advertisement between game play for some games

**Steps To Reproduce**
1. Launch Firefox Lite
2. Tap on Game
3. Select a game to play
4. Tap [Skip Ads] when advertisement is playing
5. Finish the game
6. Tap [Skip Ads] when advertisement is playing

**Expected behavior**
User is able to skip advertisement playing

**Actual behavior**
User cannot focus on the button. No response for touch events.

**Screenshots/videos**
If applicable, add screenshots/videos to help explain your problem.

**Device info (please complete the following information):**
v2.0.3 (17314)

**Reproduce rate**
3/5

**Additional context**
Try Air Hockey

**Comment by Mozillove** [comment]
@Conjuror Would you please tell me which game has this issue? Thank you!

**Comment by weslyhuang** [comment]
release blocker or not? still TBD.

@Holidaybear will help investigate it first, added to S2-3 backlog for now.

**Comment by weslyhuang** [comment]
can't repro now? need qa
