### ISSUE TITLE
Nothing shows when typing a un-exist city name in travel

### ISSUE THREAD

**Issue by Conjuror** [mozilla-mobile/FirefoxLite#4452]
**Describe the bug**
Follow up of #3874 

**Steps To Reproduce**
1. Launch Firefox Lite
2. Tap on [Travel]
3. Tap on [Search bar]
4. Type a un-exist city, i.e. "ibkqrljkajsdlfjdsf"

**Expected behavior**
4. A suggestion dialog is shown

**Actual behavior**
4. No dialog is shown

**Comment by weslyhuang** [comment]
by design for now, non-blocking
