### ISSUE TITLE
Remote config. support changing affiliated top site icon

### ISSUE THREAD

**Issue by Jacklin-ux** [mozilla-mobile/FirefoxLite#4479]
For partner top site, we can change not only icon order, links or text but also displayed icon with remote config..

**Comment by shsu571** [comment]
more flexibility ->  icon & destination (need to write more elaborate spec)

**Comment by Conjuror** [comment]
Since we need to have a user flow for default and expected behavior. mark as need ux/vd.

**Comment by shsu571** [comment]
need to have UI design, when there's no icon ( if didn't get remote config)

**Comment by shsu571** [comment]
Need to check metric with BI

**Comment by Jacklin-ux** [comment]
When received remote config., show changed affiliated icons and its name to users. But if network connection is unable, show default text (e.g. Tokopedia -> T) and the name first, then show the icon when is ready.

**Comment by shsu571** [comment]
No partner demand right move to P1
