### ISSUE TITLE
[Travel]After the video cards pressed, the title font-weight states should be regular.

### ISSUE THREAD

**Issue by FinnickC** [mozilla-mobile/FirefoxLite#4488]
**Describe the bug**
After the video cards pressed, the title font-weight states should be regular.

UX spec
https://mozilla.invisionapp.com/share/EWSX97EB69J#/screens/374278127

Visual zeplin
https://zpl.io/bP1OLDl

**Comment by benjamin-cheng** [comment]
Confirmed with @tinahsieh to change the priority to P1
