### ISSUE TITLE
[Travel] Wikipedia search need to be more accurate

### ISSUE THREAD

**Issue by Conjuror** [mozilla-mobile/FirefoxLite#4503]
**Describe the bug**
Travel search on Wikipedia should be improved.

i.e., search **Malang**
I am expecting to visit [Malang wiki](https://zh.wikipedia.org/wiki/%E7%91%AA%E7%90%85)
![Screenshot_20191218-112746](https://user-images.githubusercontent.com/1625148/71053649-0e756700-218a-11ea-8ab3-73aa9de62da6.png)

**Comment by weslyhuang** [comment]
need Wikipedia's help on this? (the search algorithm?)
