### ISSUE TITLE
Youtube video's  comment not show on Private mode

### ISSUE THREAD

**Issue by Daisy-pliu** [mozilla-mobile/FirefoxLite#4540]
**Steps To Reproduce**
1. launch app
2. open private mode
3. search [youtube] 
4. tap [any video]
5. scroll down

**Expected behavior**
see comment under the video

**Actual behavior**
no comment under the video

**Screenshots/videos**

<img src="https://user-images.githubusercontent.com/44990878/71344672-2c820380-259e-11ea-9d24-cb3a6e2e4ba8.png" width="300">
**Device info (please complete the following information):**
Device: all
version: versions with release tag 2.0.X

**Reproduce rate**
10/10

**Additional context**
This issue not happened on versions with release tag 1.9.2,so it is a regression.
Normal browsing is good to show Youtube's  comments while private mode not.
 

<img src="https://user-images.githubusercontent.com/44990878/71344867-b0d48680-259e-11ea-9880-bd98e7432bfa.png" width="300">

**Comment by weslyhuang** [comment]
P1 thus remove "need triage"
