### ISSUE TITLE
Zerda crashes when visiting tabloidbintang.com on Mito

### ISSUE THREAD

**Issue by cssjh** [mozilla-mobile/FirefoxLite#460]
As title. Can reproduce only on Mito.
**Build:** 592
**DuT:** Mito

**Comment by cssjh** [comment]
Related to #342

**Comment by Conjuror** [comment]
#454 to track

**Comment by chianger** [comment]
QAWanted to see if can still be reproduced.

**Comment by mTwTm** [comment]
09-12 16:57:54.862 512-588/system_process E/WifiStateMachine: WifiStateMachine CMD_START_SCAN source -2 txSuccessRate=2.34 rxSuccessRate=18.81 targetRoamBSSID=70:3a:0e:32:d2:c1 RSSI=-51
09-12 16:58:12.949 172-567/? W/audio_hw_primary: [out_set_parameters], kvpairs=routing=2 devices:0x2 mode:0 
09-12 16:58:12.949 172-567/? W/audio_hw_primary: the same devices(0x2) with val(0x2) val is zero...
09-12 16:58:12.969 172-567/? W/audio_hw_primary: i2s_pin_mux_sel in type is 3
09-12 16:58:12.969 172-567/? W/audio_hw_primary: i2s_pin_mux_sel in type i-----------2 adev->cp =b70eef30 num = 2  vbc_ctrl_pipe_info = b70ef9f8   cp_type = 1
09-12 16:58:12.969 172-567/? W/audio_hw_primary: -----in  cpu_index  is 3 
09-12 16:58:12.969 172-567/? W/audio_hw_primary: i2s_pin_mux_sel in type i----------i2s_ctl_info->is_switch = 1 
09-12 16:58:12.969 172-567/? E/audio_hw_primary: select_devices_signal starting... adev->out_devices 0x2 adev->in_devices 0x0
09-12 16:58:12.969 172-567/? W/audio_hw_primary: open s_tinycard in
09-12 16:58:12.969 172-567/? W/audio_hw_primary: open s_tinycard successfully
09-12 16:58:12.969 172-567/? W/audio_hw_primary: out->write_threshold=0, config.avail_min=1280, start_threshold=640
09-12 16:58:12.969 172-564/? W/audio_hw_primary: vb_control_parameters.c hp_pa_delay_config 0x0 pa_config:0x318(0x318, 0), 0x2100000(fm)(0x0, 210),  hpPaConfig:0x0(0x0, 0), 0x0(fm)(0x0, 0)
09-12 16:58:13.009 172-564/? W/audio_hw_primary: SetAudio_PaConfig_by_devices out, out_devices:0x2, in_devices:0x0
09-12 16:58:13.009 172-564/? W/audio_hw_primary: GetAudio_gain_by_devices, outmode:3 inmode:3,indev:0x0, outdev:0x2
09-12 16:58:13.009 172-564/? W/audio_hw_primary: vb_control_parameters.c pa_config:0x318(0x318, 0), 0x2100000(fm)(0x0, 210),  hpPaConfig:0x0(0x0, 0), 0x0(fm)(0x0, 0)
09-12 16:58:13.009 172-564/? W/audio_hw_primary: vb_control_parameters.c GetAudio_outpga_nv, dac_pga_gain_l:0x801a07ca fm_pga_gain_l:0x24a fm_pga_gain_r:0x24a vol_level:0x1 
09-12 16:58:13.009 172-564/? W/audio_hw_primary: GetAudio_inpga_nv, adc_pga_gain_l:0x903c device:0x0 vol_level:0x1
09-12 16:58:13.009 172-564/? W/audio_hw_primary: SetAudio_gain_by_devices out, out_devices:0x2, in_devices:0x0
09-12 16:58:13.019 512-688/system_process W/Environment:   === curr internal type is == 1
09-12 16:58:13.139 3684-3684/? W/Environment:   === curr internal type is == 1
09-12 16:58:13.139 3684-3684/? W/Environment:   === curr storage type is == 1
09-12 16:58:13.139 3684-3684/? W/Environment:   === curr internal type is == 1
09-12 16:58:13.960 512-923/system_process W/ActivityManager: getRunningAppProcesses: caller 10101 does not hold REAL_GET_TASKS; limiting output
09-12 16:58:14.431 3684-3699/org.mozilla.zerda.debug.tyu W/art: Suspending all threads took: 36.437ms
09-12 16:58:14.491 3684-3684/org.mozilla.zerda.debug.tyu W/art: Before Android 4.1, method android.graphics.PorterDuffColorFilter android.support.graphics.drawable.VectorDrawableCompat.updateTintFilter(android.graphics.PorterDuffColorFilter, android.content.res.ColorStateList, android.graphics.PorterDuff$Mode) would have incorrectly overridden the package-private method in android.graphics.drawable.Drawable
09-12 16:58:14.561 3684-3708/org.mozilla.zerda.debug.tyu W/Environment:   === curr storage type is == 1
09-12 16:58:14.561 3684-3708/org.mozilla.zerda.debug.tyu W/Environment:   === curr storage type is == 1
09-12 16:58:14.871 512-588/system_process E/WifiStateMachine: WifiStateMachine CMD_START_SCAN source -2 txSuccessRate=0.18 rxSuccessRate=17.96 targetRoamBSSID=70:3a:0e:32:d2:c1 RSSI=-53
09-12 16:58:15.472 3684-3684/org.mozilla.zerda.debug.tyu E/RecyclerView: No adapter attached; skipping layout
09-12 16:58:16.403 172-567/? W/audio_hw_primary: do_output_standby.mode:0 
09-12 16:58:23.059 2183-2246/com.google.android.gms W/Herrevad: [252] thj.b: Invalid mccmnc 
09-12 16:58:23.059 2183-2246/com.google.android.gms W/Herrevad: [252] thj.b: Invalid mccmnc 
09-12 16:58:27.053 172-567/? W/audio_hw_primary: [out_set_parameters], kvpairs=routing=2 devices:0x2 mode:0 
09-12 16:58:27.053 172-567/? W/audio_hw_primary: the same devices(0x2) with val(0x2) val is zero...
09-12 16:58:27.073 172-567/? W/audio_hw_primary: i2s_pin_mux_sel in type is 3
09-12 16:58:27.073 172-567/? W/audio_hw_primary: i2s_pin_mux_sel in type i-----------2 adev->cp =b70eef30 num = 2  vbc_ctrl_pipe_info = b70ef9f8   cp_type = 1
09-12 16:58:27.073 172-567/? W/audio_hw_primary: -----in  cpu_index  is 3 
09-12 16:58:27.073 172-567/? W/audio_hw_primary: i2s_pin_mux_sel in type i----------i2s_ctl_info->is_switch = 1 
09-12 16:58:27.073 172-567/? E/audio_hw_primary: select_devices_signal starting... adev->out_devices 0x2 adev->in_devices 0x0
09-12 16:58:27.073 172-567/? W/audio_hw_primary: open s_tinycard in
09-12 16:58:27.073 172-567/? W/audio_hw_primary: open s_tinycard successfully
09-12 16:58:27.073 172-567/? W/audio_hw_primary: out->write_threshold=0, config.avail_min=1280, start_threshold=640
09-12 16:58:27.073 172-564/? W/audio_hw_primary: vb_control_parameters.c hp_pa_delay_config 0x0 pa_config:0x318(0x318, 0), 0x2100000(fm)(0x0, 210),  hpPaConfig:0x0(0x0, 0), 0x0(fm)(0x0, 0)
09-12 16:58:27.113 172-564/? W/audio_hw_primary: SetAudio_PaConfig_by_devices out, out_devices:0x2, in_devices:0x0
09-12 16:58:27.113 172-564/? W/audio_hw_primary: GetAudio_gain_by_devices, outmode:3 inmode:3,indev:0x0, outdev:0x2
09-12 16:58:27.113 172-564/? W/audio_hw_primary: vb_control_parameters.c pa_config:0x318(0x318, 0), 0x2100000(fm)(0x0, 210),  hpPaConfig:0x0(0x0, 0), 0x0(fm)(0x0, 0)
09-12 16:58:27.113 172-564/? W/audio_hw_primary: vb_control_parameters.c GetAudio_outpga_nv, dac_pga_gain_l:0x801a07ca fm_pga_gain_l:0x24a fm_pga_gain_r:0x24a vol_level:0x1 
09-12 16:58:27.113 172-564/? W/audio_hw_primary: GetAudio_inpga_nv, adc_pga_gain_l:0x903c device:0x0 vol_level:0x1
09-12 16:58:27.113 172-564/? W/audio_hw_primary: SetAudio_gain_by_devices out, out_devices:0x2, in_devices:0x0
09-12 16:58:28.154 172-567/? W/audio_hw_primary: [out_set_parameters], kvpairs=routing=2 devices:0x2 mode:0 
09-12 16:58:28.154 172-567/? W/audio_hw_primary: the same devices(0x2) with val(0x2) val is zero...
09-12 16:58:28.384 3684-3684/org.mozilla.zerda.debug.tyu W/PathParser: Points are too far apart 4.000000902246307
09-12 16:58:28.384 3684-3684/org.mozilla.zerda.debug.tyu W/PathParser: Points are too far apart 4.000000902246293
09-12 16:58:30.186 172-567/? W/audio_hw_primary: [out_set_parameters], kvpairs=routing=2 devices:0x2 mode:0 
09-12 16:58:30.186 172-567/? W/audio_hw_primary: the same devices(0x2) with val(0x2) val is zero...
09-12 16:58:33.720 172-567/? W/audio_hw_primary: do_output_standby.mode:0 
09-12 16:58:34.871 512-588/system_process E/WifiStateMachine: WifiStateMachine CMD_START_SCAN source -2 txSuccessRate=0.19 rxSuccessRate=22.19 targetRoamBSSID=70:3a:0e:32:d2:c1 RSSI=-56
09-12 16:58:45.471 3684-3684/org.mozilla.zerda.debug.tyu W/IInputConnectionWrapper: endBatchEdit on inactive InputConnection
09-12 16:58:45.671 3684-3684/org.mozilla.zerda.debug.tyu W/art: Attempt to remove local handle scope entry from IRT, ignoring
09-12 16:58:45.691 3684-3733/org.mozilla.zerda.debug.tyu W/AudioManagerAndroid: Requires BLUETOOTH permission
09-12 16:58:45.701 3684-3684/org.mozilla.zerda.debug.tyu W/chromium: [WARNING:resource_bundle.cc(304)] locale_file_path.empty()
09-12 16:58:45.891 512-528/system_process W/ActivityManager: getRunningAppProcesses: caller 10101 does not hold REAL_GET_TASKS; limiting output
09-12 16:58:45.891 512-2395/system_process W/ActivityManager: getRunningAppProcesses: caller 10101 does not hold REAL_GET_TASKS; limiting output
09-12 16:58:45.911 3684-3684/org.mozilla.zerda.debug.tyu W/chromium: [WARNING:data_reduction_proxy_settings.cc(331)] SPDY proxy OFF at startup
09-12 16:58:45.931 3684-3684/org.mozilla.zerda.debug.tyu W/art: Attempt to remove local handle scope entry from IRT, ignoring
09-12 16:58:45.931 3684-3684/org.mozilla.zerda.debug.tyu W/AwContents: onDetachedFromWindow called when already detached. Ignoring
09-12 16:58:50.336 3684-3750/org.mozilla.zerda.debug.tyu A/libc: Fatal signal 11 (SIGSEGV), code 1, fault addr 0x0 in tid 3750 (Thread-412)
09-12 16:58:52.117 512-3774/system_process W/ActivityManager:   Force finishing activity 1 org.mozilla.zerda.debug.tyu/org.mozilla.focus.activity.MainActivity
09-12 16:58:52.198 512-3774/system_process E/JavaBinder: !!! FAILED BINDER TRANSACTION !!!
09-12 16:58:52.208 512-577/system_process W/InputDispatcher: channel '17131ee2 org.mozilla.zerda.debug.tyu/org.mozilla.focus.activity.MainActivity (server)' ~ Consumer closed input channel or an error occurred.  events=0x9
09-12 16:58:52.208 512-577/system_process E/InputDispatcher: channel '17131ee2 org.mozilla.zerda.debug.tyu/org.mozilla.focus.activity.MainActivity (server)' ~ Channel is unrecoverably broken and will be disposed!
09-12 16:58:52.208 512-1041/system_process W/InputDispatcher: Attempted to unregister already unregistered input channel '17131ee2 org.mozilla.zerda.debug.tyu/org.mozilla.focus.activity.MainActivity (server)'
09-12 16:58:52.228 512-3774/system_process W/ActivityManager: Exception thrown during pause
                                                              android.os.TransactionTooLargeException
                                                                  at android.os.BinderProxy.transactNative(Native Method)
                                                                  at android.os.BinderProxy.transact(Binder.java:519)
                                                                  at android.app.ApplicationThreadProxy.schedulePauseActivity(ApplicationThreadNative.java:704)
                                                                  at com.android.server.am.ActivityStack.startPausingLocked(ActivityStack.java:825)
                                                                  at com.android.server.am.ActivityStack.finishActivityLocked(ActivityStack.java:2740)
                                                                  at com.android.server.am.ActivityStack.finishTopRunningActivityLocked(ActivityStack.java:2597)
                                                                  at com.android.server.am.ActivityStackSupervisor.finishTopRunningActivityLocked(ActivityStackSupervisor.java:2559)
                                                                  at com.android.server.am.ActivityManagerService.handleAppCrashLocked(ActivityManagerService.java:11699)
                                                                  at com.android.server.am.ActivityManagerService.makeAppCrashingLocked(ActivityManagerService.java:11596)
                                                                  at com.android.server.am.ActivityManagerService.crashApplication(ActivityManagerService.java:12290)
                                                                  at com.android.server.am.ActivityManagerService.handleApplicationCrashInner(ActivityManagerService.java:11791)
                                                                  at com.android.server.am.NativeCrashListener$NativeCrashReporter.run(NativeCrashListener.java:86)
09-12 16:58:52.228 158-158/? E/lowmemorykiller: Error opening /proc/3684/oom_score_adj; errno=2
09-12 16:58:52.268 1052-1052/com.android.launcher3 W/ContextImpl: Calling a method in the system process without a qualified user: android.app.ContextImpl.sendBroadcast:1347 android.content.ContextWrapper.sendBroadcast:377 com.android.launcher3.Launcher.onResume:1146 android.app.Instrumentation.callActivityOnResume:1257 android.app.Activity.performResume:6103 
09-12 16:58:54.870 512-588/system_process E/WifiStateMachine: WifiStateMachine CMD_START_SCAN source -2 txSuccessRate=42.83 rxSuccessRate=47.84 targetRoamBSSID=70:3a:0e:32:d2:c1 RSSI=-63
09-12 16:59:14.870 512-588/system_process E/WifiStateMachine: WifiStateMachine CMD_START_SCAN source -2 txSuccessRate=0.33 rxSuccessRate=17.92 targetRoamBSSID=70:3a:0e:32:d2:c1 RSSI=-62

**Comment by mTwTm** [comment]
Removing QAWanted since I have reproduced it.

**Comment by walkingice** [comment]
Tested on Zerda, Focs and Lightning. All of them crashed in the web site.
I got crash log like this

```
D/AwSettings( 6868): This appProcess name is org.mozilla.rocket.debug.jchu
W/art     ( 6868): Attempt to remove local handle scope entry from IRT, ignoring
D/webcore ( 6868): WebContentsImpl::Send
D/webcore ( 6868): WebContentsImpl::Send
D/AwSettings( 6868):  getForceUserScalableLocked mForceUserScalableEnaled: false
D/AwSettings( 6868):  getSavePasswordEnabledLocked mSavePasswordEnabled: false
D/AwSettings( 6868): This appProcess name is org.mozilla.rocket.debug.jchu
D/webcore ( 6868): WebContentsImpl::Send
W/AwContents( 6868): onDetachedFromWindow called when already detached. Ignoring
D/webcore ( 6868): WebContentsImpl::Send
D/AwSettings( 6868):  getForceUserScalableLocked mForceUserScalableEnaled: false
D/AwSettings( 6868):  getSavePasswordEnabledLocked mSavePasswordEnabled: false
D/AwSettings( 6868): This appProcess name is org.mozilla.rocket.debug.jchu
D/webcore ( 6868): WebContentsImpl::Send
D/AwSettings( 6868):  getForceUserScalableLocked mForceUserScalableEnaled: false
D/AwSettings( 6868):  getSavePasswordEnabledLocked mSavePasswordEnabled: false
D/AwSettings( 6868): This appProcess name is org.mozilla.rocket.debug.jchu
D/webcore ( 6868): WebContentsImpl::Send
D/AwSettings( 6868):  getForceUserScalableLocked mForceUserScalableEnaled: false
D/AwSettings( 6868):  getSavePasswordEnabledLocked mSavePasswordEnabled: false
D/AwSettings( 6868): This appProcess name is org.mozilla.rocket.debug.jchu
D/webcore ( 6868): WebContentsImpl::Send
D/webcore ( 6868): WebContentsImpl::Send
D/AwSettings( 6868):  getForceUserScalableLocked mForceUserScalableEnaled: false
D/AwSettings( 6868):  getSavePasswordEnabledLocked mSavePasswordEnabled: false
D/AwSettings( 6868): This appProcess name is org.mozilla.rocket.debug.jchu
D/webcore ( 6868): WebContentsImpl::Send
D/AwSettings( 6868):  getForceUserScalableLocked mForceUserScalableEnaled: false

........

F/libc    ( 6868): Fatal signal 11 (SIGSEGV), code 1, fault addr 0x0 in tid 6995 (Thread-470)
I/DEBUG   (  162): *** *** *** *** *** *** *** *** *** *** *** *** *** *** *** ***
I/DEBUG   (  162): Native Crash TIME: 993204
I/DEBUG   (  162): *** *** *** *** *** *** *** *** *** *** *** *** *** *** *** ***
I/DEBUG   (  162): Build fingerprint: 'SPRD/c7356_wvga_dt_oversea_multi/scx20_c7356_wvga:5.1/LMY47D/S:user/release-keys'
I/DEBUG   (  162): Revision: '0'
I/DEBUG   (  162): ABI: 'arm'
I/DEBUG   (  162): pid: 6868, tid: 6995, name: Thread-470  >>> org.mozilla.rocket.debug.jchu <<<
I/DEBUG   (  162): signal 11 (SIGSEGV), code 1 (SEGV_MAPERR), fault addr 0x0
I/DEBUG   (  162):     r0 00000000  r1 a2806ea8  r2 0000001c  r3 00000000
I/DEBUG   (  162):     r4 a2806ea8  r5 a2806ea8  r6 a2806ea8  r7 00000000
I/DEBUG   (  162):     r8 57a71340  r9 57bb3570  sl 00000000  fp a28070bc
I/DEBUG   (  162):     ip 00000001  sp a2806e60  lr a7058269  pc a70581c2  cpsr 080b0030
I/DEBUG   (  162):█
I/DEBUG   (  162): backtrace:
I/DEBUG   (  162):     #00 pc 0098d1c2  /system/lib/libwebviewchromium.so
I/DEBUG   (  162):     #01 pc 0098d265  /system/lib/libwebviewchromium.so
I/DEBUG   (  162):     #02 pc 00a28a6f  /system/lib/libwebviewchromium.so
I/DEBUG   (  162):     #03 pc 00a28c23  /system/lib/libwebviewchromium.so
I/DEBUG   (  162):     #04 pc 00a46c1b  /system/lib/libwebviewchromium.so
I/DEBUG   (  162):     #05 pc 00a28f79  /system/lib/libwebviewchromium.so
I/DEBUG   (  162):     #06 pc 00a26abf  /system/lib/libwebviewchromium.so
I/DEBUG   (  162):     #07 pc 00a27963  /system/lib/libwebviewchromium.so
I/DEBUG   (  162):     #08 pc 0098d849  /system/lib/libwebviewchromium.so
I/DEBUG   (  162):     #09 pc 009bbb5f  /system/lib/libwebviewchromium.so
I/DEBUG   (  162):     #10 pc 00a24b57  /system/lib/libwebviewchromium.so
I/DEBUG   (  162):     #11 pc 00979d13  /system/lib/libwebviewchromium.so
I/DEBUG   (  162):     #12 pc 0136e67b  /system/lib/libwebviewchromium.so
I/DEBUG   (  162):     #13 pc 0136728f  /system/lib/libwebviewchromium.so
I/DEBUG   (  162):     #14 pc 01365fcf  /system/lib/libwebviewchromium.so
I/DEBUG   (  162):     #15 pc 01367551  /system/lib/libwebviewchromium.so
I/DEBUG   (  162):     #16 pc 01357e51  /system/lib/libwebviewchromium.so
I/DEBUG   (  162):     #17 pc 00fd61a5  /system/lib/libwebviewchromium.so
I/DEBUG   (  162):     #18 pc 00fd6013  /system/lib/libwebviewchromium.so
I/DEBUG   (  162):     #19 pc 002466a7  /system/lib/libwebviewchromium.so
I/DEBUG   (  162):     #20 pc 00229471  /system/lib/libwebviewchromium.so
I/DEBUG   (  162):     #21 pc 0022a859  /system/lib/libwebviewchromium.so
I/DEBUG   (  162):     #22 pc 0022ac23  /system/lib/libwebviewchromium.so
I/DEBUG   (  162):     #23 pc 0022adbb  /system/lib/libwebviewchromium.so
I/DEBUG   (  162):     #24 pc 00229709  /system/lib/libwebviewchromium.so
I/DEBUG   (  162):     #25 pc 0022fe8b  /system/lib/libwebviewchromium.so
I/DEBUG   (  162):     #26 pc 00229095  /system/lib/libwebviewchromium.so
I/DEBUG   (  162):     #27 pc 0023c199  /system/lib/libwebviewchromium.so
I/DEBUG   (  162):     #28 pc 002392d1  /system/lib/libwebviewchromium.so
I/DEBUG   (  162):     #29 pc 000164cb  /system/lib/libc.so (__pthread_start(void*)+30)
I/DEBUG   (  162):     #30 pc 000144e3  /system/lib/libc.so (__start_thread+6)
D/Bitmap  ( 1016): recycle bitmap... mNativeBitmap = -1212001768 , Bitmap = android.graphics.Bitmap@3d7e6463

......

W/ActivityManager(  512):   Force finishing activity 1 org.mozilla.rocket.debug.jchu/org.mozilla.rocket.activity.MainActivity
D/WindowManager(  512): Pausing WindowToken AppWindowToken{11f3d8e4 token=Token{1e898477 ActivityRecord{21512676 u0 org.mozilla.rocket.debug.jchu/org.mozilla.rocket.activity.MainActivity t2026}}}
I/DEBUG   (  162):█
I/DEBUG   (  162): Tombstone written to: /data/tombstones/tombstone_03

......

I/WindowState(  512): WIN DEATH: Window{27700868 u0 org.mozilla.rocket.debug.jchu/org.mozilla.rocket.activity.MainActivity}
W/ActivityManager(  512): Exception thrown during pause
W/ActivityManager(  512): android.os.DeadObjectException
W/ActivityManager(  512): ⋮.....at android.os.BinderProxy.transactNative(Native Method)
W/ActivityManager(  512): ⋮.....at android.os.BinderProxy.transact(Binder.java:519)
W/ActivityManager(  512): ⋮.....at android.app.ApplicationThreadProxy.schedulePauseActivity(ApplicationThreadNative.java:704)
W/ActivityManager(  512): ⋮.....at com.android.server.am.ActivityStack.startPausingLocked(ActivityStack.java:825)
W/ActivityManager(  512): ⋮.....at com.android.server.am.ActivityStack.finishActivityLocked(ActivityStack.java:2740)
W/ActivityManager(  512): ⋮.....at com.android.server.am.ActivityStack.finishTopRunningActivityLocked(ActivityStack.java:2597)
W/ActivityManager(  512): ⋮.....at com.android.server.am.ActivityStackSupervisor.finishTopRunningActivityLocked(ActivityStackSupervisor.java:2559)
W/ActivityManager(  512): ⋮.....at com.android.server.am.ActivityManagerService.handleAppCrashLocked(ActivityManagerService.java:11699)
W/ActivityManager(  512): ⋮.....at com.android.server.am.ActivityManagerService.makeAppCrashingLocked(ActivityManagerService.java:11596)
W/ActivityManager(  512): ⋮.....at com.android.server.am.ActivityManagerService.crashApplication(ActivityManagerService.java:12290)
W/ActivityManager(  512): ⋮.....at com.android.server.am.ActivityManagerService.handleApplicationCrashInner(ActivityManagerService.java:11791)
W/ActivityManager(  512): ⋮.....at com.android.server.am.NativeCrashListener$NativeCrashReporter.run(NativeCrashListener.java:86)
D/InputDispatcher(  512): Window went away: Window{27700868 u0 org.mozilla.rocket.debug.jchu/org.mozilla.rocket.activity.MainActivity}
D/PowerManagerService(  512): acquireWakeLockInternal: lock=762297995, flags=0x1, tag="ActivityManager-Launch", ws=null, uid=1000, pid=512
E/lowmemorykiller(  159): Error writing /proc/6868/oom_score_adj; errno=22
D/BroadcastQueue(  512): Add broadcastBroadcastRecord{c1f4503 u0 android.intent.action.DROPBOX_ENTRY_ADDED} into (background/order), now header = BroadcastRecord{c1f4503 u0 android.intent.action.DROPBOX_ENTRY_ADDED}, size = 1
I/ActivityManager(  512): Process org.mozilla.rocket.debug.jchu (pid 6868) has died
```

**Comment by mTwTm** [comment]
Let's remove this from Sprint 7 then.
