### ISSUE TITLE
Travel Home should also handle offline situation

### ISSUE THREAD

**Issue by youwenliang** [mozilla-mobile/FirefoxLite#4603]
Travel Home should align offline situation with other verticals.
Currently the offline situation is blank and looks like this:
![image](https://user-images.githubusercontent.com/8919308/71793590-619b5500-3078-11ea-838f-56b51b871e1c.png)

Will need to remove search section and add "offline rocky" for the offline situation.
Tina will be working on the ux/ui part of this. No metrics are needed for this issue.
(This should be an S-size issue.)

**Comment by FinnickC** [comment]
UI Spec
https://zpl.io/bA5k4gB
