### ISSUE TITLE
Upgrade all python scripts to python 3

### ISSUE THREAD

**Issue by Conjuror** [mozilla-mobile/FirefoxLite#4623]
Currently, all scripts work with Python 2. As Python 2 reached its end by January 1st, 2020. We should consider to move all scripts to Python 3. Given the fact that Python 2.7.18 will be released in April, we should still have time to plan and work on it.

**Comment by shsu571** [comment]
L10n -> will open another issue
But also need to check with engineers (might be telemtry or other part will use Python)

**Comment by Conjuror** [comment]
Here's the list of all python scripts we have in product:

amplitude:
- tools/metrics/amplitude_csv2schema.py

apk size checker:
- tools/metrics/apk_size.py

l10n:
- tools/l10n/android2po/patch.py
- tools/l10n/android2po/config.py
- tools/l10n/android2po/env.py
- tools/l10n/android2po/config.pyc
- tools/l10n/android2po/convert.py
- tools/l10n/android2po/__pycache__/commands.cpython-37.pyc
- tools/l10n/android2po/__pycache__/program.cpython-37.pyc
- tools/l10n/android2po/a2po.py
- tools/l10n/android2po/env.pyc
- tools/l10n/android2po/utils.py
- tools/l10n/android2po/patch.pyc
- tools/l10n/android2po/program.py
- tools/l10n/android2po/commands.pyc
- tools/l10n/android2po/convert.pyc
- tools/l10n/android2po/commands.py
- tools/l10n/android2po/utils.pyc
- tools/l10n/android2po/program.pyc
- tools/l10n/check_translations.py
- tools/l10n/attach-local-strings.py

CI:
- tools/ci/revertCommitParser.py
- tools/ci/detectCommitsFormat.py

??
- tools/search/scrape_plugins.py

firebase:
- tools/firebase/firebase_setup.py
