### ISSUE TITLE
The order of search result changes in specific situation

### ISSUE THREAD

**Issue by Conjuror** [mozilla-mobile/FirefoxLite#4630]
**Describe the bug**
The order of search result changes in specific situation. Suggest as P2.

**Prerequisite**

- Set your system default language to Chinese
- Set Travel Search as default

**Steps To Reproduce**
1. Launch Firefox Lite
2. Tap Settings, Language, and change the language to English (United State)
3. Tap back key to Firefox Lite home
4. Tap on [Travel vertical]
5. Tap on [Search bar]
6. Search for "Hi"
7. Tap on [Search]
8. Tap on [back]
9. Check the search result

**Expected behavior**
6. 廣島 (Hiroshima) is at the first place
9. Hawaii is at the first place and Hiroshima at the second.

**Actual behavior**
Result in step 6 and step 9 should be the same

**Comment by shsu571** [comment]
Check with AL Notes-> language setting doesn't show after make language change
