### ISSUE TITLE
In some cases, users won't be able to see news content

### ISSUE THREAD

**Issue by Conjuror** [mozilla-mobile/FirefoxLite#4637]
**Describe the bug**
Launch Firefox Lite and enter news vertical. Sometimes, users cannot see the content.

- If a user attempts to refresh with the refresh button on the upper-right corner, news content could be visible.

- If a user attempts to refresh with the button "Try again", the user always fails.

Build: v2.1.6 (18091)

**Comment by youwenliang** [comment]
Hi @Jacklin-ux have you seen this issue before?

**Comment by Jacklin-ux** [comment]
Curious, which country's news has this issue?

**Comment by youwenliang** [comment]
> Curious, which country's news has this issue?

Taiwan, but currently I can't reproduce anymore.
