### ISSUE TITLE
Facebook quick search doesn't work

### ISSUE THREAD

**Issue by Conjuror** [mozilla-mobile/FirefoxLite#4641]
**Describe the bug**
As title, there's no result for quick search now

**Steps To Reproduce**
1. tap [search bar] on home page
2. type [skirts]
3. tap [back]
4. tap [search bar] and type [red skirt]
5. tap [Facebook]
6. tap [search icon] and type [red skirt]
7. tap [Youtube]

**Expected behavior**
1. not show quick search icon
2. show quick search icon when it detects text
5. show "red skirt" on FB search bar (https://www.facebook.com/search/str/red%20 skirt/keywords_search)
7. show "red skirt" on Youtube search bar (https://www.youtube.com/results?search_query=red+skirt)

**Actual behavior**
7. Web URL is correct but no results.

**Comment by youwenliang** [comment]
I've tested and all the Facebook searches have no results, but Youtube works for me.

**Comment by Conjuror** [comment]
I think it's caused by Facebook change the search mechanism. If we want to use Facebook search, we might need to change the search URL.

**Comment by youwenliang** [comment]
Currently we are using in Firefox Lite quick search:
https://m.facebook.com/search/str/KEYWORD/keywords_search

Latest Facebook search link looks like this:
https://m.facebook.com/search/top/?q=KEYWORD&epa=SEARCH_BOX

(Will need to login in to see the results though)
