### ISSUE TITLE
Black block over keyboard on content tab 

### ISSUE THREAD

**Issue by Daisy-pliu** [mozilla-mobile/FirefoxLite#4664]
**Steps To Reproduce**

**SC1**
1. launch app
2  go to [shopping] 
3. go to [coupon] 
4. tap any Shopee's coupon 
5. tap [login]
6. tap [usernam]

**SC2**
1. launch app
2  go to  [travel]
3. tap [any city]->tap [any hotels]
4. tap [login]
5. tap [username]

**Expected behavior**
see Black block on keyboard on content tab

**Actual behavior**
see keyboard only

**Screenshots/videos**
![Screenshot_20200120-151506](https://user-images.githubusercontent.com/44990878/72705943-adc9b780-3b97-11ea-80db-d4ae953e6180.png)

![Screenshot_20200120-145604#1](https://user-images.githubusercontent.com/44990878/72705914-9985ba80-3b97-11ea-9fa1-e47d54452842.png)

**Device info (please complete the following information):**
 - Device: Pixel 8.0
 - Webview : 79.0.3945.116
 - Version : 2.1.7 (18168)
**Reproduce rate**
10/10

**Additional context**
happened on 2.0.2(16855), 2.1.7(18204) as well.
Not webview issue. it is a issue lying on shopping or travel for a long time , but not on shopping search.

**Comment by youwenliang** [comment]
I think it happens in all the content tabs inside verticals. Marked as P1.
