### ISSUE TITLE
Firefase In app msg flash disappeared 

### ISSUE THREAD

**Issue by Daisy-pliu** [mozilla-mobile/FirefoxLite#4686]
**Steps To Reproduce**
1. set up in app msg on Firebase
2. launch app

**Expected behavior**
2.  see in app message

**Actual behavior**
2.user see In app msg flash and then disappeared 

**Screenshots/videos**
[slack discussion with video](https://mozilla.slack.com/archives/CMP856PSM/p1580891242079100)

**Device info (please complete the following information):**
 - Device: Oppo
 - OS: Android 7
 - Webview 79.0.3945.136
 - Version 2.1.8(18383)

**Reproduce rate**
1/3

**Additional context**
another 2 devices also encountered same issue.
roger : pixel 3
chalres: sumsang a3

**Comment by chianger** [comment]
Per chat over slack:  Need to check but not blocker
https://mozilla.slack.com/archives/CS7KS9DT6/p1582079712062200?thread_ts=1582079277.062000&cid=CS7KS9DT6
