### ISSUE TITLE
Use of italics in Empty state messages

### ISSUE THREAD

**Issue by Joseph-PS** [mozilla-mobile/FirefoxLite#4694]
**Describe the bug**
Italics can sometimes be hard on dyslexic users. Insufficient spacing between letters tends to make the text appear to run together making words hard to recognise especially for dyslexic users.
The main conclusion is that font types have an impact on user readability.

**Steps To Reproduce**
1. Open Firefox Lite homepage.
2. Click on the "three dots" at the bottom right corner.
3. Click on the Bookmarks or Downloads or History icon.
4. See the microcopy in italic.

**Expected behavior**
No bookmarks/ No downloads/ No browsing history

**Actual behavior**
_No bookmarks_

**Screenshots/videos**
<img width="1188" alt="Firefox Lite" src="https://user-images.githubusercontent.com/60518474/74261315-16343080-4d21-11ea-8890-8946b1fc293a.png">

**Device info (please complete the following information):**
 - Device: [e.g. One plus 7]
 - OS: [e.g. Android 10]
 - Webview [e.g. 69.0.3497.100]
 - Version [e.g. 3.3.0(7183).nightly]

**Reproduce rate**
Every time when there is no bookmarks saved, no downloads done and no history saved.

**Additional context**

**Comment by shsu571** [comment]
@TLHuang  could you help to review this?
