### ISSUE TITLE
can not play Gamezop certain game

### ISSUE THREAD

**Issue by Daisy-pliu** [mozilla-mobile/FirefoxLite#4735]
**Steps To Reproduce**
1. upload game_banner_destination_type in [sheet ](https://docs.google.com/spreadsheets/d/1YEYH7fwWiWJjrSQwBiPul-e0N9B7j0QbemvBtJxmgN8/edit#gid=916540177) on Admin console in Nightly
2. launch app 
3.  tap [game ]
4.  tap [banner's gamezop game] (name: ludo with friends)
5.  tap [login]

**Expected behavior**
5.  see game's login page

**Actual behavior**
5. see 502 gate way error

**Screenshots/videos**
![Screenshot_20200221-113204](https://user-images.githubusercontent.com/44990878/75002002-01346b80-549e-11ea-859f-afd3e0260294.png)
![Screenshot_20200221-113137](https://user-images.githubusercontent.com/44990878/75002008-0691b600-549e-11ea-9e97-e5546a21bb37.png)

**Device info (please complete the following information):**
 - all
**Reproduce rate**
10/10

**Additional context**
no matter this game opened with content tab or full screen content tab it still shows server error.
Need PM followup with Gameloft partner

**Comment by youwenliang** [comment]
Will contact our Gamezop partner to check the issue. thanks for finding this error!
