### ISSUE TITLE
Vertical : when data source has error, UI shows no data.

### ISSUE THREAD

**Issue by shsu571** [mozilla-mobile/FirefoxLite#4739]
**User story**
As a user, I would like to no data msg when data source has problem.

**Additional context**
Sprint 3-3 retro, Google news error -> no Top news in Taiwan

**Comment by chianger** [comment]
This was discussed over slack weeks ago but didn;'t really get tagged label. https://mozilla.slack.com/archives/CS7KS9DT6/p1581486820097100?thread_ts=1581483341.083200&cid=CS7KS9DT6

**Comment by chianger** [comment]
Tagging P1 per that conversation for now.
