### ISSUE TITLE
Disorder layout of onboarding on ration 16:9 screen

### ISSUE THREAD

**Issue by Daisy-pliu** [mozilla-mobile/FirefoxLite#4744]
**Steps To Reproduce**
1. launch app

**Expected behavior**
see good layout of onboarding 

**Actual behavior**
see disorder layout of onboarding

**Screenshots/videos**
![Screenshot_20200224-141556](https://user-images.githubusercontent.com/44990878/75132107-ac4c5b80-5710-11ea-9dea-75962eca2d09.png)

**Device info (please complete the following information):**
 - Device: samsung S6 edge (540 x 960 pixels, 16:9 ratio) ,(1440 x 2560 pixels, 16:9 ratio), Vivo 1606, pixel 2  (Resolution | 1080 x 1920 pixels, 16:9 ratio)
 - Webview : stable  80.0.3987.117
 - Version : 2.1.9(18705)

**Reproduce rate**
10/10

**Additional context**
not happened on Samsung 8.0.
it is a regression as it not happened in 2.1.2 (17721) release . seems it happens on small screen size

**Comment by shsu571** [comment]
Need to fix but not 2.1.9's blocker

**Comment by proevan** [comment]
@Daisy-pliu can you help to test the current master branch and see if this issue has been fixed in #4736
