### ISSUE TITLE
Travel crash when search city with Google 1th time on Android 6 

### ISSUE THREAD

**Issue by Daisy-pliu** [mozilla-mobile/FirefoxLite#4745]
**Steps To Reproduce**
1. fresh launch Firefox Lite
2. Tap on [Travel]
3. Tap on [search bar]
4. Type a city name, i.e. "Sydney"
5. tap [enter]

**Expected behavior**
see [discover more] with actions [try travel discovery ] and [no thanks ]
 
**Actual behavior**
[crash](https://console.firebase.google.com/u/0/project/zerda-dcf76/crashlytics/app/android:org.mozilla.rocket/issues?buildIds=124671633&state=open&time=last-seven-days&type=crash)

**Screenshots/videos**

**Device info (please complete the following information):**
 - Device: samsung S6 
 - OS: 6.0
 - Webview  :   80.0.3987.117
 - Version : 2.1.9 (18705) 

**Reproduce rate**
5/5

**Additional context**
1. not happens on Samsung S7 edge (8.0) or Pixel 2 (9.0)
2. it only happens when user tap [enter] or when user tap [see results in Google ] 
3. it wont happen when user tap [search with travel discovery]
4. this issue only happen first time launch,  it will recover in the next time.

**Comment by shsu571** [comment]
![螢幕快照 2020-02-25 上午10 12 23](https://user-images.githubusercontent.com/52307187/75208859-c1c89080-57b7-11ea-9ff9-b48df1773374.png)
Around 20% of users are Android6. 
57% of these users use the latest version.
Useage of travel vertical: daily around 1000 -> if 20% is Android 6 -> 200 -> the chance to happen will not be high

But, if the effore is not huge, we still need to fix these on next release.
