### ISSUE TITLE
Should not see ECsite promt after 5 session EC site tab 

### ISSUE THREAD

**Issue by Daisy-pliu** [mozilla-mobile/FirefoxLite#4749]
**Steps To Reproduce**
1. launch app
2. tap [shopping search] 
3. search [bag] -> [enter]
4. tab [+] to search [http://indiamart.com] as 1th tab
5. tab [+] to search [http://indiamart.com] as 2th tab
6. tab [+] to search [http://indiamart.com] as 3th tab
7. tab [+] to search [http://indiamart.com] as 4th tab
8. tab [+] to search [http://indiamart.com]as 5th tab
9. tab [+] to search [http://indiamart.com]as 6th tab

**Expected behavior**
Not show ECsite prompt from 1th to 6th tab

**Actual behavior**
see ECsite prompt from 1th to 6th tab

**Screenshots/videos**

**Device info (please complete the following information):**
 - Device: all
 - Webview : 80.0.3987.117
 - Version : 2.1.9 (18705)

**Reproduce rate**
10/10

**Additional context**

**Comment by youwenliang** [comment]
Could not reproduce from my end, will need to confirm.

**Comment by youwenliang** [comment]
Tested with Daisy. If you access EC sites directly with the link 5 times in a row in will be counted as once, but if you access EC sites from google search results or from top sites it will behave as expected (the prompt won't show on the 6th time visit).

This is not urgent, but might need @benjamin-cheng to look into this if you have time!
