### ISSUE TITLE
Firebase Remote config setting Traditional Chineses

### ISSUE THREAD

**Issue by shsu571** [mozilla-mobile/FirefoxLite#4783]
**Describe the bug**
Firebase Remote config setting Traditional Chinese
Set the condition on Remote config: Traditional Chinese

**Expected behavior**
Users who's phone language is Traditional Chinese will recieve the remote config setting.

**Actual behavior**
Didn't recieve the remote config setting change
example: 5 star popup

**Comment by shsu571** [comment]
@Conjuror  asked Google 
Reply:
Hi there,
 
Thanks for patiently waiting. Our engineers confirmed that this is a bug on our end. Per checking, there's already a fix for this issue, but we can't give a definite timeline or details for when it will be available to production. I suggest you keep an eye out on our release notes to get the latest updates with Firebase features and its services.
 
If there's anything else I can help you with, just let me know.

**Comment by Conjuror** [comment]
More information, this is for monitoring. There's no action we want to take internally now.
