### ISSUE TITLE
[Smart Shopping Search] The cursor wasn't on the right if I used a search suggestion

### ISSUE THREAD

**Issue by tinahsieh** [mozilla-mobile/FirefoxLite#4838]
**Describe the bug**
If I select a search suggestion instead of typing the entire keyword for searching in Smart Shopping Search, the cursor will be on the left of the keyword when I redo search.

**Steps To Reproduce**
1. Go to 'Smart Shopping Search'
2. Click on 'any search suggestion'
3. Search
4. Go back to Search UI
5. The cursor will be on the left.

**Expected behavior**
The cursor will be on the right of the keyword.

**Actual behavior**
It's on the left.

**Reproduce rate**
100%

**Comment by chianger** [comment]
The reproduce step #4 =  tap 'back' to go back to search UI
