### ISSUE TITLE
User feedback crash App

### ISSUE THREAD

**Issue by shsu571** [mozilla-mobile/FirefoxLite#4840]
**Describe the bug**
crashed when open app

**Steps To Reproduce**
1. Open app

**Expected behavior**
Open home.

**Actual behavior**
Crashed and automatically turned off user's phone.

**Device info (please complete the following information):**
 - Device: Vibe X3 Lite
 - OS: Android 6.0
 - Version [2.1.11(18890)]

**Comment by Daisy-pliu** [comment]
Here is the crash report on 2.1.11(18890). Possibly this playstore user encounter these 2 crash.
1. [Homebackground crash  ](https://console.firebase.google.com/u/0/project/zerda-dcf76/crashlytics/app/android:org.mozilla.rocket/issues/f873d96c5c20ad8584f5cc1d32bd28e1?time=last-seven-days&sessionId=5E78023501CE00013D18E5D690EEBFE4_DNE_0_v2)
2. [TransactionHelper.java ](https://console.firebase.google.com/u/0/project/zerda-dcf76/crashlytics/app/android:org.mozilla.rocket/issues/5bdc2d3ef8b88c29633ee204?time=last-seven-days&sessionId=5E782FAD006300011A739009253348C3_DNE_0_v2)
