### ISSUE TITLE
2 Automated cases is gone or ignored 

### ISSUE THREAD

**Issue by Daisy-pliu** [mozilla-mobile/FirefoxLite#4843]
**Describe the bug**
After running automation, I found 
`deleteAllTopSitesAndRelaunchApp_defaultTopSitesAreLoaded`  is gone in the source code and also this `takeScreenshot_screenshotIsCaptured`  is  tagged with @ignored. 
Please dev help investigate, thank you ! 
Then we could discuss whether we want to remove it , modify or add more tests in it.

**Comment by shsu571** [comment]
Already confirmed with @proevan. Need time to check and put into sprint planning but not urgent issue
