### ISSUE TITLE
[Crash] Nokia 2.1 issue

### ISSUE THREAD

**Issue by youwenliang** [mozilla-mobile/FirefoxLite#4853]
**Describe the bug**
App crashed on Nokia 2.1 (E2M)

Playstore review:
![image](https://user-images.githubusercontent.com/8919308/77983384-7f0f5080-7341-11ea-857e-37d3e7cc0fac.png)

**Device info (please complete the following information):**
 - Device: Nokia 2.1 (E2M)
 - OS: Android 9

**Comment by Daisy-pliu** [comment]
> hey mark could you open ticket to track 5.1 ,thanks .
I will  attach below on the ticket. But seems it is not Nokia 2.1 (E2M) , just Nokia 2,1 , so will need dev help investigate.
<sub>[View in Slack](https://mozilla.slack.com/archives/CS7KS9DT6/p1585624016047800)</sub>
