### ISSUE TITLE
FxLite Preview violates Google Play sensitive policy 

### ISSUE THREAD

**Issue by Daisy-pliu** [mozilla-mobile/FirefoxLite#4866]
**Describe the bug**
On 4/3 we got notice that FxLite Preview violates Google Play sensitive policy.  After several forwards, dev team found root cause is our Coronavirus healthcare remote config messages on Homepage may violates the policy,  which will need PM team makes business decision, then release team will follow up on it on Play Store. 
<img width="566" alt="Screen Shot 2020-04-06 at 10 21 03 AM" src="https://user-images.githubusercontent.com/44990878/78517629-8aa2c180-77f0-11ea-9dcd-d1de41a9baf5.png">

**Root cause**
<img width="1174" alt="Screen Shot 2020-04-06 at 10 21 15 AM" src="https://user-images.githubusercontent.com/44990878/78517591-6fd04d00-77f0-11ea-88b4-7f28f2f86268.png">

**Comment by Conjuror** [comment]
Per offline discussion, Wendy is on it. Let's keep it track

**Comment by Daisy-pliu** [comment]
PM replied to Playstore and US team.
<img width="1460" alt="Screen Shot 2020-04-07 at 10 01 42 AM" src="https://user-images.githubusercontent.com/44990878/78622117-dddf4780-78b6-11ea-90a4-67471cc9caf0.png">
