### ISSUE TITLE
[Shopping Search] the website’s bottom bar will be covered at the beginning

### ISSUE THREAD

**Issue by shsu571** [mozilla-mobile/FirefoxLite#4884]
**Describe the bug**
 When you scroll in the Shopping search result tab, he website’s bottom bar will be covered at the beginning.

**Steps To Reproduce**
1. Go to shopping search
2. Search a keyword and see the results
3. See the result website which has bottom bar
4. Will not see the bottom bar ( Unless you scroll)
**Expected behavior**
Users will see bottom bar when they get into tab.

**Actual behavior**
Users will not see bottom bar when they get into tab.

**Screenshots/videos**
If applicable, add screenshots/videos to help explain your problem.

**Device info (please complete the following information):**
 - Version 2.1.14(19257)

**Comment by Daisy-pliu** [comment]
Yes I also found this issue , which may give user bad shopping experience.

**Comment by chianger** [comment]
Per Evan's comment, this issue can also reproduce in normal browsing mode.

**Comment by chianger** [comment]
removed from 4-6 backlog and back to ready-for-development
