### ISSUE TITLE
Find in page search bar disappeared on yahoo.com

### ISSUE THREAD

**Issue by swlibi** [mozilla-mobile/FirefoxLite#4895]
**Describe the bug**
When I use "Find in page" and click the second or third result on yahoo.com it doesn't work.

**Steps To Reproduce**

1. Launch firefox lite preview
2. Go to yahoo.com webpage
3. Click menu > find in page
4. Enter keywords
5. Click the next result
6. The search bar disappeared

**Expected behavior**
Can successfully find the next result

**Actual behavior**
The search bar disappeared

**Device info (please complete the following information):**
 - Device: ASUS_X01AD
 - OS: Android 9
 - Webview 81.0.4044.96
 - Version 2.1.15 19280

**Reproduce rate**
5/5

**Additional context**
It works on other web pages, so far I only find it cannot work on yahoo.

**Comment by Daisy-pliu** [comment]
Not a regression , it also happened on Release build 2.1.13.

**Comment by Daisy-pliu** [comment]
similar result as #3557
