### ISSUE TITLE
Missing data review

### ISSUE THREAD

**Issue by cnevinc** [mozilla-mobile/FirefoxLite#4923]
Please file data review request for #4652, #4660,  #4670, #4722, #4773, #4776, #4776, #4777,  #4784,. #4855

**Comment by shsu571** [comment]
#4777  #4784  -> no data collection request
#4855 
https://docs.google.com/document/d/1PWXIAxfZU77yUYmUERnbTdVC4E0H0BlyIslIlIMNkJI/edit
#4776
https://docs.google.com/document/d/1pCtOtlOHwFTlQYqkoxeSvP22QKITD5w0DasyewxQLGs/edit?usp=sharing
#4722 #4670   https://github.com/mozilla-tw/FirefoxLite/issues/4564
#4660 #4657 #4652 -> we are confirmign with Jack & Joe
