### ISSUE TITLE
Youtube fullscreen issue on Travel video

### ISSUE THREAD

**Issue by Daisy-pliu** [mozilla-mobile/FirefoxLite#4938]
**Steps To Reproduce**
1. launch app
2. tab [travel]
3. search any place
4. tap any Youtube video
5. tap full screen
6. rotate to landscape
7. back to portrait

**Expected behavior**
see video on portrait mode

**Actual behavior**
see a brown line and video disorder

**Screenshots/videos**
Pixel 2:
![Screenshot_20200429-104021](https://user-images.githubusercontent.com/44990878/80556411-141b6d00-8a06-11ea-84ee-85b6d973c512.png)

**Device info (please complete the following information):**
 - Device:  Pixel2 (9.0) :  video disorder 
-  Device: Samsung : brown line and video disorder 
 - Version 2.1.6 (19398)

**Reproduce rate**
5/5

**Additional context**
Not a regression

**Comment by shsu571** [comment]
My pixel 3a  is okay....

**Comment by shsu571** [comment]
Could we check more devices?
