### ISSUE TITLE
[Crash]  MultipartBody.kt line 232 

### ISSUE THREAD

**Issue by shsu571** [mozilla-mobile/FirefoxLite#4943]
**Describe the bug**
crashes 390 ; user affected 13

https://console.firebase.google.com/u/0/project/zerda-dcf76/crashlytics/app/android:org.mozilla.rocket/issues/62aa2aa80d381d51acbb71deb8307f6b?time=last-seven-days&sessionId=5EA82BAC009100011C7E10BC28A2E4D4_DNE_0_v2

**Device info (please complete the following information):**
Samsung
Android  10

This only happens on Version 2.1.16(19398)

**Comment by Daisy-pliu** [comment]
it becomes velocity alert now, impacting ~70 people out of 500.
