### ISSUE TITLE
Several separate windows

### ISSUE THREAD

**Issue by lemanno** [mozilla-mobile/FirefoxLite#4948]
**Describe the bug**

**Steps To Reproduce**
1. Go to 'Main Window'
2. Click on 'News/Games'
3. Open window manager

**Screenshots/videos**

https://rataku.com/i/cj5WE

**Device info (please complete the following information):**
 - Device: [Samsung. Galaxy A10]
 - OS: [e.g. Android 9.0]
 - Webview [e.g. 69.0.3497.100]
 - Version [e.g. 3.3.0(7183).nightly]

**Comment by youwenliang** [comment]
Hi @lemanno, do you mean that there are two Firefox Lite instances when viewing in the window manager? This is actually expected behavior since we want to separate the activities between game&news contents and normal browsing mode. Let us know if you have more questions, thanks!

**Comment by lemanno** [comment]
@youwenliang Yes, exactly.
It seemed strange to me, since this is not in other browsers.
