### ISSUE TITLE
[Feature Enhancement] Swipe tab to  refresh

### ISSUE THREAD

**Issue by shsu571** [mozilla-mobile/FirefoxLite#4959]
**User story**
As a users, I would like use the Android gesture swipe to refresh page

**Acceptance Criteria (how do I know when I’m done?)**
1.Swipe
2.Refreshing icon animation 
3.Refresh page

**Additional context**
The purpose of this feature.
-leave toolbar for more function 
-use Android native gesture to make users can do refresh as they want
-Android material design guideline https://material.io/design/platform-guidance/android-swipe-to-refresh.html
-We will only apply on tab this time. Vertical will keep reload design.
- 5/26 update: only do on normal tab firstly. If want to apply in other mode, PM will make other issue.

**Metric**
https://docs.google.com/spreadsheets/d/15Pqqx1J4HovyYdf_xncsPApucqZFvMJALTvVOGkBTyo/edit#gid=1007897701

**data review**
https://docs.google.com/document/d/1h5mak6hcvQbIX49rKxb8ZIW2OcH9P9AJ-cp9L1Nw7kE/edit#

**Comment by TLHuang** [comment]
Visual spec https://zpl.io/aBJm0Z0

**Comment by youwenliang** [comment]
https://docs.google.com/document/d/1hQhfFUpYgEcD-3P2v4_JfWklKpg7iCAubEVETj8LHo4/edit?usp=sharing

**Comment by lanyliu** [comment]
telemetry spec

method: swipe
object: browser
value: reload

**Comment by proevan** [comment]
@shsu571 is this issue only for normal browsing or it also needs to be implemented in other modes?

**Comment by proevan** [comment]
turn out that we can't detect if web content is consuming the touch event or not using native webkit
