### ISSUE TITLE
When changing the URL, the favicon in the tab tray is displayed incorrectly

### ISSUE THREAD

**Issue by swlibi** [mozilla-mobile/FirefoxLite#5003]
**Describe the bug**
When changing the URL, the favicon in the tab tray is displayed incorrectly

**Steps To Reproduce**
1. Click Shopee or Facebook on top site
2. Click the URL bar
3. Enter any website you want (nba.com)
4. Click tab tray
5. The favicon is displayed incorrectly

**Expected behavior**
The favicon is displayed correctly

**Actual behavior**
The favicon is displayed incorrectly

**Screenshots/videos**
![screenshot_20200526-113303](https://user-images.githubusercontent.com/23470610/82858612-ecf18600-9f46-11ea-81fb-81ba4d6a5e81.png)

**Device info (please complete the following information):**
 - Device: oppo
 - OS: Android 7
 - Webview 83.0.4103.60
 - Version 2.1.18 (19583)

**Reproduce rate**
5/5

**Additional context**
I can reproduce this issue in the previous version

**Comment by Daisy-pliu** [comment]
not a regression . It happens long time ago
