### ISSUE TITLE
[Home customization] Metrics & Data Review

### ISSUE THREAD

**Issue by youwenliang** [mozilla-mobile/FirefoxLite#5031]
**Trello Ticket:**
https://trello.com/c/MyP531a0 

**Spec:** 
https://docs.google.com/spreadsheets/d/1kkLDEpwWSbaMqpR2Pt4ydK7Zt3FSAaEhw0quaTSJJXY/edit?usp=sharing

**Data review:**
https://docs.google.com/document/d/1t_PEsqAs85REsZenhCkt2j761tGL_YIxDi_86a5RM3I/edit?usp=sharing

**UX Spec:**
https://mozilla.invisionapp.com/share/7YXG8U1NEJZ#/419234347_0-0_Cover

**Comment by cnevinc** [comment]
I'll move out the origin data-review request data out of the Google Doc. Since it requires permission and not public available
```
Note: only new ping requirements need this part.
What questions will you answer with this data?
We want to understand if we add a “home customization” feature (including onboarding, theme setting, vertical setting and top site setting), we can encourage more users to stick with us and improve the overall retention.
Why does Mozilla need to answer these questions? Are there benefits for users? Do we need this information to address product or business requirements?
We’d like to get product insights to enhance the user experience from different perspectives (UI design, feature roadmap planning & prioritization, …)
What alternative methods did you consider to answer these questions? Why were they not sufficient?
We don't have any other than user survey and user research, but that is not enough to get granular detailed data.
Can current instrumentation answer these questions?
No.
List all proposed measurements and indicate the category of data collection for each measurement, using the Firefox data collection categories on the Mozilla wiki.
The ping here for review is Category 2 “Interaction data”.
How long will this data be collected? Choose one of the following:
We want to collect this data for 6 months initially and then decide if we want this data to be collected going forward.
What populations will you measure?
Users in targeting markets. Including Indonesia (for e-commerce life feed) and India (for news life feed)
If this data collection is default on, what is the opt-out mechanism for users?
The user can disable "Send usage data" in settings to opt-out.
Please provide a general description of how you will analyze this data.
We'll use Firebase, Amplitude and STMO. Comparing conversion rate, retention rate and usage over time.
Where do you intend to share the results of your analysis?
N/A. Data is for internal feature planning evaluation only
Is there a third-party tool (i.e. not Telemetry) that you are proposing to use for this data collection?
Yes, Firebase.


```

**Comment by cnevinc** [comment]
For 
```
5. List all proposed measurements and indicate the category of data collection for each measurement, using the Firefox data collection categories on the Mozilla wiki.
The ping here for review is Category 2 “Interaction data”.
```
It's great you pointed out the data is cat 2. But I'll need to event list (action, method, object, value.... etc)
I also can't find this info in the document. 

So maybe it's better to do data review once the code is read to merge, and I'll look at the code changes in event.md

**Comment by youwenliang** [comment]
@cnevinc Yes you are right, BI team are still reviewing the metrics so I haven't put the exact event list in the document, will ping you once it's ready, thanks!

**Comment by lanyliu** [comment]
Telemetry [spec](https://docs.google.com/spreadsheets/d/1kkLDEpwWSbaMqpR2Pt4ydK7Zt3FSAaEhw0quaTSJJXY/edit#gid=888392947)

Need [instrumentation](https://docs.google.com/spreadsheets/d/1kkLDEpwWSbaMqpR2Pt4ydK7Zt3FSAaEhw0quaTSJJXY/edit#gid=149972229)

**Comment by yshlin** [comment]
Found one issue on telemetry:

 - after updated to new 2.1.22(20098) (didn't yet clear data), and click__panel__addtopsite, in the extra default=true, but if I remove the same item, default become false (which is supposed to be true)

**Comment by benjamin-cheng** [comment]
>     * after updated to new 2.1.22(20098) (didn't yet clear data), and click__panel__addtopsite, in the extra default=true, but if I remove the same item, default become false (which is supposed to be true)

I've fixed the telemetry issue. Could you please verify by the preview build 2.1.23(20138)? Thank you!

**Comment by chianger** [comment]
Telemetry efforts are actually in the corresponding feature task tickets. This ticket is for general tracking and data review form for PM/BI.

**Comment by lanyliu** [comment]
telemetry timing for "click, contextual_hint, theme" should be on "DONE" button

**Comment by yshlin** [comment]
- Pin topsite position wrong (expeted: 10, actual: 18) on 2nd page 
 - change menu vertical: each click send 2 times after a series of on/off tests

**Comment by shsu571** [comment]
change menu vertical: each click send 2 times after a series of on/off tests
-> This would not be the blocker of this release. So I have another issue to track.
https://github.com/mozilla-tw/FirefoxLite/issues/5267

**Comment by lanyliu** [comment]
done below test
- Pin topsite position wrong (expeted: 10, actual: 18) on 2nd page
- timing for "click, contextual_hint, theme" should be on "DONE" button/ dismiss theme
- expect "show, contextual_hint, theme" only for the on-boarding one
