### ISSUE TITLE
What is the blue exclamation icon in kebab menu?

### ISSUE THREAD

**Issue by seekr** [mozilla-mobile/FirefoxLite#5135]
![Screenshot_20200621-201103_Firefox Lite](https://user-images.githubusercontent.com/2786460/85237297-29a48600-b3fc-11ea-9d25-0ed75f047c48.jpg)

I thought this was the indicator that Turbo Mode is on, but when I switch of Turbo Mode that exclamation point remains. There's no way I can rid of that icon, no matter what I do.

**Comment by youwenliang** [comment]
@seekr Hi, thanks for bringing this up, the indicator is actually related to download issues. Make sure you check your download library and see if there's any failed download attempts. Let us know if you have more questions!
