### ISSUE TITLE
[Feature Enhancement] Brightness Implementation 

### ISSUE THREAD

**Issue by shsu571** [mozilla-mobile/FirefoxLite#5158]
**User story**
As an user, I would like to have same brightness when I use Firefox Lite and Android system.
As an users, I will not feel too bright when I get into Firefox Lite. 

**Problem**
Firefox Lite and Android system have different brightness setting.

**Comment by cnevinc** [comment]
without a spec, this could be m to L

**Comment by tinahsieh** [comment]
Please see the UX spec: https://mozilla.invisionapp.com/share/7YXG8U1NEJZ#/423261690_3-3_Night_Mode_And_Theme
