### ISSUE TITLE
Change Bukalapak's current logo to new logo (Indonesia)

### ISSUE THREAD

**Issue by yowazzzup** [mozilla-mobile/FirefoxLite#5163]
**Remote config name**
Top Sites for Indonesia

**Audience setting**
Indonesia Only

**Parameter + Audience**
New logo files provided by partner:
https://drive.google.com/drive/folders/1WolopaQOgfceL5snl_j6gjovdilEiPZV?usp=sharing

**Expected Online Time**
Anytime, or depends on product decision.

@youwenliang @shsu571

**Comment by youwenliang** [comment]
@yowazzzup Can we ask them to provide new logos as an icon format for the topsites? (72x72 png file)

**Comment by yowazzzup** [comment]
@youwenliang  I've asked Helen to help~(it'll take forever for Bukalapak to reply on customization requests)
@TLHuang Thanks so much

**Comment by shsu571** [comment]
https://github.com/mozilla-tw/FirefoxLite/issues/5118
