### ISSUE TITLE
[Smoke Test] Context menu of link/image has unnecessary scroll bar & effects

### ISSUE THREAD

**Issue by cssjh** [mozilla-mobile/FirefoxLite#517]
As title.
**DuT:** Andromax, Lenovo
**Build:** 653

**Comment by NashTung** [comment]
It can be reproduced and maybe just effect no scroll bar
Video: https://drive.google.com/open?id=1tJ9Bv26egwXggx4k9VybpwDAJf2LBemb

Device: Redmi 4A
Rocket: 2.1.0(4512).nightly
Android: 7.1.2
Android Webview: 66.0.3359.158
