### ISSUE TITLE
Download Management stage0 (spike)

### ISSUE THREAD

**Issue by shsu571** [mozilla-mobile/FirefoxLite#5179]
Transfer from Android download manager to Firefox Lite download manager.

Spec: https://docs.google.com/document/d/1Qjtt4Zatzb5CWV2qDBob-rftswhXmg4WizbcHmqPr30/edit#heading=h.9tgslodf8lb8

**Comment by lanyliu** [comment]
bring [data spec](https://docs.google.com/spreadsheets/d/1o8p47imE-MkaArVYqRxIR5Eh2ZQzlC3vfdUuIgfcONc/edit#gid=888392947) from #5220

**Comment by benjamin-cheng** [comment]
@shsu571 could you please help to confirm the scope of this spike?
- [] Manually pause and resume a download process
- [] Automatically pause and resume a download process
- [] Can download a file from the server with invalid SSL certification
- [] Get download file size before downloading the file
