### ISSUE TITLE
Awesomebar being cutted half in landscape mode

### ISSUE THREAD

**Issue by Daisy-pliu** [mozilla-mobile/FirefoxLite#5184]
**Describe the bug**
Search suggestion (tab) being cutted half in landscape mode

**Steps To Reproduce**
1. go to a website
2. enter landscape mode
3. search

**Expected behavior**
see uncutted search suggestion
**Actual behavior**
see cutted search suggestion

**Screenshots/videos**
<img width="508" alt="Screen Shot 2020-07-01 at 5 13 09 PM" src="https://user-images.githubusercontent.com/44990878/86226679-9703a400-bbbe-11ea-88b2-3662a6f50601.png">

**Device info (please complete the following information):**
 - Device: Pixel4 
 - OS: 9
 - Version : 19949 Preview

**Reproduce rate**

**Additional context**
It is a dogfooding bug reported by Eddie.

**Comment by youwenliang** [comment]
Might need UX to discuss the solution.
