### ISSUE TITLE
Bukalapak Top sites tracking link test

### ISSUE THREAD

**Issue by yowazzzup** [mozilla-mobile/FirefoxLite#5190]
**Describe the bug**
The clicks are tracked but we believe the conversion isn't tracked properly.
For tracking link and more context pls see: 
https://docs.google.com/document/d/1q0PgnSi8hL4BcYAAK5ZPZgFFngDYiF63uHdHl6vyRSo/edit?usp=sharing

**Steps To Reproduce**
Test the top sites tracking link on 2.0 fxlite version.
Make an order (TBD)

**Expected behavior**

**Actual behavior**
A clear and concise description of what you actually discovered.

**Screenshots/videos**
If applicable, add screenshots/videos to help explain your problem.

**Device info (please complete the following information):**
 - Device: [e.g. Pixel2]
 - OS: [e.g. Android 8.1.0]
 - Webview [e.g. 69.0.3497.100]
 - Version [e.g. 3.3.0(7183).nightly]

**Reproduce rate**
How many times you can reproduce such issue, given the testing rounds

**Additional context**

More details on this later

@youwenliang

**Comment by 3xploiton3** [comment]
![Screenshot_2020-07-24-05-59-10-919_org mozilla rocket](https://user-images.githubusercontent.com/19517680/88346693-23932380-cd73-11ea-8f01-477bee9847d7.jpg)


Why use tracking site?

My isp block tracker site
