### ISSUE TITLE
[Top site] Can not add topsite  with correct Frecency 

### ISSUE THREAD

**Issue by Daisy-pliu** [mozilla-mobile/FirefoxLite#5197]
**Steps To Reproduce** 
1. launch app 
2. given Ebay view count is 6 on remote config 
3. open "bbc.com" as new tab and reload "bbc.com" until it reach 6 view counts
4. tap [home icon ]

Actual result:  
4. not show [bbc.com] top site

Expect result:
4.  should show [bbc.com] top site next to Ebay.
But I am not sure it should show at the front or behind [ebay topsite ] need UX confirm@tinahsieh 

**Reproduce rate**
5/5

**Additional context**

**Comment by shsu571** [comment]
This is P0 but not blocker for sprint 4-9 release.

**Comment by shsu571** [comment]
PM and UX need to decide the method of ranking when view times is the same.

**Comment by tinahsieh** [comment]
Is this bug still valid? @Daisy-pliu
