### ISSUE TITLE
Download Management stage 0 

### ISSUE THREAD

**Issue by shsu571** [mozilla-mobile/FirefoxLite#5228]

**Comment by benjamin-cheng** [comment]
1. [ ] Remove callbacks from async content queries
2. [ ] Move EnqueueDownloadTask to DownloadDataSource
3. [ ] Move GetDownloadFileHeaderTask to DownloadDataSource
4. [ ] Move download broadcast receiver to repository/data source 
5. [ ] Move showOpenDownloadSnackBar from DownloadInfoManager to UI layer
6. [ ] Separate download implementation to DownloadDataSource
7. [ ] Combine RelocateService in downloading module
8. [ ] Combine DownloadCompleteReceiver in downloading module
9. [ ] Integrate new DownloadManager
10. [ ] Implement dedicate foreground process for downloading service
