### ISSUE TITLE
[Home customization] Onboarding UI optimization

### ISSUE THREAD

**Issue by shsu571** [mozilla-mobile/FirefoxLite#5299]
options design optimization

**Comment by tinahsieh** [comment]
UX spec update: https://mozilla.invisionapp.com/share/7YXG8U1NEJZ#/419234350_1-1_New_User_Onboarding_Flow_-1-2-

@TLHuang Could you please share the updated visual spec as well? thank you!

**Comment by TLHuang** [comment]
Visual spec: https://zpl.io/2vJkJDe
