### ISSUE TITLE
When downloading a file, it only shows "Unknown" in the download panel

### ISSUE THREAD

**Issue by youwenliang** [mozilla-mobile/FirefoxLite#5304]
**Describe the bug**
When downloading a file, it only shows "Unknown" in the download panel, when I tap the three dot menu can click delete, it says "Cannot find the file"

**Steps To Reproduce**
1. Clear data for Firefox Lite
2. Enter Firefox Lite
3. Visit https://msrp-dev01.appspot.com/api/v1/admin/push/ui?token=3 
4. Tap download to download the file
5. Long press three dot menu to open download panel

**Expected behavior**
- See the file downloading with progress bar.

**Actual behavior**
- See "Unknown" pending...

**Screenshots/videos**
![image](https://user-images.githubusercontent.com/8919308/88900524-0fbf5400-d282-11ea-8b71-6e4c255222ca.png)

**Device info (please complete the following information):**
 - Device: Redmi Note 7 
 - Version: 2.5.1 (20460)

**Reproduce rate**
How many times you can reproduce such issue, given the testing rounds
3/5 (so far only on my device)

**Additional context**
You have to wait for a long time until the download is success, then the "Unknow" will turn back to the file name. After this first encounter, everything went back to normal.

**Comment by youwenliang** [comment]
This is from Google Playstore reviews
Devices that have the same issue:
- Vivo
- Zenphone
- Nokia
- Galaxy
![image](https://user-images.githubusercontent.com/8919308/88902562-f8ce3100-d284-11ea-92ca-cc2e6d3191d6.png)

**Comment by tinahsieh** [comment]
I used Samsung to test the link and saw this result:
![Screenshot_20200730-165838_Firefox Lite](https://user-images.githubusercontent.com/17559807/88903462-544cee80-d286-11ea-80f1-0029c232fb35.jpg)

**Comment by shsu571** [comment]
@Daisy-pliu could you check this? Thank you!
