### ISSUE TITLE
[BUG] Push server send out but client_rec is false

### ISSUE THREAD

**Issue by shsu571** [mozilla-mobile/FirefoxLite#5326]
**Describe the bug**
Some users map with token and send out but client_rec is false.
We want to confirm what is the real behavior of users.
Data: https://docs.google.com/spreadsheets/d/1R8kPGw0kKHqYyaIJry7Qo7DbspOavCFRqI01HUhwcOg/edit#gid=0

**Comment by niyali** [comment]
SQL server status fyi.
https://mozilla.slack.com/archives/CMP856PSM/p1596703615051600?thread_ts=1596683568.049900&cid=CMP856PSM
