### ISSUE TITLE
Width of videos in Play store is incorrect

### ISSUE THREAD

**Issue by Conjuror** [mozilla-mobile/FirefoxLite#534]
As title. Visit play store via Zerda and choose an app with video. While the video is playing, width is incorrect.

Build 653

Tested w/ Chrome, UC, Opera mini. All the three apps redirect user to Play Store. We share the same issue w/ Focus. Suggest to P2 and come back if we have bandwidth.

**Comment by NashTung** [comment]
This issue can be reproduced.
Video:
https://drive.google.com/open?id=1aGYm0EIUsK_LxsTNPGd7oDl8fzEp-SbU

Device: Redmi 4A
Rocket: 2.0.0(4168).nightly
Android: 7.1.2
Android Webview: 66.0.3359.126
