### ISSUE TITLE
Create a 2.6.0 release branch

### ISSUE THREAD

**Issue by st3fan** [mozilla-mobile/FirefoxLite#5342]
Create a `releases_v2.6.0` branch with `release/v2.5.2` as  a starting point. It is unclear what the status of master is, so to be limit the risk we will continue where 2.5.2 left off.

**Comment by st3fan** [comment]
This has been done. See https://github.com/mozilla-mobile/FirefoxLite/tree/releases_v2.6.0 

I've also already changed the `version_name` to `2.6.0` through https://github.com/mozilla-mobile/FirefoxLite/commit/f0ffc2272421844b01a9a5b2ee85408788221119

**Comment by ariefbayu** [comment]
Hi, I've got a lot of issue closed notifications. Are we going to continue development or is there any other reason?

**Comment by cadeyrn** [comment]
>  I've got a lot of issue closed notifications. Are we going to continue development or is there any other reason?

From the readme:

> Notice - Firefox Lite is currently in Maintenance Mode. No active feature is being done on the product. Older Pull Requests and Issues have been marked with the archived label and have been closed. However, if you feel an issue is critical enough to be re-opened, please leave a note on the issue with an explanation.
