### ISSUE TITLE
[BUG] Unsigned apk ?

### ISSUE THREAD

**Issue by promeneur** [mozilla-mobile/FirefoxLite#5353]
Hello

Why a 2.6 unsigned apk ? We can't install an unsigned apk.
This app is a perfect solution for my old Samsung S2 Plus which gets little resources (CPU, memory, throughput,battery, etc.).
This APK is the only solution to install Firefox Lite because I live in France.

For several years I used Firefox Lite, please supply as in the past a signed apk.

Thanks

**Comment by Tobi823** [comment]
Are there any updates? I'm the maintainer of https://f-droid.org/en/packages/de.marmaro.krt.ffupdater/ and updating an existing installation of FirefoxLite requires a valid signature.

**Comment by cadeyrn** [comment]
@st3fan While Firefox Lite 2.6 is still only available as unsigned package that can't be installed Firefox Lite 2.6.1 was not uploaded to GitHub at all. Could you please upload it? Thank you!

**Comment by Ammako** [comment]
Get Aurora Store: https://f-droid.org/en/packages/com.aurora.store/

In your phone's settings, set Aurora Store to handle opening play store links

https://play.google.com/store/apps/details?id=org.mozilla.rocket

Open Firefox Lite play store link in Aurora Store, should be able to access it that way and download, and keep up with updates as well.

Alternatively: https://github.com/duckduckgo/Android

**Comment by st3fan** [comment]
I have uploaded signed APK to https://github.com/mozilla-mobile/FirefoxLite/releases/tag/v2.6.1
