### ISSUE TITLE
Delete Firefox Lite app from the Google Play Store and Galaxy Store

### ISSUE THREAD

**Issue by Nickoriginal** [mozilla-mobile/FirefoxLite#5363]
## As we know, on June 30, 2021 Firefox Lite reached _end-of-life_: https://support.mozilla.org/kb/end-support-firefox-lite
It will no longer receive support or security updates. Firefox Lite should be deleted (making impossible to download) from most popular sources: _Google Play Store_ and _Galaxy Store_ to **don't expose users and their data to danger.**
Despite the information from end-of-life knowledge base: "You will no longer be able to install or reinstall Firefox Lite from the App Store", as of July 5, 2021 it is still available to download.
https://play.google.com/store/apps/details?id=org.mozilla.rocket
<img src = https://user-images.githubusercontent.com/85299944/124365177-f885a500-dc4e-11eb-890e-7465ed2d8d85.jpg width = 45%> <img src = https://user-images.githubusercontent.com/85299944/124364140-329f7880-dc48-11eb-9806-3104275e0157.jpg width = 45%>
_Link to the Firefox Lite app in the Galaxy Store not exists in the internet. You can check it on the Samsung device with Galaxy Store only_.

**Comment by st3fan** [comment]
Firefox Lite will be removed from the Google Play Store once the 2.6.2 update has rolled out.
