### ISSUE TITLE
Unable to capture Boca.gov.tw page properly 

### ISSUE THREAD

**Issue by joechengla** [mozilla-mobile/FirefoxLite#572]
http://www.boca.gov.tw/content.asp?CuItem=175

**Comment by Conjuror** [comment]
We cannot reproduce on several device. @joechengla can you describe more about it?

**Comment by joechengla** [comment]
let's try turning on zoom override?

**Comment by chianger** [comment]
propose P2 but let's confirm with @joechengla

**Comment by Conjuror** [comment]
Assign to @joechengla since he didn't response. :p
