### ISSUE TITLE
Weird animation appears when deleting an item in History

### ISSUE THREAD

**Issue by cssjh** [mozilla-mobile/FirefoxLite#575]
As title. The last item (if exists) will disappear, show up and slide.
**DuT:** Andromax, Samsung
**Build:** 724

**Comment by NashTung** [comment]
It work on me
Video: https://drive.google.com/open?id=1c91bq-FyWj3C-BU7ezsj6HQ0YCUUybai

Device: Redmi 4A
Rocket: 2.1.0(4512).nightly
Android: 7.1.2
Android Webview: 66.0.3359.158
