### ISSUE TITLE
[dogfooding] some keyboard suggestions didn't be catched correctly

### ISSUE THREAD

**Issue by Conjuror** [mozilla-mobile/FirefoxLite#590]
clicking suggested word from keyboard will not replace current word in the input field (try to type "moz" and click "mozilla" from the keyboard list)

build 724

**Comment by Conjuror** [comment]
Gboard is good. Some default keyboards are bad.

**Comment by Conjuror** [comment]
this is between P1 and P2. We(UX, EPM, RD, QA) are not sure about it's priority. PM call. @joechengla

**Comment by joechengla** [comment]
need a device to reproduce this.
my device uses gboard

**Comment by chianger** [comment]
STR:
1. type Moz on the search bar and see autocomplete shows Mozilla.org on the search bar
2. tap on any Suggested words from the virtual keyboard such as "mix"

Actual result
"Mix" doesn't comes on the search bar

**Comment by chianger** [comment]
Focus, and Fennec Nightly have the same issue.
