### ISSUE TITLE
[dogfooding] Press "Refresh" on error page, will see Android webpage not found on the background?

### ISSUE THREAD

**Issue by Conjuror** [mozilla-mobile/FirefoxLite#596]
as title

**Comment by NashTung** [comment]
It seems that the error information on white background before the "Webpage not available" provide on Rocket app after tab "refresh".
Video:
https://drive.google.com/open?id=1zsyTAXSiyg_puqv_5WneCz5Wb_wc0G-7

Device: Redmi 4A
Rocket: 2.0.0(4168).nightly
Android: 7.1.2
Android Webview: 66.0.3359.126
