### ISSUE TITLE
[dogfooding] Youtube will have a big play icon at the beginning of play

### ISSUE THREAD

**Issue by Conjuror** [mozilla-mobile/FirefoxLite#599]
YouTube video playback always start with the first frame showing big PLAY icon; chrome doesn't have that

**Comment by NashTung** [comment]
This issue can be reproduced.
Video:
https://drive.google.com/open?id=1e1o2NnAakEG2gYxHoegMfsortE9W9vZ8

Device: Redmi 4A
Rocket: 2.0.0(4168).nightly
Android: 7.1.2
Android Webview: 66.0.3359.126
