### ISSUE TITLE
[Function] Setting: Block media autoplay

### ISSUE THREAD

**Issue by chianger** [mozilla-mobile/FirefoxLite#60]

**Comment by mTwTm** [comment]
@chianger Joe said it's P2 now.

**Comment by NashTung** [comment]
Is it can be reproduced correctly as below video?
Video: https://drive.google.com/open?id=1jtmGJ-NNLRb7SSmYZ7R4XAWPMjAus6rA

Device: Redmi 4A
Rocket: 2.1.1(4696).nightly
Android: 7.1.2
Android Webview: 67.0.3396.68

**Comment by mTwTm** [comment]
I think this issue is more about html videos configured to be autoplayed so Youtube may not be a good reference site. Maybe this could be helpful: https://videojs.github.io/autoplay-tests/

**Comment by Iey4iej3** [comment]
I second this. Especially, when the Internet fee is proportional to the data usage, it is also important to have an option to disable muted media autoplay.
