### ISSUE TITLE
Hard to find the download files in SD card

### ISSUE THREAD

**Issue by Jacklin-ux** [mozilla-mobile/FirefoxLite#664]
Currently, the files will be saved to SD card>Android>media>gro.allizon.zelda.beta>downloads>others folder, so if I use file manager, it's hard to find them.
Suggest, we can rethink the folder name and layers so that users can find the download files in SD card easily

**Comment by mTwTm** [comment]
We only have access to folders begin from card>Android>media>gro.allizon.zelda.beta, that's the main reason for the design.

**Comment by chianger** [comment]
this is OS level limitation.
