### ISSUE TITLE
[Smoke Test] language setting sent to webpage didn't be updated correctly

### ISSUE THREAD

**Issue by Conjuror** [mozilla-mobile/FirefoxLite#672]
STR:
1. Launch Zerda, set language of Zerda to Indonesian
2. Visit https://send.firefox.com
3. Change language to English
4. Visit https://send.firefox.com
5. Relaunch Zerda and went to https://send.firefox.com

Expected Result:

2. Display in Indonesian
4. Display in English
5. Display in English

Actual Result:

2. Display in Indonesian
4. Display in Indonesian
5. Display in English

Build: 855

**Comment by chianger** [comment]
try to clear cache and retest again

**Comment by Conjuror** [comment]
Invalid if it's caused by Cookie/Cache/Browsing History. Otherwise, it's P1 to have Zerda send correct language to websites.

**Comment by Conjuror** [comment]
Even I clear caches, it's still there. Only re-open the App will get the language settings correct.

**Comment by Conjuror** [comment]
Clear QAwanted and move to P1

**Comment by NashTung** [comment]
It works on me
Video: https://drive.google.com/open?id=1Bw3pxD0Oad7lOKa3Ys8basyiQ2SHAp2R

Device: Redmi 4A
Rocket: 2.1.0(4512).nightly
Android: 7.1.2
Android Webview: 66.0.3359.158

**Comment by mTwTm** [comment]
This is also happening in private browsing.
