### ISSUE TITLE
Can't show the context menu of a SVG when visiting its link

### ISSUE THREAD

**Issue by cssjh** [mozilla-mobile/FirefoxLite#699]
**STR**
1. Browse http://www.president.gov.tw/images/logo.svg
2. Long press on the image -> No context menu shown

**DuT:** Advan, Samsung
**Build:** 887

**Comment by NashTung** [comment]
1. The image does not display on website
Video: https://drive.google.com/open?id=1jHGH7_GcKX6SUcHlEuI4zfrCAmgNPL6H

Device: Advan i5C
Rocket: 2.1.0(4551).nightly
Android: 5.1
Android Webview: 66.0.3359.158

2. It work on me
Video: https://drive.google.com/open?id=1CZx27TjEzjUoeMePGw30QraAPhFIWJmQ

Device: Redmi 4A
Rocket: 2.1.0(4512).nightly
Android: 7.1.2
Android Webview: 66.0.3359.158
