### ISSUE TITLE
[dogfooding] info URL in Screenshot viewer can not open website

### ISSUE THREAD

**Issue by Conjuror** [mozilla-mobile/FirefoxLite#730]
as title. 

Build 950

**Comment by NashTung** [comment]
The issue can be reproduced 
Video: https://drive.google.com/open?id=1mRw2nOzVKJseBwO6NP8jSKVHLcYTNe4D

Device: Redmi 4A
Rocket: 2.1.0(4512).nightly
Android: 7.1.2
Android Webview: 66.0.3359.158
