### ISSUE TITLE
[Smoke Test] Tap About twice will have two about pages

### ISSUE THREAD

**Issue by Conjuror** [mozilla-mobile/FirefoxLite#804]
Build 1072

STR:

1. Launch Zerda
2. Tap Menu, and then Settings
3. Tap About twice

Expected Result:

3. Only one about page is shown

Actual Result:

3. Two about pages are shown

**Comment by chianger** [comment]
tap on the "about" button fairly quick can get you two about pages.

**Comment by NashTung** [comment]
It can be reproduced
Video: https://drive.google.com/open?id=1ERUrfLXXI3jh7C2nzjAGsatVr2PK4f9M

Device: Redmi 4A
Rocket: 2.1.0(4512).nightly
Android: 7.1.2
Android Webview: 66.0.3359.158
