### ISSUE TITLE
[Smoke Test] Searching with context menu will clear browsing stack

### ISSUE THREAD

**Issue by dakaizou** [mozilla-mobile/FirefoxLite#806]
STR:
1. Visit a page with plain text
2. Long tap on the text
3. Tap on the "..." of the context menu
4. Tap on SEARCH IN FIREFOX ROCKET NIGHTLY
5. Tap on back key

Not sure if this is expected.

Build: 1072
DuT: Samsung

**Comment by chianger** [comment]
P2 to let it be fixed together with multitab.

**Comment by NashTung** [comment]
This issue can be reproduced 
Video: 
https://drive.google.com/open?id=1knf6Uog7kMXDjX5v69Vxw6aYgu6ZNgp8

Device: Redmi 4A
Rocket: 2.0.0(4168).nightly
Android: 7.1.2
Android Webview: 66.0.3359.126

**Comment by mTwTm** [comment]
I think this is not relevant anymore with multitab. @Jacklin-ux to confirm.

**Comment by cynthiatang** [comment]
@mlwang32 could you please revise/add a test case for this issue? Thank you
