### ISSUE TITLE
[Smoke Test] Android 5.1 can't search with zerda

### ISSUE THREAD

**Issue by dakaizou** [mozilla-mobile/FirefoxLite#807]
STR:
1. Long tap on plain text
2. Tap on the search symbol on the top right
3. There's no option for zerda

![screenshot](https://lh3.googleusercontent.com/-9NgFXu26g0o/Wb8nZ7EGtiI/AAAAAAAAAr8/fvxX2U6Q2G0V9Kle9hZlhzKxvy8XuSTvgCL0BGAYYCw/h1280/7596172657792657366%253Faccount_id%253D1)
![screenshot](https://lh3.googleusercontent.com/-UK4MYunh1h8/Wb8nF1iqrsI/AAAAAAAAArs/p7w46dQTFWk6VZaiUDcktFptdn4Dj1apgCL0BGAYYCw/h1280/6188001734676542050%253Faccount_id%253D1)

Build: 1072
DuT: Oppo, Advan

**Comment by chianger** [comment]
We didn't implement the "Search intent" in current release.

**Comment by chianger** [comment]
this is a nice-to-have feature.

**Comment by NashTung** [comment]
This issue can be reproduced
Video:
https://drive.google.com/open?id=1h0FyZAYmX5F2Tx3povgBwofH9UtSqDqq

Device: Advan i5C
Rocket: 2.0.0(4168).nightly
Android: 5.1
Android Webview: 51.0.2704.81
