### ISSUE TITLE
Error page screenshot URL

### ISSUE THREAD

**Issue by cssjh** [mozilla-mobile/FirefoxLite#812]
Visit a page which doesn't exist and take a screenshot of it, the URL of the screenshot will be "data:text/html;charset=utf-8;base64,".

Not sure if this is an expected behaviour?

**Build:** 1072

![5909502055125071172 account_id 0](https://user-images.githubusercontent.com/8446577/30530980-c22335dc-9c7d-11e7-814b-5727ac36fcc6.png)

**Comment by Conjuror** [comment]
This could be a limitation for now. There are still choices we can have.

1. put the error link/url in the info field.
2. Leave it as it is now
3. Put something else for all screenshots for error pages
