### ISSUE TITLE
URL bar is too tall

### ISSUE THREAD

**Issue by cssjh** [mozilla-mobile/FirefoxLite#918]
For older Android devices (~5.x), select some texts ->

![2096505942556412520 account_id 0](https://user-images.githubusercontent.com/8446577/30798811-73d11b84-a20d-11e7-87d0-ac898a7b319c.png)

**Build:** 1158

**Comment by NashTung** [comment]
It can be reproduced but i does not figure out what means url is tall 
Picture:
![verify_bug_918](https://user-images.githubusercontent.com/38277638/40532407-eec3ac70-6031-11e8-8714-c934b25b9c66.png)


Device: Advan i5C
Rocket: 2.1.0(4551).nightly
Android: 5.1
Android Webview: 66.0.3359.158

**Comment by mTwTm** [comment]
I guess that means there are some extra space between the context menu at the top and the url bar. Not sure if the space is something we cannot change though.
