### ISSUE TITLE
support mixed contents 

### ISSUE THREAD

**Issue by joechengla** [mozilla-mobile/FirefoxLite#954]
https://developer.mozilla.org/en-US/docs/Web/Security/Mixed_content

**Comment by mTwTm** [comment]
New issue related to mixed contents: Play audio from http://indeks.kompas.com/radio/sonora

**Comment by weslyhuang** [comment]
may need a SUMO update for it.

**Comment by cnevinc** [comment]
After discussion. 
1. We'll default allow mixed content.
2. We'll create a setting to let users disable it.
3. In the future, we'll need to provide a hint to the users.
This behavior will need to document somewhere.

**Comment by joechengla** [comment]
suggest to include a learn more SUMO page as well
